**Author**: Felipe Matheus
**Purpose**: Experiment launcher for the annealing **tensile strength (UTS)** surrogate.

Same architecture as the IACS launcher: data preparation lives in
`src/pipelines/AnnealingPipeline.py` (composition resolution + IRI/GBEI via
`ChemicalFeatureEngineering`), and the modelling pipeline lives in
`src/modeling/Experiments.py`, which is process-agnostic — the SAME
`ExperimentRunner` is reused; only the `ExperimentConfig` changes (target,
features, physical bounds). No new class needed.

Kept in step with `notebooks/modeling/annealing_uts.ipynb`: same schema date,
same feature list (GBEI included).

Results layout: `models/annealing_uts/experiments/`
(`experiments_log.csv` + one folder per run).

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner
from src.pipelines.AnnealingPipeline import AnnealingDataPipeline

from config.Variables import Variables
from config.bags_compositions import ALL_SAMPLES
from config.elements_coefficients import RESISTIVITY_FACTORS, ENRICHMENT_FACTORS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# ---- Surrogate identity ----
TARGET = "tensile_strength_final"
# GBEI is composition-derived (ChemicalFeatureEngineering), not a raw column.
ALL_FEATURES = ["IRI", "measured_initial_diameter", "GBEI", "purity", "tensile_strength",
                "temperature", "time"]
PROCESS = "annealing_uts"

# ---- Schemas (kept in step with notebooks/modeling/annealing_uts.ipynb) ----
# Bump both to "051026" when that notebook moves to the newer schema.
ANNEALING_SCHEMA_DATE = "051026"
SN_SCHEMA_DATE = "051026"
FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{ANNEALING_SCHEMA_DATE}.csv"
FILE_NAME_SN_COMPOSITION = f"serial-number-encoding_{SN_SCHEMA_DATE}.csv"

ID = "IRI-GBEI-comparison"
TAG = f"annealing-schema{ANNEALING_SCHEMA_DATE}_{ID}"

# ---- Physical constraints (inference-time truncation) ----
Y_MAX = None
Y_MIN = 0.0     # tensile strength cannot be negative

GRID = {
    "time_limit_a": [1200, 3600],
    # "num_bag_folds_a": [10, 15, 20],
    "features": [
        ("IRI", "measured_initial_diameter", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("IRI", "purity", "measured_initial_diameter", "tensile_strength", "temperature", "time"),  # pre-GBEI baseline
        ("IRI", "measured_initial_diameter", "GBEI", "tensile_strength", "temperature", "time"), # no purity
        ("IRI", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("measured_initial_diameter", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("purity", "measured_initial_diameter", "tensile_strength", "temperature", "time"),  # pre-GBEI baseline
        ("measured_initial_diameter", "GBEI", "tensile_strength", "temperature", "time"), # no purity
        ("GBEI", "purity", "tensile_strength", "temperature", "time"),
    ],
    # NOTE: "weight_on_essay_rows" is no longer sweepable — the pipeline output
    # carries no `is_essay` column, so anything but 1.0 makes the runner raise.
}

# Raw columns the pipeline keeps before feature engineering. `material_reference`
# is never a model feature, but ChemicalFeatureEngineering resolves it into the
# composition that IRI and GBEI are computed from, so it must survive here.
ANNEALING_FEATURES = [
    "experiment_id",
    "material_reference",
    "purity",
    "measured_initial_diameter",
    "temperature",
    "time",
    "iacs",
    "tensile_strength",
    "elongation",
    "iacs_final",
    "tensile_strength_final",
    "elongation_final",
]

# 2. Data

`AnnealingDataPipeline` replaces the old `proc.process_annealing_uts` call
(that method was moved out of `Processing`). It performs the same preparation
as `notebooks/modeling/annealing_uts.ipynb`, run once here.

In [5]:
# One pipeline object owns the whole preparation: drop all-NaN rows, select
# ANNEALING_FEATURES, resolve every material_reference to a composition, and
# attach IRI + GBEI. `pipe.df_iri_gbei` is the enriched frame the getters slice.
pipe = AnnealingDataPipeline(
    df_annealing_schema_raw=pd.read_csv(
        os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA)
    ),
    annealing_features=ANNEALING_FEATURES,
    df_sn=pd.read_csv(
        os.path.join(varv.PATHS.data_structured, FILE_NAME_SN_COMPOSITION)
    ),
    all_samples=ALL_SAMPLES,
    resistivity_factors=RESISTIVITY_FACTORS,
    enrichment_factors=ENRICHMENT_FACTORS,
)

df, df_val = pipe.get_uts_df_df_val(
    features_uts=ALL_FEATURES,
    target_uts=TARGET,
)

print(f"train: {df.shape} | val: {df_val.shape}")
df.head()

train: (53, 8) | val: (10, 8)

,IRI,initial_diameter,GBEI,purity,tensile_strength,temperature,time,tensile_strength_final
0,0.195105,2.160000,0.001038,99.9,391.690000,573,30.0,249.78
1,0.195105,2.182333,0.001038,99.9,387.595254,573,30.0,255.01
2,0.233275,1.200000,0.002674,99.9,431.580000,523,30.0,247.08
3,0.233275,1.200000,0.002674,99.9,431.580000,523,60.0,242.21
4,0.233275,1.200000,0.002674,99.9,431.580000,523,90.0,239.64

In [6]:
# Sanity check BEFORE training: an unresolved material_reference yields NaN
# IRI/GBEI, and the getter's .dropna() then removes those rows silently. This
# report is the fastest way to see a typo'd reference or a blend whose bag
# weights did not sum to 1.
report = pipe.chfe.resolution_report(pipe.df_feat)
print(f"unresolved references: {(~report['resolved']).sum()}")
report

unresolved references: 0

,n_rows,source,resolved,raw weight sum,recipe,problem
material_reference,,,,,,
Cu-ETP,12,direct sample,True,NaN,,
Cu-T2,9,direct sample,True,NaN,,
SN015,9,blend,True,1.0,"1B_sac2=0.4047, 1B_sac3=0.4047, 1B_sac5=0.1906",
SN014,6,blend,True,1.0,1B_sac2=1,
SN021,6,blend,True,1.0,"1A_sac1=0.02, 1A_sac2=0.02, 1B_sac2=0.02, 1B_s...",
SN019,5,blend,True,1.0,"1A_sac1=0.3, 2N_sac2=0.6952, echantillon_2N=0....",
C14500,3,direct sample,True,NaN,,
SN027,3,blend,True,1.0,"1B_sac3=0.05, 1B_sac4=0.05, 1B_sac5=0.05, 1B_s...",
SN025,2,blend,True,1.0,"1B_sac2=0.1, 1B_sac3=0.1, 1B_sac5=0.1, echanti...",
SN016,2,blend,True,1.0,"1B_sac2=0.2305, 1B_sac3=0.2305, 1B_sac5=0.2305...",
SN024,1,blend,True,1.0,"1B_sac6=0.1, echantillon_1=0.225, echantillon_...",
SN029,1,blend,True,1.0,"1A_sac1=0.10273, 1A_sac2=0.10273, 1B_sac1=0.10...",

# 3. Base config

In [7]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a="best_quality",
    presets_b="best_quality",
    y_max=Y_MAX,
    y_min=Y_MIN,
    # `weight_on_essay_rows` stays at its 1.0 default: the pipeline output has
    # no `is_essay` column, and any other value would make the runner raise.
    # Same reason `use_shared_folds` stays False (fold stratification needs it).
)
print(base.run_id)

annealing-schema070926_IRI-GBEI-comparison__3193d51a

# 4. Single run (sanity check before any grid)

Run the base config alone first; then repeat 2-3x with `tag="uts-v1-rep2"`
etc. to measure run-to-run noise (the floor below which grid differences
mean nothing).

In [8]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-09-09 17:53:11,677 | INFO | src.modeling.Experiments | === Running annealing-schema070926_IRI-GBEI-comparison__3193d51a ===
2026-09-09 17:53:11,678 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)

=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       4.93 GB / 31.57 GB (15.6%)
Disk Space Avail:   697.01 GB / 932.08 GB (74.8%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3193d51a\model_a"
Train Data Rows:    53
Train Data Columns: 8
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (331.25, 223.43, 251.70717, 23.98799)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5003.03 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.94s of the 119.93s of remaining time.
2026-09-09 17:53:21,660	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-23.1675	 = Validation score   (-root_mean_squared_error)
	3.26s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 79.42s of the 79.40s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.96%)
	-23.0181	 = Validation score   (-root_mean_squared_error)
	3.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 62.64s of the 62.62s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-15.17	 = Validation score   (-root_mean_squared_error)
	0.79s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 61.71s of the 61.70s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=5.50%)
	-14.2355	 = Validation score   (-root_mean_squared_error)
	7.48s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 46.56s of the 46.55s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-17.975	 = Validation score   (-root_mean_squared_error)
	0.7s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 45.66s of the 45.64s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.3845	 = Validation score   (-root_mean_squared_error)
	20.39s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 18.51s of the 18.50s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.08%)
	-14.9958	 = Validation score   (-root_mean_squared_error)
	3.95s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 6.80s of the 6.79s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.94s of the -434.75s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/11.1 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 0.619, 'XGBoost_BAG_L1': 0.381}
	-13.7539	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 554.81s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 241.4 rows/s (11 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3193d51a\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.00 GB / 31.57 GB (34.8%)
Disk Space Avail:   696.53 GB / 932.08 GB (74.7%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3193d51a\model_b"
Train Data Rows:    53
Train Data Columns: 7
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (8.012079610210296, -13.815510557964274, -0.68816, 7.72401)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11196.19 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.95s of the 59.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-7.5046	 = Validation score   (-root_mean_squared_error)
	3.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 48.46s of the 48.45s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.17%)
	-7.4865	 = Validation score   (-root_mean_squared_error)
	2.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 35.31s of the 35.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-8.4401	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 34.49s of the 34.48s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.58%)
	-7.2865	 = Validation score   (-root_mean_squared_error)
	4.98s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 20.00s of the 19.99s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-8.1528	 = Validation score   (-root_mean_squared_error)
	0.72s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 19.16s of the 19.14s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-6.8985	 = Validation score   (-root_mean_squared_error)
	16.47s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.96s of the -8.57s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/10.8 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 1.0}
	-6.8985	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 68.63s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 184.7 rows/s (11 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3193d51a\model_b")
2026-09-09 18:03:53,897 | INFO | src.modeling.Experiments | Validation (n=10): rmse=2.7742 mae=2.1347
2026-09-09 18:03:53,977 | INFO | src.modeling.Experiments | Done annealing-schema070926_IRI-GBEI-comparison__3193d51a in 642.3s

{'rmse': 13.753860893195059,
 'mae': 8.180059987194133,
 'mape': 3.0558830374838535,
 'r2': 0.6649310380275492}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

**Caveat — where this `df_val` comes from.** The pipeline getter builds it as a
random 20 % sample *of `df` itself* when no `df_val` is passed, so those rows
are inside the training data and the val metrics are IN-SAMPLE and optimistic.
Pass a genuinely held-out frame to the getter to make them honest — it must
carry the same engineered columns (`IRI` / `GBEI` included), which in practice
means running it through `pipe` too.

In [9]:
df_val

,IRI,initial_diameter,GBEI,purity,tensile_strength,temperature,time,tensile_strength_final
19,0.402535,1.2,0.006830,99.9800,335.21,573,60.0,245.00
41,0.525991,2.2,0.264027,99.7036,362.31,673,60.0,235.61
47,0.467823,2.2,0.207493,99.7637,367.04,673,60.0,231.44
12,0.195105,1.2,0.001038,99.9000,397.09,573,30.0,261.32
43,0.525991,2.2,0.264027,99.7036,362.31,773,60.0,232.15
5,0.233275,1.2,0.002674,99.9000,431.58,573,30.0,232.03
17,0.195105,1.2,0.001038,99.9000,397.09,523,90.0,259.14
50,0.542737,1.0,0.268018,99.6985,367.73,723,60.0,239.69
3,0.233275,1.2,0.002674,99.9000,431.58,523,60.0,242.21
32,0.419799,0.8,0.011525,99.9740,347.70,673,30.0,247.19

In [10]:
result["artifacts"]["validation_metrics"]

{'rmse': 2.7742406927660737,
 'mae': 2.134698944132006,
 'mape': 0.8955299846281732,
 'r2': 0.9269642286821423,
 'coverage': {0.5: 0.9, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}}

In [11]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [12]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [13]:
result

{'cfg': ExperimentConfig(process='annealing_uts', tag='annealing-schema070926_IRI-GBEI-comparison', base_tag=None, target='tensile_strength_final', features=('IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='best_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=0.0, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': Path('../../models/annealing_uts/experiments/annealing-schema070926_IRI-GBEI-comparison/annealing-schema070926_IRI-GBEI-comparison__3193d51a'),
 'artifacts': {'config': {'process': 'annealing_uts',
   'tag': 'annealing-schema070926_IRI-GBEI-comparison',
   'base_tag': None,
   'target': 'tensile_strength_final',
   'features': ['IRI',
    'initial_diameter',
    'GBEI',
    'purity',
    'tensile_strength',
    'temperature',
    'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'best_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': 0.0,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['IRI',
   'initial_diameter',
   'GBEI',
   'purity',
   'tensile_strength',
   'temperature',
   'time'],
  'target': 'tensile_strength_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1'],
  'weights': array([0.        , 0.        , 0.        , 0.61904752, 0.        ,
         0.        , 0.38095248]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 1.4838933452665515e-05,
  'variance_floor': 5.754234822206097,
  'recalibration_c': 2.0450901638744012,
  'ood_ref': {'features': ['IRI',
    'initial_diameter',
    'GBEI',
    'purity',
    'tensile_strength',
    'temperature',
    'time'],
   'mean': array([3.82777511e-01, 1.47815723e+00, 8.57125997e-02, 9.98662019e+01,
          3.76785005e+02, 6.44509434e+02, 5.07075472e+01]),
   'cov_inv': array([[ 1.89016707e+02, -5.12117051e-02, -9.05406344e+01,
            2.20114185e+01,  4.18907648e-01, -4.40695127e-02,
           -5.48383529e-02],
          [-5.12117051e-02,  5.37577017e+00, -6.95836215e+00,
            7.24122362e+00,  7.34813427e-04, -1.14400273e-03,
           -6.28513969e-03],
          [-9.05406344e+01, -6.95836215e+00,  3.23424488e+02,
            2.05810298e+02,  1.74350309e-02, -2.03555395e-02,
           -3.59247851e-02],
          [ 2.20114185e+01,  7.24122362e+00,  2.05810298e+02,
            2.92882955e+02,  2.98992601e-01,  3.37791981e-03,
            1.02414099e-02],
          [ 4.18907648e-01,  7.34813427e-04,  1.74350309e-02,
            2.98992601e-01,  2.27007551e-03,  9.23923614e-06,
           -2.56148039e-04],
          [-4.40695127e-02, -1.14400273e-03, -2.03555395e-02,
            3.37791981e-03,  9.23923614e-06,  1.47953409e-04,
            1.76437855e-04],
          [-5.48383529e-02, -6.28513969e-03, -3.59247851e-02,
            1.02414099e-02, -2.56148039e-04,  1.76437855e-04,
            1.87729611e-03]]),
   'd_ref': 3.111257220562557,
   'ranges': {'IRI': (0.195105, 0.7207775779124422),
    'initial_diameter': (0.8, 2.2),
    'GBEI': (0.0010379999999999999, 0.2966417158930622),
    'purity': (99.6675, 99.98),
    'tensile_strength': (335.21, 431.58),
    'temperature': (523.0, 923.0),
    'time': (0.5, 105.0)}},
  'y_max': None,
  'y_min': 0.0,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.264151 -0.235849
  1   0.80            0.433962 -0.366038
  2   0.90            0.603774 -0.296226
  3   0.95            0.698113 -0.251887,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.471698 -0.028302
  1   0.80            0.867925  0.067925
  2   0.90            0.886792 -0.013208
  3   0.95            0.943396 -0.006604,
  'aleatoric_diagnostics': {'n_total': 53,
   'n_truncated': 13,
   'pct_truncated': 24.528301886792452,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 3017.185161143319,
   'r_tilde_sq_mean': 169.11748513165122,
   'r_tilde_sq_median': 17.75304884011783},
  'metrics': {'rmse': 13.753860893195059,
   'mae': 8.180059987194133,
   'mape': 3.0558830374838535,
   'r2': 0.6649310380275492},
  'validation_metrics': {'rmse': 2.7742406927660737,
   'mae': 2.134698944132006,
   'mape': 0.8955299846281732,
   'r2': 0.9269642286821423,
   'coverage': {0.5: 0.9, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}},
  'dataset_hash': '7b3dd9e4'},
 'log_row': {'run_id': 'annealing-schema070926_IRI-GBEI-comparison__3193d51a',
  'timestamp': '2026-09-09T18:03:53',
  'elapsed_s': 642.3,
  'n_rows': 53,
  'dataset_hash': '7b3dd9e4',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_uts\\experiments\\annealing-schema070926_IRI-GBEI-comparison\\annealing-schema070926_IRI-GBEI-comparison__3193d51a',
  'cfg_process': 'annealing_uts',
  'cfg_tag': 'annealing-schema070926_IRI-GBEI-comparison',
  'cfg_base_tag': None,
  'cfg_target': 'tensile_strength_final',
  'cfg_features': 'IRI|initial_diameter|GBEI|purity|tensile_strength|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'best_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': 0.0,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'cfg_group_col': None,
  'rmse': 13.75386,
  'mae': 8.18006,
  'mape': 3.05588,
  'r2': 0.66493,
  'cov_0.5': 0.4717,
  'cov_0.8': 0.8679,
  'cov_0.9': 0.8868,
  'cov_0.95': 0.9434,
  'c_opt': 2.0451,
  'pct_truncated_aleat': 24.53,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 2.88213,
  'mean_sigma_aleat': 2.62277,
  'n_val': 10,
  'val_rmse': 2.77424,
  'val_mae': 2.1347,
  'val_mape': 0.89553,
  'val_r2': 0.92696,
  'val_cov_0.5': 0.9,
  'val_cov_0.8': 1.0,
  'val_cov_0.9': 1.0,
  'val_cov_0.95': 1.0},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x17581185390>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x175889bde10>}

# 6. Grid

In [14]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-09-09 18:03:57,415 | INFO | src.modeling.Experiments | Grid: 16 runs over ['time_limit_a', 'features']
2026-09-09 18:03:57,417 | INFO | src.modeling.Experiments | === Running annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__fd18e049 ===
2026-09-09 18:03:57,419 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.58 GB / 31.57 GB (36.7%)
Disk Space Avail:   696.49 GB / 932.08 GB (74.7%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 1200s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__fd18e049\model_a"
Train Data Rows:    53
Train Data Columns: 8
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (331.25, 223.43, 251.70717, 23.98799)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11756.85 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['IRI', 'initial_diameter', 'GBEI', 'purity', 'tensile_strength', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1199.96s of the 1199.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-23.1675	 = Validation score   (-root_mean_squared_error)
	3.04s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1188.46s of the 1188.44s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.15%)
	-23.0181	 = Validation score   (-root_mean_squared_error)
	3.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 1174.61s of the 1174.59s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-15.17	 = Validation score   (-root_mean_squared_error)
	0.66s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1173.80s of the 1173.78s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.18%)
	-14.2355	 = Validation score   (-root_mean_squared_error)
	4.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 1160.94s of the 1160.92s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-17.975	 = Validation score   (-root_mean_squared_error)
	0.74s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1160.06s of the 1160.04s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.3845	 = Validation score   (-root_mean_squared_error)
	18.64s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1132.96s of the 1132.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.06%)
	-14.9958	 = Validation score   (-root_mean_squared_error)
	2.2s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1120.12s of the 1120.10s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.6741	 = Validation score   (-root_mean_squared_error)
	24.71s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1087.47s of the 1087.45s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.71%)
	-12.2102	 = Validation score   (-root_mean_squared_error)
	3.58s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 1075.98s of the 1075.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.57%)
	-14.6044	 = Validation score   (-root_mean_squared_error)
	5.62s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 1060.49s of the 1060.47s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-19.5622	 = Validation score   (-root_mean_squared_error)
	16.18s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 1036.34s of the 1036.33s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.31%)
	-12.1362	 = Validation score   (-root_mean_squared_error)
	4.15s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 1022.06s of the 1022.04s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.4873	 = Validation score   (-root_mean_squared_error)
	17.37s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 993.88s of the 993.87s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=4.33%)
	-16.5941	 = Validation score   (-root_mean_squared_error)
	22.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 964.34s of the 964.32s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.07%)
	-24.3523	 = Validation score   (-root_mean_squared_error)
	2.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 954.87s of the 954.85s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.36	 = Validation score   (-root_mean_squared_error)
	20.44s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 926.67s of the 926.65s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
	-16.7154	 = Validation score   (-root_mean_squared_error)
	5.62s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 912.59s of the 912.57s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-18.7354	 = Validation score   (-root_mean_squared_error)
	0.79s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 911.64s of the 911.62s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=4.09%)
	-12.9221	 = Validation score   (-root_mean_squared_error)
	92.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 806.11s of the 806.10s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.038	 = Validation score   (-root_mean_squared_error)
	18.17s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 780.09s of the 780.08s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.73%)
	-15.2091	 = Validation score   (-root_mean_squared_error)
	8.23s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 762.13s of the 762.11s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-15.4641	 = Validation score   (-root_mean_squared_error)
	0.92s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 761.06s of the 761.05s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.57%)
	-15.0555	 = Validation score   (-root_mean_squared_error)
	3.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 749.37s of the 749.36s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-19.7736	 = Validation score   (-root_mean_squared_error)
	18.03s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 721.90s of the 721.88s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.05%)
	-15.5932	 = Validation score   (-root_mean_squared_error)
	1.8s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 711.18s of the 711.16s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-16.7944	 = Validation score   (-root_mean_squared_error)
	16.96s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 684.19s of the 684.18s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.50%)
	-24.3523	 = Validation score   (-root_mean_squared_error)
	3.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 671.89s of the 671.87s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-19.9455	 = Validation score   (-root_mean_squared_error)
	21.01s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 642.03s of the 642.01s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.57%)
	-13.9886	 = Validation score   (-root_mean_squared_error)
	100.21s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 532.14s of the 532.13s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-21.0941	 = Validation score   (-root_mean_squared_error)
	19.04s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 503.95s of the 503.93s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.10%)
	-15.5746	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 492.91s of the 492.89s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-21.5572	 = Validation score   (-root_mean_squared_error)
	0.57s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 492.19s of the 492.17s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.08%)
	-14.4754	 = Validation score   (-root_mean_squared_error)
	53.36s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 433.68s of the 433.67s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-19.5521	 = Validation score   (-root_mean_squared_error)
	14.03s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 410.76s of the 410.75s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-22.0943	 = Validation score   (-root_mean_squared_error)
	9.88s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 396.76s of the 396.74s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.05%)
	-12.2174	 = Validation score   (-root_mean_squared_error)
	2.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 390.49s of the 390.47s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-20.9501	 = Validation score   (-root_mean_squared_error)
	10.96s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 375.61s of the 375.59s of remaining time.

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema070926_IRI-GBEI-comparison__3193d51a,2026-09-09T18:03:53,642.3,53,7b3dd9e4,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3193d51a,annealing_uts,annealing-schema070926_IRI-GBEI-comparison,NaN,tensile_strength_final,...,2.62277,10,2.77424,2.13470,0.89553,0.92696,0.9,1.0,1.0,1.0
1,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__fd18e049,2026-09-09T18:26:01,1324.5,53,7b3dd9e4,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__fd18e049,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.55826,4.46585,1.83570,0.59185,0.5,0.9,1.0,1.0
2,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__acdfa7d7,2026-09-09T18:48:31,1349.8,53,093630cc,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__acdfa7d7,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,5.86731,4.45140,1.82970,0.67332,0.6,0.8,1.0,1.0
3,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__586a71ee,2026-09-09T19:10:57,1345.3,53,df4f6b38,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__586a71ee,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.09796,4.60574,1.88936,0.64713,0.5,0.9,1.0,1.0
4,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time__74d819ca,2026-09-09T19:40:38,1781.3,53,c975a4df,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time__74d819ca,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,3.63139,2.69226,1.11143,0.87486,0.9,1.0,1.0,1.0
5,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__e1b3cb35,2026-09-09T20:03:15,1357.1,53,4f17a278,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__e1b3cb35,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.47086,4.81298,1.97736,0.60265,0.5,0.7,0.7,0.8
6,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=purity-initial_diameter-tensile_strength-temperature-time__6131c2ea,2026-09-09T20:25:41,1345.6,53,7c5ce26e,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=purity-initial_diameter-tensile_strength-temperature-time__6131c2ea,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,4.07130,2.73358,1.13250,0.84271,0.9,0.9,0.9,1.0
7,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-tensile_strength-temperature-time__f7ab4bf7,2026-09-09T20:48:45,1384.0,53,cf43b5f6,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-tensile_strength-temperature-time__f7ab4bf7,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.44531,10,5.82463,4.52840,1.86679,0.67805,0.4,0.9,1.0,1.0
8,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-purity-tensile_strength-temperature-time__50c84a41,2026-09-09T21:10:54,1328.7,53,8870f5f4,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-purity-tensile_strength-temperature-time__50c84a41,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,3.10153,2.45788,1.01638,0.90872,0.7,0.8,0.9,1.0
9,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__7e300edf,2026-09-09T21:56:58,2763.9,53,7b3dd9e4,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__7e300edf,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,5.78661,4.24371,1.75196,0.68224,0.5,0.9,1.0,1.0
10,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__df51ef9b,2026-09-09T22:38:47,2508.9,53,093630cc,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__df51ef9b,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.02195,4.68702,1.93282,0.65587,0.5,0.9,1.0,1.0
11,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__fc66f73a,2026-09-09T23:22:44,2637.2,53,df4f6b38,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__fc66f73a,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.76850,5.27101,2.17147,0.56526,0.4,0.8,0.9,0.9
12,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-GBEI-purity-tensile_strength-temperature-time__0e223119,2026-09-10T00:13:42,3057.8,53,c975a4df,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-GBEI-purity-tensile_strength-temperature-time__0e223119,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,3.71765,2.74123,1.13135,0.86885,0.9,1.0,1.0,1.0
13,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__d67f1630,2026-09-10T01:03:31,2988.5,53,4f17a278,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__d67f1630,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,6.08181,4.80743,1.98298,0.64899,0.5,0.8,0.9,1.0
14,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=purity-initial_diameter-tensile_strength-temperature-time__522cf548,2026-09-10T01:42:39,2348.3,53,7c5ce26e,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=purity-initial_diameter-tensile_strength-temperature-time__522cf548,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.39880,10,4.63692,3.44127,1.42388,0.79596,0.8,0.9,0.9,1.0
15,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-tensile_strength-temperature-time__3b331471,2026-09-10T02:15:00,1940.5,53,cf43b5f6,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-tensile_strength-temperature-time__3b331471,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.43943,10,5.88369,4.64302,1.91822,0.67149,0.5,0.9,1.0,1.0
16,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-purity-tensile_strength-temperature-time__46f92a7d,2026-09-10T02:38:10,1389.9,53,8870f5f4,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-purity-tensile_strength-temperature-time__46f92a7d,annealing_uts,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-purity-tensile_strength-temperature-time,annealing-schema070926_IRI-GBEI-comparison,tensile_strength_final,...,2.59482,10,3.14441,2.49112,1.02774,0.90617,0.7,0.9,0.9,1.0

# 7. Inspect results

In [15]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_num_bag_folds_a", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9",
    "c_opt", "pct_truncated_aleat", "mean_sigma_epist", "mean_sigma_aleat",
    "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_num_bag_folds_a,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
8,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-purity-tensile_strength-temperature-time__50c84a41,1200,5,GBEI|purity|tensile_strength|temperature|time,10.49056,6.79087,0.9057,3.10153,2.45788,0.9,1.4057,47.17,5.56373,2.39880,1328.7
4,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time__74d819ca,1200,5,IRI|GBEI|purity|tensile_strength|temperature|time,10.83036,6.83093,0.9245,3.63139,2.69226,1.0,1.6737,56.60,5.63439,2.39880,1781.3
12,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-GBEI-purity-tensile_strength-temperature-time__0e223119,3600,5,IRI|GBEI|purity|tensile_strength|temperature|time,10.84531,6.83422,0.9057,3.71765,2.74123,1.0,1.7113,56.60,5.57502,2.39880,3057.8
16,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-purity-tensile_strength-temperature-time__46f92a7d,3600,5,GBEI|purity|tensile_strength|temperature|time,10.84586,6.71500,0.9057,3.14441,2.49112,0.9,1.4549,47.17,4.88978,2.59482,1389.9
5,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__e1b3cb35,1200,5,initial_diameter|GBEI|purity|tensile_strength|temperature|time,11.21044,6.77705,0.8868,6.47086,4.81298,0.7,1.3573,62.26,6.56717,2.39880,1357.1
15,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-tensile_strength-temperature-time__3b331471,3600,5,initial_diameter|GBEI|tensile_strength|temperature|time,11.22773,6.95897,0.9057,5.88369,4.64302,1.0,1.4308,43.40,5.20328,2.43943,1940.5
1,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__fd18e049,1200,5,IRI|initial_diameter|GBEI|purity|tensile_strength|temperature|time,11.24788,7.48196,0.9434,6.55826,4.46585,1.0,1.4549,56.60,6.63989,2.39880,1324.5
9,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__7e300edf,3600,5,IRI|initial_diameter|GBEI|purity|tensile_strength|temperature|time,11.46394,7.04580,0.9057,5.78661,4.24371,1.0,1.4549,41.51,4.80739,2.39880,2763.9
11,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__fc66f73a,3600,5,IRI|initial_diameter|GBEI|tensile_strength|temperature|time,11.48264,7.02914,0.9057,6.76850,5.27101,0.9,1.4311,49.06,5.38822,2.39880,2637.2
3,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__586a71ee,1200,5,IRI|initial_diameter|GBEI|tensile_strength|temperature|time,11.50766,7.07108,0.9245,6.09796,4.60574,1.0,1.5379,52.83,5.67644,2.39880,1345.3
7,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-GBEI-tensile_strength-temperature-time__f7ab4bf7,1200,5,initial_diameter|GBEI|tensile_strength|temperature|time,11.54930,7.08151,0.9057,5.82463,4.52840,1.0,1.5589,37.74,4.59337,2.44531,1384.0
13,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-GBEI-purity-tensile_strength-temperature-time__d67f1630,3600,5,initial_diameter|GBEI|purity|tensile_strength|temperature|time,11.59331,7.20798,0.9057,6.08181,4.80743,0.9,1.4213,50.94,5.66826,2.39880,2988.5
2,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__acdfa7d7,1200,5,IRI|purity|initial_diameter|tensile_strength|temperature|time,11.61053,7.15459,0.9245,5.86731,4.45140,1.0,1.4549,41.51,5.43447,2.39880,1349.8
10,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__df51ef9b,3600,5,IRI|purity|initial_diameter|tensile_strength|temperature|time,11.75658,7.11036,0.9057,6.02195,4.68702,1.0,1.6153,43.40,4.79332,2.39880,2508.9
0,annealing-schema070926_IRI-GBEI-comparison__3193d51a,120,5,IRI|initial_diameter|GBEI|purity|tensile_strength|temperature|time,13.75386,8.18006,0.8868,2.77424,2.13470,1.0,2.0451,24.53,2.88213,2.62277,642.3
14,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=purity-initial_diameter-tensile_strength-temperature-time__522cf548,3600,5,purity|initial_diameter|tensile_strength|temperature|time,14.22953,7.83399,0.9057,4.63692,3.44127,0.9,1.4549,64.15,6.78953,2.39880,2348.3
6,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=purity-initial_diameter-tensile_strength-temperature-time__6131c2ea,1200,5,purity|initial_diameter|tensile_strength|temperature|time,14.28377,7.91968,0.9057,4.07130,2.73358,0.9,1.4549,58.49,6.03196,2.39880,1345.6

In [16]:
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                       rmse                 mae           cov_0.9
                       mean       std      mean       std    mean       std
cfg_time_limit_a
120               13.753860       NaN  8.180060       NaN  0.8868       NaN
1200              11.591313  1.153391  7.138459  0.393220  0.9151  0.017452
3600              11.680613  1.082072  7.091933  0.337364  0.9057  0.000000

# 8. Load a winner

In [17]:
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-purity-tensile_strength-temperature-time__50c84a41

   alpha  empirical_coverage       gap
0   0.50            0.471698 -0.028302
1   0.80            0.792453 -0.007547
2   0.90            0.905660  0.005660
3   0.95            0.962264  0.012264

In [18]:
1

1