**Author**: Felipe Matheus
**Purpose**: Experiment launcher for the annealing **tensile strength (UTS)** surrogate.

Same architecture as `run_experiments.ipynb` (IACS): all pipeline logic lives
in `src/modeling/Experiments.py`, which is process-agnostic — the SAME
`ExperimentRunner` is reused; only the `ExperimentConfig` changes (target,
features, physical bounds). No new class needed.

Results layout: `models/annealing_tensile_strength/experiments/`
(`experiments_log.csv` + one folder per run).

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
TARGET = "tensile_strength_final"
ALL_FEATURES = ["purity", "initial_diameter", "tensile_strength", "temperature", "time"]
PROCESS = "annealing_uts"

SCHEMA_DATE = "110826"
FILE_NAME_SCHEMA_DATA = "schema_annealing_essays_{}.csv".format(SCHEMA_DATE)

TAG = f"annealing-schema{SCHEMA_DATE}"
GRID = {
    "time_limit_a": [900, 600],
    # "num_bag_folds_a": [10, 15, 20],
    # "features": [
    #     ("purity", "initial_diameter", "tensile_strength", "temperature", "time"),
    #     # ("initial_diameter", "tensile_strength", "temperature", "time"),
    # ],
}

# 2. Data (same preparation as annealing_uts.ipynb, run once)

In [3]:
df, df_val = proc.process_annealing_uts(
    features=ALL_FEATURES,
    target=TARGET,
    df_schema=pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA)),
)

In [4]:
# FILE_NAME = "dataset_annealing_tensile-strength.csv"

# df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
# df_float = proc.df_to_float(
#     df_raw, drop_cols=["DOI", "is_Cu"], ignore_columns=["material"]
# )
# df_labeled = feng.label_element(df_float).drop_duplicates()
# df_with_masks = feng.add_ratio_mask_column(
#     feng.add_ratio_mask_column(df_labeled, "grain_size"), "tensile_strength",
# )
# df = (
#     df_with_masks[ALL_FEATURES + [TARGET]]
#     .dropna(subset=[TARGET])
#     .reset_index(drop=True)
# )

# # No essay rows yet for UTS -> no is_essay column. The runr detects this
# # and applies uniform weights (weight_on_essay_rows must stay 1.0).
# print(f"Dataset: {df.shape}")

# # Validation set: none held-out yet. When UTS essays arrive, build df_val
# # from them (with the same columns) and pass df_val=df_val below.
# df_val = None
# df.head()

# 3. Base config

In [5]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    y_max=None,
    y_min=0.0,
    presets_a = "best_quality",
)
print(base.run_id)

annealing-schema110826__0ac26579

# 4. Single run (sanity check before any grid)

Run the base config alone first; then repeat 2-3x with `tag="uts-v1-rep2"`
etc. to measure run-to-run noise (the floor below which grid differences
mean nothing).

In [6]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-08-11 15:33:33,396 | INFO | src.modeling.Experiments | === Running annealing-schema110826__0ac26579 ===
2026-08-11 15:33:33,398 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       5.84 GB / 31.57 GB (18.5%)
Disk Space Avail:   727.32 GB / 932.08 GB (78.0%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__0ac26579\model_a"
Train Data Rows:    36
Train Data Columns: 6
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (331.2476863, 232.03, 253.84328, 22.1508)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5955.47 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.96s of the 119.95s of remaining time.
2026-08-11 15:33:37,113	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.27%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-23.0675	 = Validation score   (-root_mean_squared_error)
	0.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 106.47s of the 106.46s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.32%)
	-23.0675	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 101.57s of the 101.56s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-19.4273	 = Validation score   (-root_mean_squared_error)
	0.52s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 100.95s of the 100.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.71%)
	-18.3011	 = Validation score   (-root_mean_squared_error)
	17.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 80.00s of the 79.99s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-20.0194	 = Validation score   (-root_mean_squared_error)
	0.36s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 79.54s of the 79.53s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-24.1256	 = Validation score   (-root_mean_squared_error)
	7.26s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 69.01s of the 69.00s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.12%)
	-18.9931	 = Validation score   (-root_mean_squared_error)
	0.67s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 64.02s of the 64.01s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.3866	 = Validation score   (-root_mean_squared_error)
	7.68s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 52.62s of the 52.61s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.24%)
	-17.5895	 = Validation score   (-root_mean_squared_error)
	1.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 47.75s of the 47.74s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.56%)
	-18.5304	 = Validation score   (-root_mean_squared_error)
	8.41s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 35.49s of the 35.48s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-17.4734	 = Validation score   (-root_mean_squared_error)
	6.8s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 25.37s of the 25.37s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.64%)
	-22.9401	 = Validation score   (-root_mean_squared_error)
	1.64s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 19.52s of the 19.51s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-23.7012	 = Validation score   (-root_mean_squared_error)
	7.21s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 8.77s of the 8.76s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=8.49%)
	-19.2068	 = Validation score   (-root_mean_squared_error)
	7.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.96s of the -3.90s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 0.5, 'NeuralNetTorch_r79_BAG_L1': 0.5}
	-15.8692	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 123.95s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 179.4 rows/s (8 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__0ac26579\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       6.15 GB / 31.57 GB (19.5%)
Disk Space Avail:   716.57 GB / 932.08 GB (76.9%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__0ac26579\model_b"
Train Data Rows:    36
Train Data Columns: 5
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (8.324371740435007, -13.815510557964274, -3.14243, 8.82461)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6308.28 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.95s of the 59.95s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.25%)
	-9.1437	 = Validation score   (-root_mean_squared_error)
	0.99s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 55.72s of the 55.72s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
	-9.1437	 = Validation score   (-root_mean_squared_error)
	0.98s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 50.97s of the 50.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.5046	 = Validation score   (-root_mean_squared_error)
	0.52s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 50.34s of the 50.33s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.30%)
	-8.9033	 = Validation score   (-root_mean_squared_error)
	1.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 45.49s of the 45.48s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.3888	 = Validation score   (-root_mean_squared_error)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 44.91s of the 44.91s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-9.2185	 = Validation score   (-root_mean_squared_error)
	7.08s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 34.02s of the 34.02s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.10%)
	-9.1286	 = Validation score   (-root_mean_squared_error)
	0.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 28.84s of the 28.83s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-8.6024	 = Validation score   (-root_mean_squared_error)
	6.63s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 18.61s of the 18.61s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.41%)
	-8.7594	 = Validation score   (-root_mean_squared_error)
	0.85s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.95s of the 13.53s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/5.3 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.95, 'LightGBMLarge_BAG_L1': 0.05}
	-8.6019	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime

{'rmse': 15.869155435262606,
 'mae': 9.792584643359376,
 'mape': 3.6048580428243397,
 'r2': 0.4720861193226151}

# 5 Validation set

TBD

In [7]:
df_val

,purity,initial_diameter,tensile_strength,temperature,time,tensile_strength_final
35,99.7637,2.0,349.58,723.0,60.0,239.570748
13,99.9000,1.2,397.09,573.0,60.0,262.400000
26,99.9740,0.8,347.70,823.0,0.5,301.290000
30,99.9740,0.8,347.70,873.0,20.0,242.340000
16,99.9000,1.2,397.09,523.0,60.0,260.260000
31,99.9740,0.8,347.70,873.0,30.0,239.190000
21,99.9800,1.2,335.21,523.0,30.0,245.680000
12,99.9000,1.2,397.09,573.0,30.0,261.320000
8,99.9000,1.2,431.58,623.0,30.0,239.410000
17,99.9000,1.2,397.09,523.0,90.0,259.140000

In [8]:
result["artifacts"]["validation_metrics"]

{'rmse': 13.076932872853806,
 'mae': 8.490315251275883,
 'mape': 3.1931300976824764,
 'r2': 0.4755122361089602,
 'coverage': {0.5: 0.7, 0.8: 0.9, 0.9: 0.9, 0.95: 1.0}}

In [9]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [10]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [11]:
result

{'cfg': ExperimentConfig(process='annealing_uts', tag='annealing-schema110826', base_tag=None, target='tensile_strength_final', features=('purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=0.0, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': Path('../../models/annealing_uts/experiments/annealing-schema110826/annealing-schema110826__0ac26579'),
 'artifacts': {'config': {'process': 'annealing_uts',
   'tag': 'annealing-schema110826',
   'base_tag': None,
   'target': 'tensile_strength_final',
   'features': ['purity',
    'initial_diameter',
    'tensile_strength',
    'temperature',
    'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': 0.0,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['purity',
   'initial_diameter',
   'tensile_strength',
   'temperature',
   'time'],
  'target': 'tensile_strength_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1',
   'NeuralNetTorch_BAG_L1',
   'LightGBMLarge_BAG_L1',
   'CatBoost_r177_BAG_L1',
   'NeuralNetTorch_r79_BAG_L1',
   'LightGBM_r131_BAG_L1',
   'NeuralNetFastAI_r191_BAG_L1',
   'CatBoost_r9_BAG_L1'],
  'weights': array([0.00000000e+00, 0.00000000e+00, 5.34919172e-08, 1.97950631e-07,
         0.00000000e+00, 0.00000000e+00, 2.53696745e-07, 0.00000000e+00,
         4.99999623e-01, 0.00000000e+00, 4.99999872e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 1.6904743119994237e-05,
  'variance_floor': 4.906581343258993,
  'recalibration_c': 2.403763770015332,
  'ood_ref': {'features': ['purity',
    'initial_diameter',
    'tensile_strength',
    'temperature',
    'time'],
   'mean': array([ 99.93114722,   1.2539537 , 380.78097927, 610.5       ,
           49.73611111]),
   'cov_inv': array([[ 2.98095456e+02,  1.13650187e+01,  2.30999471e-01,
            1.64665452e-02,  7.00588778e-02],
          [ 1.13650187e+01,  6.85966351e+00,  3.01056476e-03,
            5.58584192e-03,  1.13161640e-02],
          [ 2.30999471e-01,  3.01056476e-03,  1.00692084e-03,
            1.09910205e-04, -5.33781376e-05],
          [ 1.64665452e-02,  5.58584192e-03,  1.09910205e-04,
            1.40565008e-04,  1.80027570e-04],
          [ 7.00588778e-02,  1.13161640e-02, -5.33781376e-05,
            1.80027570e-04,  1.89585323e-03]]),
   'd_ref': 2.791337363116231,
   'ranges': {'purity': (99.7637, 99.98),
    'initial_diameter': (0.8, 2.182333333),
    'tensile_strength': (335.21, 431.58),
    'temperature': (523.0, 873.0),
    'time': (0.5, 90.0)}},
  'y_max': None,
  'y_min': 0.0,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.305556 -0.194444
  1   0.80            0.611111 -0.188889
  2   0.90            0.722222 -0.177778
  3   0.95            0.805556 -0.144444,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.722222  0.222222
  1   0.80            0.861111  0.061111
  2   0.90            0.916667  0.016667
  3   0.95            0.972222  0.022222,
  'aleatoric_diagnostics': {'n_total': 36,
   'n_truncated': 14,
   'pct_truncated': 38.888888888888886,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 4123.145987647536,
   'r_tilde_sq_mean': 210.17149141184586,
   'r_tilde_sq_median': 5.402886509429001},
  'metrics': {'rmse': 15.869155435262606,
   'mae': 9.792584643359376,
   'mape': 3.6048580428243397,
   'r2': 0.4720861193226151},
  'validation_metrics': {'rmse': 13.076932872853806,
   'mae': 8.490315251275883,
   'mape': 3.1931300976824764,
   'r2': 0.4755122361089602,
   'coverage': {0.5: 0.7, 0.8: 0.9, 0.9: 0.9, 0.95: 1.0}},
  'dataset_hash': '57606bab'},
 'log_row': {'run_id': 'annealing-schema110826__0ac26579',
  'timestamp': '2026-08-11T15:36:30',
  'elapsed_s': 176.7,
  'n_rows': 36,
  'dataset_hash': '57606bab',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_uts\\experiments\\annealing-schema110826\\annealing-schema110826__0ac26579',
  'cfg_process': 'annealing_uts',
  'cfg_tag': 'annealing-schema110826',
  'cfg_base_tag': None,
  'cfg_target': 'tensile_strength_final',
  'cfg_features': 'purity|initial_diameter|tensile_strength|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'medium_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': 0.0,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'cfg_group_col': None,
  'rmse': 15.86916,
  'mae': 9.79258,
  'mape': 3.60486,
  'r2': 0.47209,
  'cov_0.5': 0.7222,
  'cov_0.8': 0.8611,
  'cov_0.9': 0.9167,
  'cov_0.95': 0.9722,
  'c_opt': 2.4038,
  'pct_truncated_aleat': 38.89,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 5.46213,
  'mean_sigma_aleat': 2.21508,
  'n_val': 10,
  'val_rmse': 13.07693,
  'val_mae': 8.49032,
  'val_mape': 3.19313,
  'val_r2': 0.47551,
  'val_cov_0.5': 0.7,
  'val_cov_0.8': 0.9,
  'val_cov_0.9': 0.9,
  'val_cov_0.95': 1.0},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1f482051b50>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1f48935f2d0>}

# 6. Grid

In [12]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-08-11 15:36:32,116 | INFO | src.modeling.Experiments | Grid: 2 runs over ['time_limit_a']
2026-08-11 15:36:32,118 | INFO | src.modeling.Experiments | === Running annealing-schema110826__time_limit_a=900__a30f4985 ===
2026-08-11 15:36:32,119 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       5.74 GB / 31.57 GB (18.2%)
Disk Space Avail:   716.56 GB / 932.08 GB (76.9%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=900__a30f4985\model_a"
Train Data Rows:    36
Train Data Columns: 6
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (331.2476863, 232.03, 253.84328, 22.1508)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6085.67 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 899.96s of the 899.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.26%)
	-23.0675	 = Validation score   (-root_mean_squared_error)
	0.96s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 895.26s of the 895.25s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.29%)
	-23.0675	 = Validation score   (-root_mean_squared_error)
	0.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 890.31s of the 890.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-19.4273	 = Validation score   (-root_mean_squared_error)
	0.54s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 889.66s of the 889.65s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.68%)
	-18.3011	 = Validation score   (-root_mean_squared_error)
	19.71s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 866.56s of the 866.55s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-20.0194	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 866.14s of the 866.13s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-24.1256	 = Validation score   (-root_mean_squared_error)
	7.04s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 855.62s of the 855.61s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.12%)
	-18.9931	 = Validation score   (-root_mean_squared_error)
	0.81s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 850.50s of the 850.49s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.3866	 = Validation score   (-root_mean_squared_error)
	7.78s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 838.87s of the 838.85s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.36%)
	-17.5895	 = Validation score   (-root_mean_squared_error)
	1.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 833.87s of the 833.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.11%)
	-18.5304	 = Validation score   (-root_mean_squared_error)
	8.94s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 821.05s of the 821.03s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-17.4734	 = Validation score   (-root_mean_squared_error)
	6.82s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 810.76s of the 810.75s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.62%)
	-22.9401	 = Validation score   (-root_mean_squared_error)
	1.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 804.49s of the 804.48s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-23.7012	 = Validation score   (-root_mean_squared_error)
	7.04s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 793.94s of the 793.93s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=9.01%)
	-19.2068	 = Validation score   (-root_mean_squared_error)
	9.0s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 780.56s of the 780.55s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-23.0675	 = Validation score   (-root_mean_squared_error)
	0.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 776.15s of the 776.13s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-17.5493	 = Validation score   (-root_mean_squared_error)
	7.54s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 764.59s of the 764.58s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.52%)
	-18.7807	 = Validation score   (-root_mean_squared_error)
	0.81s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 759.90s of the 759.89s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-20.5101	 = Validation score   (-root_mean_squared_error)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 759.26s of the 759.25s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.83%)
	-18.2375	 = Validation score   (-root_mean_squared_error)
	1.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 753.48s of the 753.47s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-24.1256	 = Validation score   (-root_mean_squared_error)
	7.15s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 742.72s of the 742.71s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=9.07%)
	-18.746	 = Validation score   (-root_mean_squared_error)
	9.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 728.81s of the 728.79s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-19.3099	 = Validation score   (-root_mean_squared_error)
	0.59s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 728.14s of the 728.12s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.07%)
	-21.9899	 = Validation score   (-root_mean_squared_error)
	1.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 723.74s of the 723.73s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-22.8749	 = Validation score   (-root_mean_squared_error)
	7.2s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 712.67s of the 712.65s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.11%)
	-18.9089	 = Validation score   (-root_mean_squared_error)
	0.66s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 707.97s of the 707.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.9968	 = Validation score   (-root_mean_squared_error)
	7.39s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 696.74s of the 696.73s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.97%)
	-23.0675	 = Validation score   (-root_mean_squared_error)
	0.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 691.74s of the 691.73s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.451	 = Validation score   (-root_mean_squared_error)
	7.12s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 680.86s of the 680.84s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=8.79%)
	-19.3486	 = Validation score   (-root_mean_squared_error)
	3.25s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 673.45s of the 673.44s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-23.7012	 = Validation score   (-root_mean_squared_error)
	13.08s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 652.96s of the 652.95s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.21%)
	-17.965	 = Validation score   (-root_mean_squared_error)
	0.82s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 646.31s of the 646.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-21.4315	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 645.69s of the 645.68s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.08%)
	-18.1611	 = Validation score   (-root_mean_squared_error)
	1.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 639.87s of the 639.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-23.2239	 = Validation score   (-root_mean_squared_error)
	7.78s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 627.26s of the 627.24s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-18.858	 = Validation score   (-root_mean_squared_error)
	8.1s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 614.23s of the 614.22s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=2.09%)
	-22.8823	 = Validation score   (-root_mean_squared_error)
	2.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 607.17s of the 607.15s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-22.8979	 = Validation score   (-root_mean_squared_error)
	22.46s	 = Training   runtime
	0.36s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 575.50s of the 575.49s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=8.71%)
	-18.8605	 = Validation score   (-root_mean_squared_error)
	4.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r156_BAG_L1 ... Training model for up to 561.36s of the 561.35s of remaining time.

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema110826__0ac26579,2026-08-11T15:36:30,176.7,36,57606bab,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__0ac26579,annealing_uts,annealing-schema110826,NaN,tensile_strength_final,...,2.21508,10,13.07693,8.49032,3.19313,0.47551,0.7,0.9,0.9,1.0
1,annealing-schema110826__time_limit_a=900__a30f4985,2026-08-11T15:53:18,1006.0,36,57606bab,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=900__a30f4985,annealing_uts,annealing-schema110826__time_limit_a=900,annealing-schema110826,tensile_strength_final,...,2.21508,10,11.21791,7.49340,2.82315,0.61404,0.4,0.7,0.9,0.9
2,annealing-schema110826__time_limit_a=600__dce22b15,2026-08-11T16:04:57,699.1,36,57606bab,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=600__dce22b15,annealing_uts,annealing-schema110826__time_limit_a=600,annealing-schema110826,tensile_strength_final,...,2.21508,10,13.07693,8.49032,3.19313,0.47551,0.7,0.9,0.9,1.0

# 7. Inspect results

In [13]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_num_bag_folds_a", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9",
    "c_opt", "pct_truncated_aleat", "mean_sigma_epist", "mean_sigma_aleat",
    "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_num_bag_folds_a,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
1,annealing-schema110826__time_limit_a=900__a30f4985,900,5,purity|initial_diameter|tensile_strength|temperature|time,15.78935,9.70847,0.8889,11.21791,7.49340,0.9,1.4549,44.44,6.01499,2.21508,1006.0
0,annealing-schema110826__0ac26579,120,5,purity|initial_diameter|tensile_strength|temperature|time,15.86916,9.79258,0.9167,13.07693,8.49032,0.9,2.4038,38.89,5.46213,2.21508,176.7
2,annealing-schema110826__time_limit_a=600__dce22b15,600,5,purity|initial_diameter|tensile_strength|temperature|time,15.86916,9.79258,0.9167,13.07693,8.49032,0.9,2.4038,38.89,5.46213,2.21508,699.1

In [14]:
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                      rmse          mae     cov_0.9
                      mean std     mean std    mean std
cfg_time_limit_a
120               15.86916 NaN  9.79258 NaN  0.9167 NaN
600               15.86916 NaN  9.79258 NaN  0.9167 NaN
900               15.78935 NaN  9.70847 NaN  0.8889 NaN

# 8. Load a winner

In [15]:
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema110826__time_limit_a=900__a30f4985

   alpha  empirical_coverage       gap
0   0.50            0.555556  0.055556
1   0.80            0.805556  0.005556
2   0.90            0.888889 -0.011111
3   0.95            0.888889 -0.061111

(raylet) The node with node id: daf9340905b585755bc1c4639f6fa8281d5eef8bd0d8e045c559877d and address: 127.0.0.1 and node name: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, etc.)
	(2) raylet has lagging heartbeats due to slow network or busy workload.

In [16]:
1

1