**Author**: Felipe Matheus
**Start Date**: 12/06/2026
**End Date**: 24/06/2026
**Purpose**: Experiment launcher ("control panel") for the annealing_iacs surrogate.

This notebook does NOT contain pipeline logic. Data preparation lives in
`src/pipelines/AnnealingPipeline.py` (composition resolution + IRI/GBEI via
`ChemicalFeatureEngineering`), and the modelling logic (Model A -> OOF ->
NNLS -> Model B -> calibration -> metrics -> persistence) lives in
`src/modeling/Experiments.py`. Here you only:

1. Point the pipeline at a schema date and let it build `df` / `df_val`.
2. Define a base `ExperimentConfig`.
3. Define the grid of variations you want to sweep.
4. Run and inspect the central `experiments_log.csv`.

Kept in step with `notebooks/modeling/annealing_iacs.ipynb`: same schema date,
same feature list (IRI included), same physical ceiling.

Results layout on disk:
```
models/annealing_iacs/experiments/
    experiments_log.csv          <- 1 row per run (the "results spreadsheet")
    <tag>__<hash>/               <- 1 folder per run
        config.yaml
        model_a/   model_b/
        artifacts.pkl
        leaderboard_autogluon.csv
```

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner
from src.pipelines.AnnealingPipeline import AnnealingDataPipeline

from config.Variables import Variables
from config.bags_compositions import ALL_SAMPLES
from config.elements_coefficients import RESISTIVITY_FACTORS, ENRICHMENT_FACTORS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# ---- Surrogate identity ----
TARGET = "iacs_final"
# IRI is composition-derived (ChemicalFeatureEngineering), not a raw column.
ALL_FEATURES = ["GBEI", "measured_initial_diameter", "IRI", "purity", "iacs", "temperature", "time"]
PROCESS = "annealing_iacs"

# ---- Schemas (kept in step with notebooks/modeling/annealing_iacs.ipynb) ----
ANNEALING_SCHEMA_DATE = "051026"
SN_SCHEMA_DATE = "051026"
FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{ANNEALING_SCHEMA_DATE}.csv"
FILE_NAME_SN_COMPOSITION = f"serial-number-encoding_{SN_SCHEMA_DATE}.csv"

# Rows whose STARTING iacs is below this are dropped (pipeline knob).
THRESHOLD_INITIAL = 85.0

ID = "IRI-GBEI-comparison"
TAG = f"annealing-schema{ANNEALING_SCHEMA_DATE}_{ID}"

# ---- Physical constraints (inference-time truncation) ----
Y_MAX = 105.0   # physical ceiling for %IACS
Y_MIN = None

GRID = {
    "time_limit_a": [1200, 3600],
    # "num_bag_folds_a": [10, 20],
    "features": [
        ("GBEI", "measured_initial_diameter", "IRI", "purity", "iacs", "temperature", "time"),
        ("GBEI", "measured_initial_diameter", "purity", "iacs", "temperature", "time"),# pre-IRI baseline
        ("GBEI", "measured_initial_diameter", "IRI", "iacs", "temperature", "time"),
        ("GBEI", "IRI", "purity", "iacs", "temperature", "time"),
        ("measured_initial_diameter", "IRI", "purity", "iacs", "temperature", "time"),
        ("measured_initial_diameter", "purity", "iacs", "temperature", "time"),# pre-IRI baseline
        ("measured_initial_diameter", "IRI", "iacs", "temperature", "time"),
        ("IRI", "purity", "iacs", "temperature", "time"),
    ],
    # NOTE: "weight_on_essay_rows" is no longer sweepable — the pipeline output
    # carries no `is_essay` column, so anything but 1.0 makes the runner raise.
}

# Raw columns the pipeline keeps before feature engineering. `material_reference`
# is never a model feature, but ChemicalFeatureEngineering resolves it into the
# composition that IRI and GBEI are computed from, so it must survive here.
ANNEALING_FEATURES = [
    "experiment_id",
    "material_reference",
    "purity",
    "measured_initial_diameter",
    "temperature",
    "time",
    "iacs",
    "tensile_strength",
    "elongation",
    "iacs_final",
    "tensile_strength_final",
    "elongation_final",
]

# 2. Data

`AnnealingDataPipeline` replaces the old `proc.process_annealing_iacs` call
(that method was moved out of `Processing`). It performs the same preparation
as `notebooks/modeling/annealing_iacs.ipynb`, run once here.

The external Chimie ParisTech validation file is NOT used any more: it has no
`material_reference` column, so IRI cannot be computed for it and its rows can
no longer be scored by an IRI-fed surrogate. Add that column to the file to
bring it back.

In [3]:
# One pipeline object owns the whole preparation: drop all-NaN rows, select
# ANNEALING_FEATURES, resolve every material_reference to a composition, and
# attach IRI + GBEI. `pipe.df_iri_gbei` is the enriched frame the getters slice.
pipe = AnnealingDataPipeline(
    df_annealing_schema_raw=pd.read_csv(
        os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA)
    ),
    annealing_features=ANNEALING_FEATURES,
    df_sn=pd.read_csv(
        os.path.join(varv.PATHS.data_structured, FILE_NAME_SN_COMPOSITION)
    ),
    all_samples=ALL_SAMPLES,
    resistivity_factors=RESISTIVITY_FACTORS,
    enrichment_factors=ENRICHMENT_FACTORS,
)

df, df_val = pipe.get_iacs_df_df_val(
    features_iacs=ALL_FEATURES,
    target_iacs=TARGET,
    threshold_initial=THRESHOLD_INITIAL,
)

print(f"train: {df.shape} | val: {df_val.shape}")
df.head()

train: (59, 8) | val: (11, 8)

,GBEI,initial_diameter,IRI,purity,iacs,temperature,time,iacs_final
0,0.489800,1.900000,1.300000,99.9,88.260,623,30.0,88.350
1,0.489800,1.900000,1.300000,99.9,88.260,623,60.0,88.655
2,0.489800,1.900000,1.300000,99.9,88.260,623,90.0,88.800
3,0.001038,2.160000,0.195105,99.9,99.825,573,30.0,102.340
4,0.001038,2.182333,0.195105,99.9,99.390,573,30.0,102.230

In [4]:
# Sanity check BEFORE training: an unresolved material_reference yields NaN
# IRI/GBEI, and the getter's .dropna() then removes those rows silently. This
# report is the fastest way to see a typo'd reference or a blend whose bag
# weights did not sum to 1.
report = pipe.chfe.resolution_report(pipe.df_feat)
print(f"unresolved references: {(~report['resolved']).sum()}")
report

unresolved references: 0

,n_rows,source,resolved,raw weight sum,recipe,problem
material_reference,,,,,,
Cu-ETP,12,direct sample,True,NaN,,
Cu-T2,9,direct sample,True,NaN,,
SN015,9,blend,True,1.0,"1B_sac2=0.4047, 1B_sac3=0.4047, 1B_sac5=0.1906",
SN014,6,blend,True,1.0,1B_sac2=1,
SN021,6,blend,True,1.0,"1A_sac1=0.02, 1A_sac2=0.02, 1B_sac2=0.02, 1B_s...",
SN019,5,blend,True,1.0,"1A_sac1=0.3, 2N_sac2=0.6952, echantillon_2N=0....",
C14500,3,direct sample,True,NaN,,
SN027,3,blend,True,1.0,"1B_sac3=0.05, 1B_sac4=0.05, 1B_sac5=0.05, 1B_s...",
SN025,2,blend,True,1.0,"1B_sac2=0.1, 1B_sac3=0.1, 1B_sac5=0.1, echanti...",
SN016,2,blend,True,1.0,"1B_sac2=0.2305, 1B_sac3=0.2305, 1B_sac5=0.2305...",
SN024,1,blend,True,1.0,"1B_sac6=0.1, echantillon_1=0.225, echantillon_...",
SN029,1,blend,True,1.0,"1A_sac1=0.10273, 1A_sac2=0.10273, 1B_sac1=0.10...",

In [5]:
# The `df[df.iacs > 90]` filter that used to live here is now the pipeline's
# `threshold_initial` knob, applied by the getter in section 2.
df[ALL_FEATURES + [TARGET]].describe().T

,count,mean,std,min,25%,50%,75%,max
GBEI,59.0,0.101954,0.142240,0.001038,0.002674,0.011525,0.226272,0.4898
initial_diameter,59.0,1.535808,0.533763,0.800000,1.200000,1.200000,2.171167,2.2000
IRI,59.0,0.419873,0.245165,0.195105,0.233275,0.419799,0.467823,1.3000
purity,59.0,99.869639,0.101733,99.667500,99.763700,99.900000,99.964900,99.9800
iacs,59.0,97.678305,3.239998,88.260000,96.967500,97.565000,99.520000,102.7000
temperature,59.0,640.033898,101.769341,523.000000,573.000000,623.000000,723.000000,923.0000
time,59.0,50.127119,24.940722,0.500000,30.000000,60.000000,60.000000,105.0000
iacs_final,59.0,100.449011,3.329916,88.350000,99.392500,100.625000,102.265000,104.8650

# 3. Base config

In [6]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a="best_quality",
    presets_b="best_quality",
    y_max=Y_MAX,
    y_min=Y_MIN,
    # `weight_on_essay_rows` stays at its 1.0 default: the pipeline output has
    # no `is_essay` column, and any other value would make the runner raise.
    # Same reason `use_shared_folds` stays False (fold stratification needs it).
)
print(base.run_id)

annealing-schema070926_IRI-GBEI-comparison__3326e693

# 4. Single run (sanity check before any grid)

Always run the base config alone first. Then run it 2-3 more times with
`tag="annealing-v1-rep2"` etc. to measure run-to-run noise: AutoGluon under a
time budget is NOT deterministic, and at n~90 this noise is the floor below
which grid differences mean nothing.

In [7]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-09-09 17:52:16,386 | INFO | src.modeling.Experiments | === Running annealing-schema070926_IRI-GBEI-comparison__3326e693 ===
2026-09-09 17:52:16,388 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)

=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       9.16 GB / 31.57 GB (29.0%)
Disk Space Avail:   697.02 GB / 932.08 GB (74.8%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3326e693\model_a"
Train Data Rows:    59
Train Data Columns: 8
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (104.865, 88.35, 100.44901, 3.32992)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9350.32 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.96s of the 119.95s of remaining time.
2026-09-09 17:52:23,906	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.18%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-2.4921	 = Validation score   (-root_mean_squared_error)
	3.09s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 87.76s of the 87.75s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
	-2.4624	 = Validation score   (-root_mean_squared_error)
	3.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 77.41s of the 77.40s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0443	 = Validation score   (-root_mean_squared_error)
	0.8s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 76.45s of the 76.45s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=5.70%)
	-1.0581	 = Validation score   (-root_mean_squared_error)
	7.44s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 58.86s of the 58.85s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.027	 = Validation score   (-root_mean_squared_error)
	0.72s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 57.95s of the 57.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1533	 = Validation score   (-root_mean_squared_error)
	23.8s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 24.07s of the 24.06s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.45%)
	-1.1709	 = Validation score   (-root_mean_squared_error)
	2.9s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 7.43s of the 7.42s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.96s of the -15.83s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/7.0 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 0.261, 'ExtraTreesMSE_BAG_L1': 0.261, 'NeuralNetFastAI_BAG_L1': 0.261, 'RandomForestMSE_BAG_L1': 0.217}
	-0.9935	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 135.89s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 86.3 rows/s (12 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3326e693\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       7.22 GB / 31.57 GB (22.9%)
Disk Space Avail:   697.01 GB / 932.08 GB (74.8%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3326e693\model_b"
Train Data Rows:    59
Train Data Columns: 7
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1.7788973435613997, -13.815510557964274, -3.72193, 5.59476)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7401.69 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.96s of the 59.95s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.22%)
	-5.6047	 = Validation score   (-root_mean_squared_error)
	9.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 43.36s of the 43.35s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.20%)
	-5.6067	 = Validation score   (-root_mean_squared_error)
	4.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 31.97s of the 31.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-5.8552	 = Validation score   (-root_mean_squared_error)
	0.66s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 31.16s of the 31.15s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=4.61%)
	-5.2393	 = Validation score   (-root_mean_squared_error)
	10.47s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 13.40s of the 13.40s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-5.8038	 = Validation score   (-root_mean_squared_error)
	0.68s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 12.56s of the 12.55s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-5.1136	 = Validation score   (-root_mean_squared_error)
	12.61s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.96s of the -7.23s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/10.0 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.714, 'CatBoost_BAG_L1': 0.286}
	-5.0892	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 67.29s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 232.3 rows/s (12 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3326e693\model_b")
2026-09-09 17:55:48,350 | INFO | src.modeling.Modeling | OOD inflation applied to 1/11 rows (max m=1.25).
2026-09-09 17:55:48,698 | INFO | src.modeling.Experiments | Validation (n=11): rmse=0.5691 mae=0.4279
2026-09-09 17:55:48,741 | INFO | src.modeling.Experiments | Done annealing-schema070926_IRI-GBEI-comparison__3326e693 in 212.3s

{'rmse': 0.9934721964576684,
 'mae': 0.7859976897543693,
 'mape': 0.7895138307690909,
 'r2': 0.9094540673124589}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

**Caveat — where this `df_val` comes from.** The pipeline getter builds it as a
random 20 % sample *of `df` itself* when no `df_val` is passed, so those rows
are inside the training data and the val metrics are IN-SAMPLE and optimistic.
Pass a genuinely held-out frame to the getter to make them honest — it must
carry the same engineered columns (`IRI` / `GBEI` included), which in practice
means running it through `pipe` too.

In [8]:
df_val

,GBEI,initial_diameter,IRI,purity,iacs,temperature,time,iacs_final
0,0.489800,1.900000,1.300000,99.9000,88.260,623,30.0,88.350000
5,0.001038,2.182333,0.195105,99.9000,99.390,588,30.0,101.346667
34,0.011525,0.800000,0.419799,99.9740,97.565,573,60.0,99.110000
13,0.002674,1.200000,0.233275,99.9000,97.710,573,90.0,101.220000
45,0.264027,2.200000,0.525991,99.7036,94.840,723,60.0,100.140000
53,0.207493,2.200000,0.467823,99.7637,97.100,673,60.0,100.065000
57,0.268018,1.000000,0.542737,99.6985,94.400,623,30.0,97.580000
25,0.006830,1.200000,0.402535,99.9800,102.700,573,60.0,100.785000
47,0.264027,2.200000,0.525991,99.7036,94.840,673,60.0,100.530000
12,0.002674,1.200000,0.233275,99.9000,97.710,573,60.0,101.350000
49,0.264027,2.200000,0.525991,99.7036,94.840,773,60.0,100.270000

In [9]:
result["artifacts"]["validation_metrics"]

{'rmse': 0.5690633061985272,
 'mae': 0.4278688525855911,
 'mape': 0.4410362999092956,
 'r2': 0.974683505873121,
 'coverage': {0.5: 0.7272727272727273, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}}

In [10]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [11]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [12]:
result

{'cfg': ExperimentConfig(process='annealing_iacs', tag='annealing-schema070926_IRI-GBEI-comparison', base_tag=None, target='iacs_final', features=('GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='best_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=105.0, y_min=None, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': Path('../../models/annealing_iacs/experiments/annealing-schema070926_IRI-GBEI-comparison/annealing-schema070926_IRI-GBEI-comparison__3326e693'),
 'artifacts': {'config': {'process': 'annealing_iacs',
   'tag': 'annealing-schema070926_IRI-GBEI-comparison',
   'base_tag': None,
   'target': 'iacs_final',
   'features': ['GBEI',
    'initial_diameter',
    'IRI',
    'purity',
    'iacs',
    'temperature',
    'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'best_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': 105.0,
   'y_min': None,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['GBEI',
   'initial_diameter',
   'IRI',
   'purity',
   'iacs',
   'temperature',
   'time'],
  'target': 'iacs_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1'],
  'weights': array([5.46245245e-08, 0.00000000e+00, 2.17390991e-01, 2.60868894e-01,
         2.60870045e-01, 2.60869296e-01, 7.20132851e-07]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 3.8817463519080775e-06,
  'variance_floor': 0.11088339284426817,
  'recalibration_c': 2.045088535363133,
  'ood_ref': {'features': ['GBEI',
    'initial_diameter',
    'IRI',
    'purity',
    'iacs',
    'temperature',
    'time'],
   'mean': array([1.01953929e-01, 1.53580791e+00, 4.19873272e-01, 9.98696390e+01,
          9.76783051e+01, 6.40033898e+02, 5.01271186e+01]),
   'cov_inv': array([[ 3.79224161e+02, -8.31405185e+00, -1.30495047e+02,
            1.95784065e+02,  3.12039318e+00,  1.55835304e-02,
           -5.21834240e-02],
          [-8.31405185e+00,  4.97294476e+00,  7.52668137e-01,
            6.87936336e+00, -9.83125149e-02,  1.13783750e-04,
            4.30279476e-03],
          [-1.30495047e+02,  7.52668137e-01,  8.91978330e+01,
           -9.04175580e+01,  1.70206223e+00, -1.10292823e-02,
           -2.28586889e-02],
          [ 1.95784065e+02,  6.87936336e+00, -9.04175580e+01,
            2.45988386e+02, -8.77161101e-01,  4.09193464e-02,
            7.46755620e-02],
          [ 3.12039318e+00, -9.83125149e-02,  1.70206223e+00,
           -8.77161101e-01,  3.30205928e-01,  9.64596743e-04,
           -2.00675321e-03],
          [ 1.55835304e-02,  1.13783750e-04, -1.10292823e-02,
            4.09193464e-02,  9.64596743e-04,  1.33002432e-04,
            1.57343442e-04],
          [-5.21834240e-02,  4.30279476e-03, -2.28586889e-02,
            7.46755620e-02, -2.00675321e-03,  1.57343442e-04,
            1.85160553e-03]]),
   'd_ref': 3.3389149186165032,
   'ranges': {'GBEI': (0.0010379999999999999, 0.4898),
    'initial_diameter': (0.8, 2.2),
    'IRI': (0.195105, 1.3),
    'purity': (99.6675, 99.98),
    'iacs': (88.26, 102.7),
    'temperature': (523.0, 923.0),
    'time': (0.5, 105.0)}},
  'y_max': 105.0,
  'y_min': None,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.237288 -0.262712
  1   0.80            0.491525 -0.308475
  2   0.90            0.644068 -0.255932
  3   0.95            0.728814 -0.221186,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.576271  0.076271
  1   0.80            0.830508  0.030508
  2   0.90            0.915254  0.015254
  3   0.95            0.932203 -0.017797,
  'aleatoric_diagnostics': {'n_total': 59,
   'n_truncated': 13,
   'pct_truncated': 22.033898305084747,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 5.923320427818168,
   'r_tilde_sq_mean': 0.8458018289905002,
   'r_tilde_sq_median': 0.28155745286668465},
  'metrics': {'rmse': 0.9934721964576684,
   'mae': 0.7859976897543693,
   'mape': 0.7895138307690909,
   'r2': 0.9094540673124589},
  'validation_metrics': {'rmse': 0.5690633061985272,
   'mae': 0.4278688525855911,
   'mape': 0.4410362999092956,
   'r2': 0.974683505873121,
   'coverage': {0.5: 0.7272727272727273, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}},
  'dataset_hash': '405e27af'},
 'log_row': {'run_id': 'annealing-schema070926_IRI-GBEI-comparison__3326e693',
  'timestamp': '2026-09-09T17:55:48',
  'elapsed_s': 212.3,
  'n_rows': 59,
  'dataset_hash': '405e27af',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_iacs\\experiments\\annealing-schema070926_IRI-GBEI-comparison\\annealing-schema070926_IRI-GBEI-comparison__3326e693',
  'cfg_process': 'annealing_iacs',
  'cfg_tag': 'annealing-schema070926_IRI-GBEI-comparison',
  'cfg_base_tag': None,
  'cfg_target': 'iacs_final',
  'cfg_features': 'GBEI|initial_diameter|IRI|purity|iacs|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'best_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': 105.0,
  'cfg_y_min': None,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'cfg_group_col': None,
  'rmse': 0.99347,
  'mae': 0.786,
  'mape': 0.78951,
  'r2': 0.90945,
  'cov_0.5': 0.5763,
  'cov_0.8': 0.8305,
  'cov_0.9': 0.9153,
  'cov_0.95': 0.9322,
  'c_opt': 2.0451,
  'pct_truncated_aleat': 22.03,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 0.34759,
  'mean_sigma_aleat': 0.34159,
  'n_val': 11,
  'val_rmse': 0.56906,
  'val_mae': 0.42787,
  'val_mape': 0.44104,
  'val_r2': 0.97468,
  'val_cov_0.5': 0.7273,
  'val_cov_0.8': 1.0,
  'val_cov_0.9': 1.0,
  'val_cov_0.95': 1.0},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1c976022910>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1c97f22e850>}

# 6. Grid

Keys are `ExperimentConfig` field names; values are lists of variants.
`features` variants must be tuples. Already-completed runs are skipped
(`force=True` to redo).

In [13]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-09-09 17:55:51,429 | INFO | src.modeling.Experiments | Grid: 16 runs over ['time_limit_a', 'features']
2026-09-09 17:55:51,432 | INFO | src.modeling.Experiments | === Running annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0 ===
2026-09-09 17:55:51,432 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       12.25 GB / 31.57 GB (38.8%)
Disk Space Avail:   697.01 GB / 932.08 GB (74.8%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 1200s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0\model_a"
Train Data Rows:    59
Train Data Columns: 8
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (104.865, 88.35, 100.44901, 3.32992)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12463.38 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['GBEI', 'initial_diameter', 'IRI', 'purity', 'iacs', ...]
		('int', [])   : 1 | ['temperature']
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1199.92s of the 1199.91s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-2.4921	 = Validation score   (-root_mean_squared_error)
	3.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1190.88s of the 1190.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-2.4624	 = Validation score   (-root_mean_squared_error)
	3.95s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 1181.83s of the 1181.81s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0443	 = Validation score   (-root_mean_squared_error)
	0.58s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1181.11s of the 1181.09s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.13%)
	-1.0581	 = Validation score   (-root_mean_squared_error)
	4.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 1172.31s of the 1172.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.027	 = Validation score   (-root_mean_squared_error)
	0.63s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1171.54s of the 1171.53s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1533	 = Validation score   (-root_mean_squared_error)
	14.39s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 1152.71s of the 1152.70s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.05%)
	-1.1709	 = Validation score   (-root_mean_squared_error)
	2.09s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1144.78s of the 1144.77s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1501	 = Validation score   (-root_mean_squared_error)
	13.98s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1125.94s of the 1125.93s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.56%)
	-1.085	 = Validation score   (-root_mean_squared_error)
	2.03s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 1117.58s of the 1117.57s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.24%)
	-1.0358	 = Validation score   (-root_mean_squared_error)
	4.45s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 1108.31s of the 1108.29s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0293	 = Validation score   (-root_mean_squared_error)
	12.96s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 1090.85s of the 1090.83s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.24%)
	-1.4332	 = Validation score   (-root_mean_squared_error)
	2.81s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 1082.06s of the 1082.05s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.2157	 = Validation score   (-root_mean_squared_error)
	13.32s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 1064.31s of the 1064.29s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.33%)
	-1.1002	 = Validation score   (-root_mean_squared_error)
	11.38s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 1047.15s of the 1047.13s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.06%)
	-3.3903	 = Validation score   (-root_mean_squared_error)
	2.82s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 1040.50s of the 1040.48s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1102	 = Validation score   (-root_mean_squared_error)
	13.24s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 1022.39s of the 1022.37s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.25%)
	-1.0022	 = Validation score   (-root_mean_squared_error)
	2.94s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 1014.75s of the 1014.74s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0044	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 1013.93s of the 1013.92s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=2.93%)
	-0.9294	 = Validation score   (-root_mean_squared_error)
	7.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 1001.61s of the 1001.59s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1631	 = Validation score   (-root_mean_squared_error)
	8.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 989.29s of the 989.27s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.36%)
	-1.0929	 = Validation score   (-root_mean_squared_error)
	4.54s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 980.71s of the 980.69s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0044	 = Validation score   (-root_mean_squared_error)
	0.7s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 979.90s of the 979.89s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.49%)
	-1.0349	 = Validation score   (-root_mean_squared_error)
	2.56s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 973.73s of the 973.72s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0745	 = Validation score   (-root_mean_squared_error)
	8.47s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 962.02s of the 962.01s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.04%)
	-0.9948	 = Validation score   (-root_mean_squared_error)
	1.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 956.80s of the 956.79s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.98	 = Validation score   (-root_mean_squared_error)
	9.92s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 943.38s of the 943.36s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.35%)
	-3.3903	 = Validation score   (-root_mean_squared_error)
	1.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 938.37s of the 938.36s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.1401	 = Validation score   (-root_mean_squared_error)
	13.02s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 921.89s of the 921.88s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.25%)
	-0.9811	 = Validation score   (-root_mean_squared_error)
	5.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 911.16s of the 911.15s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.9961	 = Validation score   (-root_mean_squared_error)
	10.05s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 896.28s of the 896.26s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.08%)
	-1.0908	 = Validation score   (-root_mean_squared_error)
	0.83s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 890.87s of the 890.86s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-2.3521	 = Validation score   (-root_mean_squared_error)
	0.52s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 890.24s of the 890.23s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=2.87%)
	-1.0127	 = Validation score   (-root_mean_squared_error)
	2.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 884.45s of the 884.44s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.3887	 = Validation score   (-root_mean_squared_error)
	8.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 871.91s of the 871.90s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.246	 = Validation score   (-root_mean_squared_error)
	11.83s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 855.17s of the 855.15s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.02%)
	-1.1517	 = Validation score   (-root_mean_squared_error)
	2.31s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 848.43s of the 848.41s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.9265	 = Validation score   (-root_mean_squared_error)
	8.07s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 836.67s of the 836.66s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.33%)

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema070926_IRI-GBEI-comparison__3326e693,2026-09-09T17:55:48,212.3,59,405e27af,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__3326e693,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison,NaN,iacs_final,...,0.34159,11,0.56906,0.42787,0.44104,0.97468,0.7273,1.0000,1.0000,1.0000
1,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0,2026-09-09T18:17:49,1318.2,59,405e27af,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.80356,0.59441,0.60275,0.94952,0.5455,0.9091,0.9091,0.9091
2,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-purity-iacs-temperature-time__9e794bcd,2026-09-09T18:40:01,1331.6,59,e235e43e,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-purity-iacs-temperature-time__9e794bcd,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.78421,0.49142,0.51231,0.95192,0.8182,0.9091,1.0000,1.0000
3,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-iacs-temperature-time__ed60a32a,2026-09-09T19:01:40,1299.3,59,b479036c,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-iacs-temperature-time__ed60a32a,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.61589,0.48372,0.49452,0.97035,0.6364,0.9091,0.9091,0.9091
4,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-IRI-purity-iacs-temperature-time__481f9e11,2026-09-09T19:23:14,1293.3,59,2e174cf5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-IRI-purity-iacs-temperature-time__481f9e11,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.59566,0.45216,0.45947,0.97226,0.9091,1.0000,1.0000,1.0000
5,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-purity-iacs-temperature-time__791fa64f,2026-09-09T19:45:38,1343.9,59,6d04d1d2,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-purity-iacs-temperature-time__791fa64f,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.65427,0.49194,0.50437,0.96653,0.6364,0.9091,0.9091,0.9091
6,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-purity-iacs-temperature-time__235185cb,2026-09-09T20:07:40,1322.7,59,f4a814c8,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-purity-iacs-temperature-time__235185cb,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.34020,11,0.81883,0.56121,0.57877,0.94758,0.9091,0.9091,0.9091,1.0000
7,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-iacs-temperature-time__65bad412,2026-09-09T20:29:57,1336.8,59,7611edba,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-iacs-temperature-time__65bad412,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.73340,0.55495,0.56578,0.95795,0.6364,0.8182,0.9091,0.9091
8,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-iacs-temperature-time__2230cb2b,2026-09-09T20:53:13,1395.5,59,c68e325c,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-iacs-temperature-time__2230cb2b,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.69802,0.51710,0.53091,0.96191,0.8182,1.0000,1.0000,1.0000
9,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__6cb1919f,2026-09-09T21:28:50,2136.8,59,405e27af,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__6cb1919f,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.80356,0.59441,0.60275,0.94952,0.5455,0.9091,0.9091,0.9091
10,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-purity-iacs-temperature-time__2e4f10e9,2026-09-09T22:03:20,2070.2,59,e235e43e,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-purity-iacs-temperature-time__2e4f10e9,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.74131,0.51066,0.52997,0.95704,0.8182,0.9091,0.9091,1.0000
11,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-iacs-temperature-time__cd275aad,2026-09-09T22:41:54,2313.5,59,b479036c,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-iacs-temperature-time__cd275aad,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.61904,0.49839,0.50771,0.97004,0.6364,0.9091,0.9091,0.9091
12,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-IRI-purity-iacs-temperature-time__5eae2b75,2026-09-09T23:20:15,2301.4,59,2e174cf5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-IRI-purity-iacs-temperature-time__5eae2b75,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33480,11,0.62365,0.46739,0.47441,0.96959,0.9091,1.0000,1.0000,1.0000
13,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-purity-iacs-temperature-time__491fb9cd,2026-09-09T23:56:34,2178.7,59,6d04d1d2,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-purity-iacs-temperature-time__491fb9cd,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.67580,0.50712,0.51923,0.96430,0.7273,0.9091,0.9091,1.0000
14,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-purity-iacs-temperature-time__311cef01,2026-09-10T00:38:20,2505.6,59,f4a814c8,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-purity-iacs-temperature-time__311cef01,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.34021,11,0.81883,0.56121,0.57877,0.94758,0.9091,0.9091,0.9091,1.0000
15,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-iacs-temperature-time__7220e51d,2026-09-10T01:24:07,2747.6,59,7611edba,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-iacs-temperature-time__7220e51d,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.68475,0.51390,0.52244,0.96334,0.6364,0.9091,0.9091,0.9091
16,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-iacs-temperature-time__feea776b,2026-09-10T02:00:16,2169.1,59,c68e325c,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema070926_IRI-GBEI-comparison\annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-iacs-temperature-time__feea776b,annealing_iacs,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-iacs-temperature-time,annealing-schema070926_IRI-GBEI-comparison,iacs_final,...,0.33299,11,0.62262,0.47491,0.48485,0.96969,0.5455,1.0000,1.0000,1.0000

In [14]:
# import pickle
# from pathlib import Path
# import pandas as pd

# exp_dir = Path("../../models/annealing_iacs/experiments")
# rows = []
# for run_path in exp_dir.iterdir():
#     pkl = run_path / "artifacts.pkl"
#     if not pkl.exists():
#         continue
#     with open(pkl, "rb") as f:
#         art = pickle.load(f)
#     row = {"run_id": run_path.name}
#     row.update({f"cfg_{k}": v for k, v in art["config"].items()})
#     m = dict(art["metrics"]); m.pop("coverage", None)
#     row.update({k: v for k, v in m.items()})
#     cov = art["metrics"].get("coverage", {})
#     row.update({f"cov_{a}": c for a, c in cov.items()})
#     row["c_opt"] = art["recalibration_c"]
#     if art.get("validation_metrics"):
#         vm = dict(art["validation_metrics"]); vcov = vm.pop("coverage", {})
#         row.update({f"val_{k}": v for k, v in vm.items()})
#         row.update({f"val_cov_{a}": c for a, c in vcov.items()})
#     row["cfg_features"] = "|".join(art["features"])
#     rows.append(row)

# pd.DataFrame(rows).to_csv(exp_dir / "experiments_log.csv", index=False)
# print(f"Rebuilt log with {len(rows)} runs")

# 7. Inspect results

In [15]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_num_bag_folds_a", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9",
    "c_opt", "pct_truncated_aleat", "mean_sigma_epist", "mean_sigma_aleat",
    "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_num_bag_folds_a,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
1,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0,1200,5,GBEI|initial_diameter|IRI|purity|iacs|temperature|time,0.79588,0.63987,0.8983,0.80356,0.59441,0.9091,1.3156,52.54,0.49375,0.33299,1318.2
9,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__6cb1919f,3600,5,GBEI|initial_diameter|IRI|purity|iacs|temperature|time,0.79588,0.63987,0.8983,0.80356,0.59441,0.9091,1.3156,52.54,0.49375,0.33299,2136.8
11,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-IRI-iacs-temperature-time__cd275aad,3600,5,GBEI|initial_diameter|IRI|iacs|temperature|time,0.80666,0.63788,0.9153,0.61904,0.49839,0.9091,1.4549,44.07,0.48090,0.33299,2313.5
15,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-iacs-temperature-time__7220e51d,3600,5,initial_diameter|IRI|iacs|temperature|time,0.82322,0.65129,0.9153,0.68475,0.51390,0.9091,1.4549,27.12,0.35482,0.33299,2747.6
7,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-iacs-temperature-time__65bad412,1200,5,initial_diameter|IRI|iacs|temperature|time,0.83190,0.64140,0.8983,0.73340,0.55495,0.9091,1.6473,38.98,0.39454,0.33299,1336.8
10,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-initial_diameter-purity-iacs-temperature-time__2e4f10e9,3600,5,GBEI|initial_diameter|purity|iacs|temperature|time,0.83994,0.65199,0.8814,0.74131,0.51066,0.9091,1.8387,37.29,0.37740,0.33299,2070.2
3,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-iacs-temperature-time__ed60a32a,1200,5,GBEI|initial_diameter|IRI|iacs|temperature|time,0.85394,0.68834,0.9153,0.61589,0.48372,0.9091,1.4549,37.29,0.47898,0.33299,1299.3
2,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-purity-iacs-temperature-time__9e794bcd,1200,5,GBEI|initial_diameter|purity|iacs|temperature|time,0.86307,0.67684,0.9322,0.78421,0.49142,1.0000,2.0451,32.20,0.34480,0.33299,1331.6
13,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-IRI-purity-iacs-temperature-time__491fb9cd,3600,5,initial_diameter|IRI|purity|iacs|temperature|time,0.86717,0.67223,0.9153,0.67580,0.50712,0.9091,1.7659,42.37,0.44853,0.33299,2178.7
16,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=IRI-purity-iacs-temperature-time__feea776b,3600,5,IRI|purity|iacs|temperature|time,0.87089,0.67045,0.8983,0.62262,0.47491,1.0000,1.5957,40.68,0.45264,0.33299,2169.1
5,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-IRI-purity-iacs-temperature-time__791fa64f,1200,5,initial_diameter|IRI|purity|iacs|temperature|time,0.87362,0.66757,0.8983,0.65427,0.49194,0.9091,1.4549,38.98,0.43126,0.33299,1343.9
8,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=IRI-purity-iacs-temperature-time__2230cb2b,1200,5,IRI|purity|iacs|temperature|time,0.87628,0.68800,0.9322,0.69802,0.51710,1.0000,1.8197,38.98,0.42962,0.33299,1395.5
14,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=initial_diameter-purity-iacs-temperature-time__311cef01,3600,5,initial_diameter|purity|iacs|temperature|time,0.89704,0.71272,0.9661,0.81883,0.56121,0.9091,2.0451,27.12,0.35904,0.34021,2505.6
6,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=initial_diameter-purity-iacs-temperature-time__235185cb,1200,5,initial_diameter|purity|iacs|temperature|time,0.89704,0.71272,0.9661,0.81883,0.56121,0.9091,2.0451,27.12,0.35904,0.34020,1322.7
4,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-IRI-purity-iacs-temperature-time__481f9e11,1200,5,GBEI|IRI|purity|iacs|temperature|time,0.90314,0.71419,0.8983,0.59566,0.45216,1.0000,1.8743,30.51,0.37273,0.33299,1293.3
12,annealing-schema070926_IRI-GBEI-comparison__time_limit_a=3600__features=GBEI-IRI-purity-iacs-temperature-time__5eae2b75,3600,5,GBEI|IRI|purity|iacs|temperature|time,0.91084,0.70665,0.8983,0.62365,0.46739,1.0000,1.8571,23.73,0.34336,0.33480,2301.4
0,annealing-schema070926_IRI-GBEI-comparison__3326e693,120,5,GBEI|initial_diameter|IRI|purity|iacs|temperature|time,0.99347,0.78600,0.9153,0.56906,0.42787,1.0000,2.0451,22.03,0.34759,0.34159,212.3

In [16]:
# Quick pivot: effect of one knob, marginalised over the others.
# Remember: compare against run-to-run noise (Section 4) before concluding.
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                      rmse                 mae             cov_0.9
                      mean       std      mean       std      mean       std
cfg_time_limit_a
120               0.993470       NaN  0.786000       NaN  0.915300       NaN
1200              0.861859  0.035057  0.678616  0.028341  0.917375  0.024708
3600              0.851455  0.041840  0.667885  0.028664  0.911037  0.025218

# 8. Load a winner for deployment / further analysis

Each run folder is self-contained: predictors + artifacts.pkl with weights,
`recalibration_c`, calibration tables.

In [17]:
# log already carries the resolved absolute path, so use it directly
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0

   alpha  empirical_coverage       gap
0   0.50            0.559322  0.059322
1   0.80            0.813559  0.013559
2   0.90            0.898305 -0.001695
3   0.95            0.932203 -0.017797

In [18]:
1

1

In [19]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-schema070926_IRI-GBEI-comparison/annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0')

In [20]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-schema070926_IRI-GBEI-comparison/annealing-schema070926_IRI-GBEI-comparison__time_limit_a=1200__features=GBEI-initial_diameter-IRI-purity-iacs-temperature-time__dbacf8e0')