**Author**: Felipe Matheus  
**Start Date**: 29/07/2026  
**End Date**: --/07/2026  
**Purpose**: Experiment launcher ("control panel") for the annealing_iacs surrogate.

This notebook does NOT contain pipeline logic. All the logic (Model A -> OOF ->
NNLS -> Model B -> calibration -> metrics -> persistence) lives in
`src/modeling/Experiments.py`, which orchestrates the existing `Modeling` and
`Evaluation` helpers. Here you only:

1. Load and prepare the data (once).
2. Define a base `ExperimentConfig`.
3. Define the grid of variations you want to sweep.
4. Run and inspect the central `experiments_log.csv`.

Results layout on disk:
```
models/annealing_iacs/experiments/
    experiments_log.csv          <- 1 row per run (the "results spreadsheet")
    <tag>__<hash>/               <- 1 folder per run
        config.yaml
        model_a/   model_b/
        artifacts.pkl
        leaderboard_autogluon.csv
```

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
TARGET = "elongation_final"
FEATURES = ["initial_diameter", "tensile_strength", "purity", "elongation", "temperature", "time"]
PROCESS = "annealing_elongation"

SCHEMA_DATE = "230726"
FILE_NAME_SCHEMA_DATA = "schema_annealing_essays_{}.csv".format(SCHEMA_DATE)

TAG = f"annealing-schema{SCHEMA_DATE}"
GRID = {
    "time_limit_a": [300, 600],
    # "num_bag_folds_a": [10, 20],
    "features": [
        ("initial_diameter", "tensile_strength", "purity", "elongation", "temperature", "time"),
        ("initial_diameter", "purity", "elongation", "temperature", "time"),
    ],
}

# 2. Data (same preparation as annealing_elongation.ipynb, run once)

In [3]:
df, df_val = proc.process_annealing_elongation(
    features=FEATURES,
    target=TARGET,
    df_schema=pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
)

In [ ]:
# # SCHEMA_DATE = "080626"
# # FILE_NAME = "dataset_annealing_iacs.csv"
# FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{SCHEMA_DATE}.csv"
# # FILE_NAME_VALIDATION_DATA = "Experimental Results Annealing V2 - CompiledResults.csv"

# # ---- Schema (essay) data: explicit is_essay marker ----
# df_raw_schema = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
# df_schema = df_raw_schema[ALL_FEATURES + [TARGET]].dropna()
# df_schema["is_essay"] = True

# # ---- Literature data ----
# df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
# df_float = proc.df_to_float(df_raw, drop_cols=["DOI"], ignore_columns=["material"])
# df_labeled = feng.label_element(df_float).drop_duplicates()
# df_with_masks = feng.add_ratio_mask_column(
#     feng.add_ratio_mask_column(df_labeled, "grain_size"), "iacs",
# )
# df_lit = df_with_masks[df_with_masks.has_Cu == True][ALL_FEATURES + [TARGET]]
# df_lit["is_essay"] = False

# # ---- Validation data ----
# df_val = proc.load_validation_data_chimie_paris(
#     path=os.path.join(varv.PATHS.data_processed, FILE_NAME_VALIDATION_DATA)
# )

# assert df_lit[ALL_FEATURES + [TARGET]].isna().sum().sum() == 0, "NaNs in inputs"

# # ---- Concat. weight_col is built INSIDE the runr from is_essay + config ----
# df = pd.concat([df_schema, df_lit], ignore_index=True)
# print(f"Dataset: {df.shape} | essays: {df.is_essay.sum()} | lit: {(~df.is_essay).sum()}")
# df.head()

Dataset: (96, 6) | essays: 9 | lit: 87

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:37: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(

   purity    iacs  temperature  time  iacs_final  is_essay
0    99.9  88.260        623.0  30.0      88.350      True
1    99.9  88.260        623.0  60.0      88.655      True
2    99.9  88.260        623.0  90.0      88.800      True
3    99.9  99.825        573.0  30.0     102.340      True
4    99.9  99.390        573.0  30.0     102.230      True

# 3. Base config

In [18]:
df = df[df.iacs > 90]

In [19]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a = "best_quality",
    #     presets_a = "medium_quality"
    #     presets_b = "medium_quality"
    # everything else uses the defaults; override here if needed, e.g.:
    # time_limit_a=120, weight_on_essay_rows=1.0, use_shared_folds=False,
)
print(base.run_id)

annealing-v2-weight-3-best-quality__9e081980

# 4. Single run (sanity check before any grid)

Always run the base config alone first. Then run it 2-3 more times with
`tag="annealing-v1-rep2"` etc. to measure run-to-run noise: AutoGluon under a
time budget is NOT deterministic, and at n~90 this noise is the floor below
which grid differences mean nothing.

In [20]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-07-07 15:25:12,570 | INFO | src.modeling.Experiments | === Running annealing-v2-weight-3-best-quality__9e081980 ===
Warning: path already exists! This predictor may overwrite an existing predictor! path="..\..\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980\model_a"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       12.13 GB / 31.57 GB (38.4%)
Disk Space Avail:   732.26 GB / 932.08 GB (78.6%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980\model_a"
Train Data Rows:    26
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (105.0, 95.0, 100.77333, 2.7099)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12407.70 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 3 | ['iacs', 'temperature', 'time']
		('int', ['bool']) : 1 | ['purity']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.95s of the 119.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-2.8385	 = Validation score   (-root_mean_squared_error)
	1.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 103.48s of the 103.47s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.15%)
	-2.8385	 = Validation score   (-root_mean_squared_error)
	3.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 96.20s of the 96.19s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-0.9607	 = Validation score   (-root_mean_squared_error)
	0.98s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 94.99s of the 94.97s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.32%)
	-1.3918	 = Validation score   (-root_mean_squared_error)
	56.98s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 34.30s of the 34.29s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-0.935	 = Validation score   (-root_mean_squared_error)
	0.85s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 33.29s of the 33.27s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.8297	 = Validation score   (-root_mean_squared_error)
	14.7s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 14.12s of the 14.11s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.04%)
	-1.0593	 = Validation score   (-root_mean_squared_error)
	2.94s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 7.53s of the 7.52s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.95s of the -426.07s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/11.6 GB
	Ensemble Weights: {'ExtraTreesMSE_BAG_L1': 0.64, 'XGBoost_BAG_L1': 0.32, 'RandomForestMSE_BAG_L1': 0.04}
	-0.8848	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 546.13s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 63.6 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.64 GB / 31.57 GB (36.9%)
Disk Space Avail:   732.24 GB / 932.08 GB (78.6%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980\model_b"
Train Data Rows:    26
Train Data Columns: 4
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1.9469413568540566, -13.815510557964274, -5.74309, 6.59904)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11910.77 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 3 | ['iacs', 'temperature', 'time']
		('int', ['bool']) : 1 | ['purity']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.97s of the 59.97s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-6.5702	 = Validation score   (-root_mean_squared_error)
	0.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 56.62s of the 56.62s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-6.5702	 = Validation score   (-root_mean_squared_error)
	1.03s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 52.78s of the 52.78s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.1359	 = Validation score   (-root_mean_squared_error)
	0.4s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 52.30s of the 52.29s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.34%)
	-6.5456	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 48.55s of the 48.55s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.2411	 = Validation score   (-root_mean_squared_error)
	0.41s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 48.05s of the 48.05s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-6.5595	 = Validation score   (-root_mean_squared_error)
	6.07s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 39.50s of the 39.50s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.04%)
	-6.6074	 = Validation score   (-root_mean_squared_error)
	1.09s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 34.46s of the 34.46s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-6.4711	 = Validation score   (-root_mean_squared_error)
	6.89s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 23.79s of the 23.79s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.61%)
	-6.5629	 = Validation score   (-root_mean_squared_error)
	1.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.97s of the 18.49s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/10.9 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.762, 'RandomForestMSE_BAG_L1': 0.19, 'CatBoost_BAG_L1': 0.048}
	-6.4223	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 41.57s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 127.4 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980\model_b")
2026-07-07 15:35:03,673 | INFO | src.modeling.Experiments | Validation (n=36): rmse=1.4216 mae=1.1201
2026-07-07 15:35:03,717 | INFO | src.modeling.Experiments | Done annealing-v2-weight-3-best-quality__9e081980 in 591.1s

{'rmse': 0.8847832475335353,
 'mae': 0.6586034282677284,
 'mape': 0.6571651306970457,
 'r2': 0.8891336496579376}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

Using `df_schema` as `df_val` is illustrative: those rows are inside the
training data, so val metrics are optimistic. Swap in any held-out
DataFrame with the same columns and nothing else changes.

In [21]:
df_val

,id,purity,initial_diameter,iacs,temperature,time,iacs_final
0,C1_250_30m_T1,99.95,1.2,98.47,523,30,101.08
1,C1_250_30m_T3,99.95,1.2,98.47,523,30,101.08
2,C1_250_60m_T1,99.95,1.2,98.47,523,60,100.82
3,C1_250_60m_T2,99.95,1.2,98.47,523,60,100.82
4,C1_250_90m_T1,99.95,1.2,98.47,523,90,101.22
5,C1_250_90m_T2,99.95,1.2,98.47,523,90,101.22
6,C1_250_30m_AQ_T1,99.95,1.2,98.47,523,30,100.95
7,C1_250_30m_AQ_T2,99.95,1.2,98.47,523,30,100.95
8,C1_300_30m_T1,99.95,1.2,98.47,573,30,102.03
9,C1_300_30m_T2,99.95,1.2,98.47,573,30,102.03
10,C1_300_60m_T1,99.95,1.2,98.47,573,60,101.08
11,C1_300_60m_T2,99.95,1.2,98.47,573,60,101.08
12,C1_300_90m_T1,99.95,1.2,98.47,573,90,101.08
13,C1_300_90m_T2,99.95,1.2,98.47,573,90,101.08
14,C1_350_30m_T1,99.95,1.2,98.47,623,30,100.29
15,C1_350_30m_T2,99.95,1.2,98.47,623,30,100.29
16,C1_350_60m_T1,99.95,1.2,98.47,623,60,100.55
17,C1_350_60m_T2,99.95,1.2,98.47,623,60,100.55
18,C2_250_30m_T1,99.90,1.2,97.71,523,30,100.29
19,C2_250_30m_T2,99.90,1.2,97.71,523,30,100.29
20,C2_250_60m_T1,99.90,1.2,97.71,523,60,100.42
21,C2_250_60m_T2,99.90,1.2,97.71,523,60,100.42
22,C2_250_90m_T1,99.90,1.2,97.71,523,90,100.29
23,C2_250_90m_T2,99.90,1.2,97.71,523,90,100.29
24,C2_300_30m_T1,99.90,1.2,97.71,573,30,101.22
25,C2_300_30m_T2,99.90,1.2,97.71,573,30,101.22
26,C2_300_60m_T1,99.90,1.2,97.71,573,60,101.35
27,C2_300_60m_T2,99.90,1.2,97.71,573,60,101.35
28,C2_300_90m_T1,99.90,1.2,97.71,573,90,101.35
29,C2_300_90m_T2,99.90,1.2,97.71,573,90,101.35
30,C2_350_30m_T1,99.90,1.2,97.71,623,30,100.55
31,C2_350_30m_T2,99.90,1.2,97.71,623,30,100.55
32,C2_350_60m_T1,99.90,1.2,97.71,623,60,100.68
33,C2_350_60m_T2,99.90,1.2,97.71,623,60,100.68
34,C2_350_90m_T1,99.90,1.2,97.71,623,90,100.29
35,C2_350_90m_T2,99.90,1.2,97.71,623,90,100.29

In [22]:
result["artifacts"]["validation_metrics"]

{'rmse': 1.4216301045035884,
 'mae': 1.1201457761156972,
 'mape': 1.1129637440244284,
 'r2': -8.138509538925913,
 'coverage': {0.5: 0.16666666666666666,
  0.8: 0.4444444444444444,
  0.9: 0.5,
  0.95: 0.6666666666666666}}

In [23]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [24]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [25]:
result

{'cfg': ExperimentConfig(process='annealing_iacs', tag='annealing-v2-weight-3-best-quality', base_tag=None, target='iacs_final', features=('purity', 'iacs', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=None, fold_seed=42, use_shared_folds=False),
 'run_dir': Path('../../models/annealing_iacs/experiments/annealing-v2-weight-3-best-quality/annealing-v2-weight-3-best-quality__9e081980'),
 'artifacts': {'config': {'process': 'annealing_iacs',
   'tag': 'annealing-v2-weight-3-best-quality',
   'base_tag': None,
   'target': 'iacs_final',
   'features': ['purity', 'iacs', 'temperature', 'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': None,
   'fold_seed': 42,
   'use_shared_folds': False},
  'features': ['purity', 'iacs', 'temperature', 'time'],
  'target': 'iacs_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1'],
  'weights': array([0.        , 0.        , 0.04000027, 0.        , 0.63999959,
         0.        , 0.32000014]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 3.832797460745496e-06,
  'variance_floor': 0.07343572223751113,
  'recalibration_c': 2.012200016030775,
  'ood_ref': {'features': ['purity', 'iacs', 'temperature', 'time'],
   'mean': array([ 99.92153846,  97.72326923, 546.65384615, 108.46153846]),
   'cov_inv': array([[ 1.00617313e+02,  3.37223783e-01,  1.58022951e-02,
           -9.76877984e-03],
          [ 3.37223783e-01,  1.23776499e-01, -5.12867906e-04,
            5.84817627e-04],
          [ 1.58022951e-02, -5.12867906e-04,  2.52707240e-04,
            5.09053323e-06],
          [-9.76877984e-03,  5.84817627e-04,  5.09053323e-06,
            3.45431946e-05]]),
   'd_ref': 2.7647784093112007,
   'ranges': {'purity': (99.9, 99.98),
    'iacs': (92.0, 100.25),
    'temperature': (423.0, 673.0),
    'time': (30.0, 600.0)}},
  'y_max': None,
  'y_min': None,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.346154 -0.153846
  1   0.80            0.423077 -0.376923
  2   0.90            0.576923 -0.323077
  3   0.95            0.692308 -0.257692,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.461538 -0.038462
  1   0.80            0.769231 -0.030769
  2   0.90            0.884615 -0.015385
  3   0.95            0.923077 -0.026923,
  'aleatoric_diagnostics': {'n_total': 26,
   'n_truncated': 10,
   'pct_truncated': 38.46153846153846,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 7.0072211777342055,
   'r_tilde_sq_mean': 0.6748502391683312,
   'r_tilde_sq_median': 0.18910929518226677},
  'metrics': {'rmse': 0.8847832475335353,
   'mae': 0.6586034282677284,
   'mape': 0.6571651306970457,
   'r2': 0.8891336496579376},
  'validation_metrics': {'rmse': 1.4216301045035884,
   'mae': 1.1201457761156972,
   'mape': 1.1129637440244284,
   'r2': -8.138509538925913,
   'coverage': {0.5: 0.16666666666666666,
    0.8: 0.4444444444444444,
    0.9: 0.5,
    0.95: 0.6666666666666666}},
  'dataset_hash': 'c054a007'},
 'log_row': {'run_id': 'annealing-v2-weight-3-best-quality__9e081980',
  'timestamp': '2026-07-07T15:35:03',
  'elapsed_s': 591.1,
  'n_rows': 26,
  'dataset_hash': 'c054a007',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_iacs\\experiments\\annealing-v2-weight-3-best-quality\\annealing-v2-weight-3-best-quality__9e081980',
  'cfg_process': 'annealing_iacs',
  'cfg_tag': 'annealing-v2-weight-3-best-quality',
  'cfg_base_tag': None,
  'cfg_target': 'iacs_final',
  'cfg_features': 'purity|iacs|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'medium_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': None,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'rmse': 0.88478,
  'mae': 0.6586,
  'mape': 0.65717,
  'r2': 0.88913,
  'cov_0.5': 0.4615,
  'cov_0.8': 0.7692,
  'cov_0.9': 0.8846,
  'cov_0.95': 0.9231,
  'c_opt': 2.0122,
  'pct_truncated_aleat': 38.46,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 0.30484,
  'mean_sigma_aleat': 0.27099,
  'n_val': 36,
  'val_rmse': 1.42163,
  'val_mae': 1.12015,
  'val_mape': 1.11296,
  'val_r2': -8.13851,
  'val_cov_0.5': 0.1667,
  'val_cov_0.8': 0.4444,
  'val_cov_0.9': 0.5,
  'val_cov_0.95': 0.6667},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1bc37fad710>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x1bc3ae9b790>}

# 6. Grid

Keys are `ExperimentConfig` field names; values are lists of variants.
`features` variants must be tuples. Already-completed runs are skipped
(`force=True` to redo).

In [26]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-07-07 15:35:05,350 | INFO | src.modeling.Experiments | Grid: 2 runs over ['time_limit_a', 'num_bag_folds_a', 'weight_on_essay_rows']
2026-07-07 15:35:05,350 | INFO | src.modeling.Experiments | === Running annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0__a832725d ===
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.48 GB / 31.57 GB (36.4%)
Disk Space Avail:   732.23 GB / 932.08 GB (78.6%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=10, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0__a832725d\model_a"
Train Data Rows:    26
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (105.0, 95.0, 100.77333, 2.7099)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11746.74 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 3 | ['iacs', 'temperature', 'time']
		('int', ['bool']) : 1 | ['purity']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 599.98s of the 599.97s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.13%)
	-2.763	 = Validation score   (-root_mean_squared_error)
	5.0s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 589.98s of the 589.98s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.14%)
	-2.763	 = Validation score   (-root_mean_squared_error)
	3.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 580.78s of the 580.78s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-0.9851	 = Validation score   (-root_mean_squared_error)
	0.31s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 580.39s of the 580.39s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.35%)
	-1.2485	 = Validation score   (-root_mean_squared_error)
	29.4s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 545.63s of the 545.63s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-0.941	 = Validation score   (-root_mean_squared_error)
	0.29s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 545.26s of the 545.25s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.7731	 = Validation score   (-root_mean_squared_error)
	16.53s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 523.84s of the 523.83s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	-0.9856	 = Validation score   (-root_mean_squared_error)
	3.65s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 515.00s of the 515.00s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.4371	 = Validation score   (-root_mean_squared_error)
	16.74s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 492.94s of the 492.94s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.58%)
	-1.1855	 = Validation score   (-root_mean_squared_error)
	4.69s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 482.69s of the 482.69s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.28%)
	-1.2066	 = Validation score   (-root_mean_squared_error)
	9.79s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 467.69s of the 467.69s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.7756	 = Validation score   (-root_mean_squared_error)
	15.72s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 446.74s of the 446.74s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.23%)
	-2.763	 = Validation score   (-root_mean_squared_error)
	4.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 437.42s of the 437.42s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.8843	 = Validation score   (-root_mean_squared_error)
	16.31s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 415.68s of the 415.67s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.51%)
	-1.3464	 = Validation score   (-root_mean_squared_error)
	19.75s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 390.55s of the 390.55s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.07%)
	-2.763	 = Validation score   (-root_mean_squared_error)
	4.18s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 381.15s of the 381.14s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.5888	 = Validation score   (-root_mean_squared_error)
	15.63s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 360.21s of the 360.20s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.17%)
	-0.7743	 = Validation score   (-root_mean_squared_error)
	4.47s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 350.35s of the 350.34s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-0.9681	 = Validation score   (-root_mean_squared_error)
	0.36s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 349.91s of the 349.91s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.20%)
	-1.0195	 = Validation score   (-root_mean_squared_error)
	7.34s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 337.37s of the 337.37s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.7731	 = Validation score   (-root_mean_squared_error)
	16.59s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 315.46s of the 315.45s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.41%)
	-1.2738	 = Validation score   (-root_mean_squared_error)
	34.1s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 275.89s of the 275.89s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0054	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 275.30s of the 275.30s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.53%)
	-1.5827	 = Validation score   (-root_mean_squared_error)
	5.0s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 265.68s of the 265.68s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.7131	 = Validation score   (-root_mean_squared_error)
	17.0s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 243.28s of the 243.28s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.04%)
	-0.7423	 = Validation score   (-root_mean_squared_error)
	3.71s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 234.13s of the 234.13s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.8336	 = Validation score   (-root_mean_squared_error)
	15.9s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 212.88s of the 212.88s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.40%)
	-2.763	 = Validation score   (-root_mean_squared_error)
	4.17s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 203.48s of the 203.48s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.8529	 = Validation score   (-root_mean_squared_error)
	15.91s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 182.26s of the 182.26s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.35%)
	-1.0615	 = Validation score   (-root_mean_squared_error)
	31.65s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 145.34s of the 145.34s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.8843	 = Validation score   (-root_mean_squared_error)
	16.9s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 123.56s of the 123.56s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.06%)
	-0.9344	 = Validation score   (-root_mean_squared_error)
	3.52s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 114.58s of the 114.58s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.9282	 = Validation score   (-root_mean_squared_error)
	0.29s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 114.21s of the 114.20s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.26%)
	-1.1681	 = Validation score   (-root_mean_squared_error)
	8.68s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 100.28s of the 100.27s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.7522	 = Validation score   (-root_mean_squared_error)
	16.98s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 78.03s of the 78.02s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0663	 = Validation score   (-root_mean_squared_error)
	16.3s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 56.35s of the 56.34s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=1.12%)
	-2.433	 = Validation score   (-root_mean_squared_error)
	4.48s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 46.32s of the 46.31s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.7418	 = Validation score   (-root_mean_squared_error)
	16.74s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 24.20s of the 24.20s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=3.39%)
	-1.219	 = Validation score   (-root_mean_squared_error)
	7.89s	 = Training   runtime
	0.02s	 = Validation runtime

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-v2-weight-3-best-quality__9e081980,2026-07-07T15:35:03,591.1,26,c054a007,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__9e081980,annealing_iacs,annealing-v2-weight-3-best-quality,NaN,iacs_final,...,0.27099,36,1.42163,1.12015,1.11296,-8.13851,0.1667,0.4444,0.5000,0.6667
1,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0__a832725d,2026-07-07T15:46:19,673.8,26,c054a007,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0__a832725d,annealing_iacs,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0,annealing-v2-weight-3-best-quality,iacs_final,...,0.27099,36,1.31219,0.94355,0.93740,-6.78562,0.4444,0.6111,0.6111,0.7778
2,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc,2026-07-07T15:57:53,694.1,26,c054a007,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v2-weight-3-best-quality\annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc,annealing_iacs,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0,annealing-v2-weight-3-best-quality,iacs_final,...,0.27099,36,1.25733,0.92530,0.91919,-6.14829,0.3333,0.5000,0.5556,0.6111

In [27]:
# import pickle
# from pathlib import Path
# import pandas as pd

# exp_dir = Path("../../models/annealing_iacs/experiments")
# rows = []
# for run_path in exp_dir.iterdir():
#     pkl = run_path / "artifacts.pkl"
#     if not pkl.exists():
#         continue
#     with open(pkl, "rb") as f:
#         art = pickle.load(f)
#     row = {"run_id": run_path.name}
#     row.update({f"cfg_{k}": v for k, v in art["config"].items()})
#     m = dict(art["metrics"]); m.pop("coverage", None)
#     row.update({k: v for k, v in m.items()})
#     cov = art["metrics"].get("coverage", {})
#     row.update({f"cov_{a}": c for a, c in cov.items()})
#     row["c_opt"] = art["recalibration_c"]
#     if art.get("validation_metrics"):
#         vm = dict(art["validation_metrics"]); vcov = vm.pop("coverage", {})
#         row.update({f"val_{k}": v for k, v in vm.items()})
#         row.update({f"val_cov_{a}": c for a, c in vcov.items()})
#     row["cfg_features"] = "|".join(art["features"])
#     rows.append(row)

# pd.DataFrame(rows).to_csv(exp_dir / "experiments_log.csv", index=False)
# print(f"Rebuilt log with {len(rows)} runs")

# 7. Inspect results

In [28]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_weight_on_essay_rows", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9", "c_opt", "pct_truncated_aleat",
    "mean_sigma_epist", "mean_sigma_aleat", "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_weight_on_essay_rows,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
2,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc,600,2.0,purity|iacs|temperature|time,0.38467,0.23969,0.8846,1.25733,0.92530,0.5556,1.4549,23.08,0.07389,0.27099,694.1
1,annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=10__weight_on_essay_rows=2.0__a832725d,600,2.0,purity|iacs|temperature|time,0.57513,0.42376,0.9231,1.31219,0.94355,0.6111,1.8139,34.62,0.19646,0.27099,673.8
0,annealing-v2-weight-3-best-quality__9e081980,120,1.0,purity|iacs|temperature|time,0.88478,0.65860,0.8846,1.42163,1.12015,0.5000,2.0122,38.46,0.30484,0.27099,591.1

In [29]:
# Quick pivot: effect of one knob, marginalised over the others.
# Remember: compare against run-to-run noise (Section 4) before concluding.
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                     rmse                 mae            cov_0.9
                     mean       std      mean       std     mean       std
cfg_time_limit_a
120               0.88478       NaN  0.658600       NaN  0.88460       NaN
600               0.47990  0.134676  0.331725  0.130157  0.90385  0.027224

# 8. Load a winner for deployment / further analysis

Each run folder is self-contained: predictors + artifacts.pkl with weights,
`recalibration_c`, calibration tables.

In [30]:
# log already carries the resolved absolute path, so use it directly
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc

   alpha  empirical_coverage       gap
0   0.50            0.769231  0.269231
1   0.80            0.807692  0.007692
2   0.90            0.884615 -0.015385
3   0.95            0.961538  0.011538

In [31]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-v2-weight-3-best-quality/annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc')

In [32]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-v2-weight-3-best-quality/annealing-v2-weight-3-best-quality__time_limit_a=600__num_bag_folds_a=20__weight_on_essay_rows=2.0__b7afe3bc')