**Author**: Felipe Matheus  
**Start Date**: 29/07/2026  
**End Date**: --/07/2026  
**Purpose**: Experiment launcher ("control panel") for the annealing_iacs surrogate.

This notebook does NOT contain pipeline logic. All the logic (Model A -> OOF ->
NNLS -> Model B -> calibration -> metrics -> persistence) lives in
`src/modeling/Experiments.py`, which orchestrates the existing `Modeling` and
`Evaluation` helpers. Here you only:

1. Load and prepare the data (once).
2. Define a base `ExperimentConfig`.
3. Define the grid of variations you want to sweep.
4. Run and inspect the central `experiments_log.csv`.

Results layout on disk:
```
models/annealing_iacs/experiments/
    experiments_log.csv          <- 1 row per run (the "results spreadsheet")
    <tag>__<hash>/               <- 1 folder per run
        config.yaml
        model_a/   model_b/
        artifacts.pkl
        leaderboard_autogluon.csv
```

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
TARGET = "elongation_final"
ALL_FEATURES = ["initial_diameter", "tensile_strength", "purity", "elongation", "temperature", "time"]
PROCESS = "annealing_elongation"

SCHEMA_DATE = "110826"
FILE_NAME_SCHEMA_DATA = "schema_annealing_essays_{}.csv".format(SCHEMA_DATE)

TAG = f"annealing-schema{SCHEMA_DATE}"
GRID = {
    "time_limit_a": [900, 600],
    # "num_bag_folds_a": [10, 20],
    # "features": [
    #     ("initial_diameter", "tensile_strength", "purity", "elongation", "temperature", "time"),
    #     ("initial_diameter", "purity", "elongation", "temperature", "time"),
    # ],
}

# 2. Data (same preparation as annealing_elongation.ipynb, run once)

In [3]:
df, df_val = proc.process_annealing_elongation(
    features=ALL_FEATURES,
    target=TARGET,
    df_schema=pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
)

In [4]:
# # SCHEMA_DATE = "080626"
# # FILE_NAME = "dataset_annealing_iacs.csv"
# FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{SCHEMA_DATE}.csv"
# # FILE_NAME_VALIDATION_DATA = "Experimental Results Annealing V2 - CompiledResults.csv"

# # ---- Schema (essay) data: explicit is_essay marker ----
# df_raw_schema = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
# df_schema = df_raw_schema[ALL_FEATURES + [TARGET]].dropna()
# df_schema["is_essay"] = True

# # ---- Literature data ----
# df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
# df_float = proc.df_to_float(df_raw, drop_cols=["DOI"], ignore_columns=["material"])
# df_labeled = feng.label_element(df_float).drop_duplicates()
# df_with_masks = feng.add_ratio_mask_column(
#     feng.add_ratio_mask_column(df_labeled, "grain_size"), "iacs",
# )
# df_lit = df_with_masks[df_with_masks.has_Cu == True][ALL_FEATURES + [TARGET]]
# df_lit["is_essay"] = False

# # ---- Validation data ----
# df_val = proc.load_validation_data_chimie_paris(
#     path=os.path.join(varv.PATHS.data_processed, FILE_NAME_VALIDATION_DATA)
# )

# assert df_lit[ALL_FEATURES + [TARGET]].isna().sum().sum() == 0, "NaNs in inputs"

# # ---- Concat. weight_col is built INSIDE the runr from is_essay + config ----
# df = pd.concat([df_schema, df_lit], ignore_index=True)
# print(f"Dataset: {df.shape} | essays: {df.is_essay.sum()} | lit: {(~df.is_essay).sum()}")
# df.head()

# 3. Base config

In [ ]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a = "best_quality",
    #     presets_a = "medium_quality"
    #     presets_b = "medium_quality"
    # everything else uses the defaults; override here if needed, e.g.:
    # time_limit_a=120, weight_on_essay_rows=1.0, use_shared_folds=False,
)
print(base.run_id)

annealing-schema230726__78b06c52

# 4. Single run (sanity check before any grid)

Always run the base config alone first. Then run it 2-3 more times with
`tag="annealing-v1-rep2"` etc. to measure run-to-run noise: AutoGluon under a
time budget is NOT deterministic, and at n~90 this noise is the floor below
which grid differences mean nothing.

In [6]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-07-29 16:28:09,113 | INFO | src.modeling.Experiments | === Running annealing-schema230726__78b06c52 ===
2026-07-29 16:28:09,114 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       5.36 GB / 31.57 GB (17.0%)
Disk Space Avail:   737.06 GB / 932.08 GB (79.1%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__78b06c52\model_a"
Train Data Rows:    28
Train Data Columns: 7
Label Column:       elongation_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (61.1, 8.55, 39.1, 13.49557)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5462.48 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.95s of the 119.95s of remaining time.
2026-07-29 16:28:14,060	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-14.073	 = Validation score   (-root_mean_squared_error)
	0.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 108.28s of the 108.28s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.41%)
	-14.073	 = Validation score   (-root_mean_squared_error)
	1.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 103.22s of the 103.22s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-12.9976	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 102.47s of the 102.47s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.53%)
	-10.7825	 = Validation score   (-root_mean_squared_error)
	2.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 97.15s of the 97.15s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-11.606	 = Validation score   (-root_mean_squared_error)
	0.49s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 96.53s of the 96.53s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-14.2106	 = Validation score   (-root_mean_squared_error)
	7.73s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 85.40s of the 85.40s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.16%)
	-10.6001	 = Validation score   (-root_mean_squared_error)
	0.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 80.73s of the 80.73s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-8.4324	 = Validation score   (-root_mean_squared_error)
	7.71s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 69.35s of the 69.35s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.58%)
	-9.1296	 = Validation score   (-root_mean_squared_error)
	1.38s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.95s of the 64.19s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/4.6 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.714, 'LightGBMLarge_BAG_L1': 0.286}
	-8.2921	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 55.87s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 153.5 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__78b06c52\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       4.75 GB / 31.57 GB (15.0%)
Disk Space Avail:   737.05 GB / 932.08 GB (79.1%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__78b06c52\model_b"
Train Data Rows:    28
Train Data Columns: 6
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (7.141958521369611, -13.815510557964274, -1.31122, 7.48011)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5428.35 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.96s of the 59.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.29%)
	-7.9756	 = Validation score   (-root_mean_squared_error)
	1.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 55.60s of the 55.60s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.34%)
	-7.9756	 = Validation score   (-root_mean_squared_error)
	1.23s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 50.77s of the 50.76s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.8525	 = Validation score   (-root_mean_squared_error)
	0.45s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 50.22s of the 50.21s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.58%)
	-7.5556	 = Validation score   (-root_mean_squared_error)
	7.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 40.02s of the 40.02s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.8003	 = Validation score   (-root_mean_squared_error)
	0.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 39.63s of the 39.63s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-8.0747	 = Validation score   (-root_mean_squared_error)
	7.84s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 28.65s of the 28.65s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-7.3873	 = Validation score   (-root_mean_squared_error)
	1.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 23.98s of the 23.97s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-6.5891	 = Validation score   (-root_mean_squared_error)
	8.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 11.86s of the 11.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.72%)
	-7.0801	 = Validation score   (-root_mean_squared_error)
	1.46s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.96s of the 6.40s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/4.7 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.783, 'LightGBMLarge_BAG_L1': 0.174, 'XGBoost_BAG_L1': 0.043}
	-6.5486	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 53.66s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 119.9 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__78b06c52\model_b")
2026-07-29 16:30:05,460 | INFO | src.modeling.Experiments | Validation (n=8): rmse=10.5980 mae=6.5475
2026-07-29 16:30:05,508 | INFO | src.modeling.Experiments | Done annealing-schema230726__78b06c52 in 116.4s

{'rmse': 8.292139291336353,
 'mae': 5.245794353485107,
 'mape': 25.865454014424767,
 'r2': 0.6084882901723389}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

Using `df_schema` as `df_val` is illustrative: those rows are inside the
training data, so val metrics are optimistic. Swap in any held-out
DataFrame with the same columns and nothing else changes.

In [7]:
df_val

,initial_diameter,tensile_strength,purity,elongation,temperature,time,elongation_final
9,1.20,431.58,99.9000,0.94,623.0,60.0,26.17
25,2.00,376.08,99.9558,5.33,573.0,30.0,8.55
8,1.20,431.58,99.9000,0.94,623.0,30.0,27.06
21,1.20,335.21,99.9800,1.61,523.0,30.0,51.01
0,2.16,391.69,99.9000,4.90,573.0,30.0,48.60
12,1.20,397.09,99.9000,2.36,573.0,30.0,44.18
17,1.20,397.09,99.9000,2.36,523.0,90.0,42.28
22,1.20,335.21,99.9800,1.61,523.0,60.0,49.42

In [8]:
result["artifacts"]["validation_metrics"]

{'rmse': 10.597993658519528,
 'mae': 6.547539176124967,
 'mape': 48.52385742130462,
 'r2': 0.43481691755998053,
 'coverage': {0.5: 0.25, 0.8: 0.75, 0.9: 0.75, 0.95: 0.875}}

In [9]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [10]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [11]:
result

{'cfg': ExperimentConfig(process='annealing_elongation', tag='annealing-schema230726', base_tag=None, target='elongation_final', features=('initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='medium_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=None, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': Path('../../models/annealing_elongation/experiments/annealing-schema230726/annealing-schema230726__78b06c52'),
 'artifacts': {'config': {'process': 'annealing_elongation',
   'tag': 'annealing-schema230726',
   'base_tag': None,
   'target': 'elongation_final',
   'features': ['initial_diameter',
    'tensile_strength',
    'purity',
    'elongation',
    'temperature',
    'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'medium_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': None,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['initial_diameter',
   'tensile_strength',
   'purity',
   'elongation',
   'temperature',
   'time'],
  'target': 'elongation_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1',
   'NeuralNetTorch_BAG_L1',
   'LightGBMLarge_BAG_L1'],
  'weights': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         3.70478714e-08, 0.00000000e+00, 0.00000000e+00, 7.14285771e-01,
         2.85714192e-01]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 1.8418495457694917e-06,
  'variance_floor': 1.8213050370370372,
  'recalibration_c': 2.4098359234622118,
  'ood_ref': {'features': ['initial_diameter',
    'tensile_strength',
    'purity',
    'elongation',
    'temperature',
    'time'],
   'mean': array([  1.38365476, 390.23268763,  99.91890357,   2.45035714,
          576.57142857,  54.64285714]),
   'cov_inv': array([[ 5.81729933e+01, -7.15354564e-02, -2.81831140e+01,
           -1.10827004e+01, -3.38947660e-02,  1.32074019e-02],
          [-7.15354564e-02,  1.24430087e-03,  4.25450647e-01,
            2.53179521e-02,  3.24179302e-06,  2.22091872e-04],
          [-2.81831140e+01,  4.25450647e-01,  4.93891185e+02,
            9.46430250e+00,  7.84990962e-02,  1.11562389e-01],
          [-1.10827004e+01,  2.53179521e-02,  9.46430250e+00,
            2.74869485e+00, -2.14852019e-03,  1.10531214e-02],
          [-3.38947660e-02,  3.24179302e-06,  7.84990962e-02,
           -2.14852019e-03,  4.88686421e-04, -1.36197390e-04],
          [ 1.32074019e-02,  2.22091872e-04,  1.11562389e-01,
            1.10531214e-02, -1.36197390e-04,  1.95954310e-03]]),
   'd_ref': 3.075338042103646,
   'ranges': {'initial_diameter': (1.2, 2.182333333),
    'tensile_strength': (335.21, 431.58),
    'purity': (99.7637, 99.98),
    'elongation': (0.94, 6.02),
    'temperature': (523.0, 723.0),
    'time': (30.0, 90.0)}},
  'y_max': None,
  'y_min': None,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.214286 -0.285714
  1   0.80            0.428571 -0.371429
  2   0.90            0.500000 -0.400000
  3   0.95            0.678571 -0.271429,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.500000  0.000000
  1   0.80            0.821429  0.021429
  2   0.90            0.857143 -0.042857
  3   0.95            0.857143 -0.092857,
  'aleatoric_diagnostics': {'n_total': 28,
   'n_truncated': 7,
   'pct_truncated': 25.0,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 1263.9013434320386,
   'r_tilde_sq_mean': 63.724548003457265,
   'r_tilde_sq_median': 6.525265048393003},
  'metrics': {'rmse': 8.292139291336353,
   'mae': 5.245794353485107,
   'mape': 25.865454014424767,
   'r2': 0.6084882901723389},
  'validation_metrics': {'rmse': 10.597993658519528,
   'mae': 6.547539176124967,
   'mape': 48.52385742130462,
   'r2': 0.43481691755998053,
   'coverage': {0.5: 0.25, 0.8: 0.75, 0.9: 0.75, 0.95: 0.875}},
  'dataset_hash': 'e85dd375'},
 'log_row': {'run_id': 'annealing-schema230726__78b06c52',
  'timestamp': '2026-07-29T16:30:05',
  'elapsed_s': 116.4,
  'n_rows': 28,
  'dataset_hash': 'e85dd375',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_elongation\\experiments\\annealing-schema230726\\annealing-schema230726__78b06c52',
  'cfg_process': 'annealing_elongation',
  'cfg_tag': 'annealing-schema230726',
  'cfg_base_tag': None,
  'cfg_target': 'elongation_final',
  'cfg_features': 'initial_diameter|tensile_strength|purity|elongation|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'medium_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'medium_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': None,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'cfg_group_col': None,
  'rmse': 8.29214,
  'mae': 5.24579,
  'mape': 25.86545,
  'r2': 0.60849,
  'cov_0.5': 0.5,
  'cov_0.8': 0.8214,
  'cov_0.9': 0.8571,
  'cov_0.95': 0.8571,
  'c_opt': 2.4098,
  'pct_truncated_aleat': 25.0,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 1.85944,
  'mean_sigma_aleat': 1.34956,
  'n_val': 8,
  'val_rmse': 10.59799,
  'val_mae': 6.54754,
  'val_mape': 48.52386,
  'val_r2': 0.43482,
  'val_cov_0.5': 0.25,
  'val_cov_0.8': 0.75,
  'val_cov_0.9': 0.75,
  'val_cov_0.95': 0.875},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x22fa30b0c10>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x22faa4c0c10>}

# 6. Grid

Keys are `ExperimentConfig` field names; values are lists of variants.
`features` variants must be tuples. Already-completed runs are skipped
(`force=True` to redo).

In [12]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-07-29 16:30:07,520 | INFO | src.modeling.Experiments | Grid: 4 runs over ['time_limit_a', 'features']
2026-07-29 16:30:07,523 | INFO | src.modeling.Experiments | === Running annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e ===
2026-07-29 16:30:07,524 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       4.93 GB / 31.57 GB (15.6%)
Disk Space Avail:   737.05 GB / 932.08 GB (79.1%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e\model_a"
Train Data Rows:    28
Train Data Columns: 7
Label Column:       elongation_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (61.1, 8.55, 39.1, 13.49557)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4998.38 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 299.96s of the 299.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.32%)
	-14.073	 = Validation score   (-root_mean_squared_error)
	1.35s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 295.33s of the 295.33s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.38%)
	-14.073	 = Validation score   (-root_mean_squared_error)
	1.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 289.89s of the 289.88s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-12.9976	 = Validation score   (-root_mean_squared_error)
	0.53s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 289.24s of the 289.23s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=8.20%)
	-10.7825	 = Validation score   (-root_mean_squared_error)
	1.96s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 283.74s of the 283.73s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-11.606	 = Validation score   (-root_mean_squared_error)
	0.46s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 283.19s of the 283.18s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-14.2106	 = Validation score   (-root_mean_squared_error)
	7.91s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 272.39s of the 272.39s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-10.6001	 = Validation score   (-root_mean_squared_error)
	1.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 267.64s of the 267.64s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-8.4324	 = Validation score   (-root_mean_squared_error)
	7.8s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 256.38s of the 256.38s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.65%)
	-9.1296	 = Validation score   (-root_mean_squared_error)
	1.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.96s of the 251.41s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/4.8 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.714, 'LightGBMLarge_BAG_L1': 0.286}
	-8.2921	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 48.65s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 143.4 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       4.77 GB / 31.57 GB (15.1%)
Disk Space Avail:   737.04 GB / 932.08 GB (79.1%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e\model_b"
Train Data Rows:    28
Train Data Columns: 6
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (7.141958521369611, -13.815510557964274, -1.31122, 7.48011)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5561.16 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 6 | ['initial_diameter', 'tensile_strength', 'purity', 'elongation', 'temperature', ...]
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.97s of the 59.97s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.29%)
	-7.9756	 = Validation score   (-root_mean_squared_error)
	1.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 55.49s of the 55.49s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.33%)
	-7.9756	 = Validation score   (-root_mean_squared_error)
	1.24s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 50.58s of the 50.58s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.8525	 = Validation score   (-root_mean_squared_error)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 49.99s of the 49.99s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.18%)
	-7.5556	 = Validation score   (-root_mean_squared_error)
	7.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 39.34s of the 39.34s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.8003	 = Validation score   (-root_mean_squared_error)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 38.94s of the 38.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-8.0747	 = Validation score   (-root_mean_squared_error)
	9.04s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 26.92s of the 26.92s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-7.3873	 = Validation score   (-root_mean_squared_error)
	1.05s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 22.02s of the 22.02s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-6.5891	 = Validation score   (-root_mean_squared_error)
	7.26s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 11.67s of the 11.67s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.69%)
	-7.0801	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.97s of the 5.28s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/4.3 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.783, 'LightGBMLarge_BAG_L1': 0.174, 'XGBoost_BAG_L1': 0.043}
	-6.5486	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 54.78s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 118.1 rows/s (6 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e\model_b")
2026-07-29 16:31:54,688 | INFO | src.modeling.Experiments | Validation (n=8): rmse=10.5980 mae=6.5475
2026-07-29 16:31:54,732 | INFO | src.modeling.Experiments | Done annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e in 107.2s
2026-07-29 16:31:54,734 | INFO | src.modeling.Experiments | === Running annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4 ===
2026-07-29 16:31:54,734 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       5.04 GB / 31.57 GB (16.0%)
Disk Space Avail:   737.03 GB / 932.08 GB (79.1%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4\model_a"
Train Data Rows:    28
Train Data Columns: 6
Label Column:       elongation_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (61.1, 8.55, 39.1, 13.49557)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5165.72 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['initial_diameter', 'purity', 'elongation', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['initial_diameter', 'purity', 'elongation', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema230726__78b06c52,2026-07-29T16:30:05,116.4,28,e85dd375,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__78b06c52,annealing_elongation,annealing-schema230726,NaN,elongation_final,...,1.34956,8,10.59799,6.54754,48.52386,0.43482,0.25,0.75,0.750,0.875
1,annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e,2026-07-29T16:31:54,107.2,28,e85dd375,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e,annealing_elongation,annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time,annealing-schema230726,elongation_final,...,1.34956,8,10.59799,6.54754,48.52386,0.43482,0.25,0.75,0.750,0.875
2,annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4,2026-07-29T16:33:44,109.4,28,b52f1456,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4,annealing_elongation,annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time,annealing-schema230726,elongation_final,...,1.34956,8,9.34959,5.60851,42.38869,0.56013,0.25,0.75,0.875,0.875
3,annealing-schema230726__time_limit_a=600__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__1bdeffd2,2026-07-29T16:35:29,105.6,28,e85dd375,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=600__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__1bdeffd2,annealing_elongation,annealing-schema230726__time_limit_a=600__features=initial_diameter-tensile_strength-purity-elongation-temperature-time,annealing-schema230726,elongation_final,...,1.34956,8,10.59799,6.54754,48.52386,0.43482,0.25,0.75,0.750,0.875
4,annealing-schema230726__time_limit_a=600__features=initial_diameter-purity-elongation-temperature-time__1718d052,2026-07-29T16:37:10,100.5,28,b52f1456,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_elongation\experiments\annealing-schema230726\annealing-schema230726__time_limit_a=600__features=initial_diameter-purity-elongation-temperature-time__1718d052,annealing_elongation,annealing-schema230726__time_limit_a=600__features=initial_diameter-purity-elongation-temperature-time,annealing-schema230726,elongation_final,...,1.34956,8,9.34959,5.60851,42.38869,0.56013,0.25,0.75,0.875,0.875

# 7. Inspect results

In [14]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_weight_on_essay_rows", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9", "c_opt", "pct_truncated_aleat",
    "mean_sigma_epist", "mean_sigma_aleat", "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_weight_on_essay_rows,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
2,annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4,300,1.0,initial_diameter|purity|elongation|temperature|time,8.00787,4.94571,0.8929,9.34959,5.60851,0.875,2.0930,25.0,2.29640,1.34956,109.4
4,annealing-schema230726__time_limit_a=600__features=initial_diameter-purity-elongation-temperature-time__1718d052,600,1.0,initial_diameter|purity|elongation|temperature|time,8.00787,4.94571,0.8929,9.34959,5.60851,0.875,2.0930,25.0,2.29640,1.34956,100.5
1,annealing-schema230726__time_limit_a=300__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__5528796e,300,1.0,initial_diameter|tensile_strength|purity|elongation|temperature|time,8.29214,5.24579,0.8571,10.59799,6.54754,0.750,2.4098,25.0,1.85944,1.34956,107.2
0,annealing-schema230726__78b06c52,120,1.0,initial_diameter|tensile_strength|purity|elongation|temperature|time,8.29214,5.24579,0.8571,10.59799,6.54754,0.750,2.4098,25.0,1.85944,1.34956,116.4
3,annealing-schema230726__time_limit_a=600__features=initial_diameter-tensile_strength-purity-elongation-temperature-time__1bdeffd2,600,1.0,initial_diameter|tensile_strength|purity|elongation|temperature|time,8.29214,5.24579,0.8571,10.59799,6.54754,0.750,2.4098,25.0,1.85944,1.34956,105.6

In [15]:
# Quick pivot: effect of one knob, marginalised over the others.
# Remember: compare against run-to-run noise (Section 4) before concluding.
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                      rmse                mae           cov_0.9
                      mean       std     mean       std    mean       std
cfg_time_limit_a
120               8.292140       NaN  5.24579       NaN  0.8571       NaN
300               8.150005  0.201009  5.09575  0.212189  0.8750  0.025314
600               8.150005  0.201009  5.09575  0.212189  0.8750  0.025314

# 8. Load a winner for deployment / further analysis

Each run folder is self-contained: predictors + artifacts.pkl with weights,
`recalibration_c`, calibration tables.

In [16]:
# log already carries the resolved absolute path, so use it directly
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema230726__time_limit_a=300__features=initial_diameter-purity-elongation-temperature-time__a850a6c4

   alpha  empirical_coverage       gap
0   0.50            0.607143  0.107143
1   0.80            0.857143  0.057143
2   0.90            0.892857 -0.007143
3   0.95            0.964286  0.014286