**Author**: Felipe Matheus  
**Start Date**: 12/06/2026  
**End Date**: 24/06/2026  
**Purpose**: Experiment launcher ("control panel") for the annealing_iacs surrogate.

This notebook does NOT contain pipeline logic. All the logic (Model A -> OOF ->
NNLS -> Model B -> calibration -> metrics -> persistence) lives in
`src/modeling/Experiments.py`, which orchestrates the existing `Modeling` and
`Evaluation` helpers. Here you only:

1. Load and prepare the data (once).
2. Define a base `ExperimentConfig`.
3. Define the grid of variations you want to sweep.
4. Run and inspect the central `experiments_log.csv`.

Results layout on disk:
```
models/annealing_iacs/experiments/
    experiments_log.csv          <- 1 row per run (the "results spreadsheet")
    <tag>__<hash>/               <- 1 folder per run
        config.yaml
        model_a/   model_b/
        artifacts.pkl
        leaderboard_autogluon.csv
```

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.modeling.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
TARGET = "iacs_final"
ALL_FEATURES = ["purity", "iacs", "temperature", "time"]
PROCESS = "annealing_iacs"

TAG = "annealing-v1-best-quality"
GRID = {
    "time_limit_a": [900, 1500],
    "num_bag_folds_a": [10, 20],
    "weight_on_essay_rows": [1.0, 2.0],
    # "features": [
    #     ("purity", "iacs", "temperature", "time"),
    #     ("iacs", "temperature", "time"),
    # ],
}

# 2. Data (same preparation as annealing_iacs.ipynb, run once)

In [3]:
SCHEMA_DATE = "080626"
FILE_NAME = "dataset_annealing_iacs.csv"
FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{SCHEMA_DATE}.csv"
FILE_NAME_VALIDATION_DATA = "Experimental Results Annealing V2 - CompiledResults.csv"

# ---- Schema (essay) data: explicit is_essay marker ----
df_raw_schema = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
df_schema = df_raw_schema[ALL_FEATURES + [TARGET]].dropna()
df_schema["is_essay"] = True

# ---- Literature data ----
df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
df_float = proc.df_to_float(df_raw, drop_cols=["DOI"], ignore_columns=["material"])
df_labeled = feng.label_element(df_float).drop_duplicates()
df_with_masks = feng.add_ratio_mask_column(
    feng.add_ratio_mask_column(df_labeled, "grain_size"), "iacs",
)
df_lit = df_with_masks[df_with_masks.has_Cu == True][ALL_FEATURES + [TARGET]]
df_lit["is_essay"] = False

# ---- Validation data ----
df_val = proc.load_validation_data_chimie_paris(
    path=os.path.join(varv.PATHS.data_processed, FILE_NAME_VALIDATION_DATA)
)

assert df_lit[ALL_FEATURES + [TARGET]].isna().sum().sum() == 0, "NaNs in inputs"

# ---- Concat. weight_col is built INSIDE the runr from is_essay + config ----
df = pd.concat([df_schema, df_lit], ignore_index=True)
print(f"Dataset: {df.shape} | essays: {df.is_essay.sum()} | lit: {(~df.is_essay).sum()}")
df.head()

Dataset: (96, 6) | essays: 9 | lit: 87

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:37: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(

   purity    iacs  temperature  time  iacs_final  is_essay
0    99.9  88.260        623.0  30.0      88.350      True
1    99.9  88.260        623.0  60.0      88.655      True
2    99.9  88.260        623.0  90.0      88.800      True
3    99.9  99.825        573.0  30.0     102.340      True
4    99.9  99.390        573.0  30.0     102.230      True

# 3. Base config

In [4]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a = "best_quality",
    #     presets_a = "medium_quality"
    #     presets_b = "medium_quality"
    # everything else uses the defaults; override here if needed, e.g.:
    # time_limit_a=120, weight_on_essay_rows=1.0, use_shared_folds=False,
)
print(base.run_id)

annealing-v1-best-quality__9e081980

# 4. Single run (sanity check before any grid)

Always run the base config alone first. Then run it 2-3 more times with
`tag="annealing-v1-rep2"` etc. to measure run-to-run noise: AutoGluon under a
time budget is NOT deterministic, and at n~90 this noise is the floor below
which grid differences mean nothing.

In [5]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-06-25 12:49:54,798 | INFO | src.modeling.Experiments | === Running annealing-v1-best-quality__9e081980 ===
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       7.47 GB / 31.57 GB (23.7%)
Disk Space Avail:   749.92 GB / 932.08 GB (80.5%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__9e081980\model_a"
Train Data Rows:    96
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (105.0, 48.0, 88.90533, 11.88152)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7645.01 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.98s of the 119.97s of remaining time.
2026-06-25 12:49:57,709	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.21%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-7.517	 = Validation score   (-root_mean_squared_error)
	0.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 109.92s of the 109.91s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.27%)
	-6.6733	 = Validation score   (-root_mean_squared_error)
	1.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 105.93s of the 105.92s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.8611	 = Validation score   (-root_mean_squared_error)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 105.28s of the 105.28s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=5.99%)
	-4.2159	 = Validation score   (-root_mean_squared_error)
	37.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 64.14s of the 64.13s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.394	 = Validation score   (-root_mean_squared_error)
	0.37s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 63.70s of the 63.70s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-5.6565	 = Validation score   (-root_mean_squared_error)
	7.63s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 52.62s of the 52.62s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.10%)
	-4.725	 = Validation score   (-root_mean_squared_error)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 47.64s of the 47.64s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.3822	 = Validation score   (-root_mean_squared_error)
	13.83s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 29.85s of the 29.85s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.00%)
	-4.6793	 = Validation score   (-root_mean_squared_error)
	2.62s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 23.09s of the 23.09s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=5.81%)
	-4.4289	 = Validation score   (-root_mean_squared_error)
	18.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.98s of the 0.51s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/6.3 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.32, 'CatBoost_BAG_L1': 0.24, 'ExtraTreesMSE_BAG_L1': 0.2, 'LightGBMLarge_BAG_L1': 0.16, 'NeuralNetFastAI_BAG_L1': 0.08}
	-3.9961	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 119.53s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 173.7 rows/s (20 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__9e081980\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       6.47 GB / 31.57 GB (20.5%)
Disk Space Avail:   749.85 GB / 932.08 GB (80.4%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__9e081980\model_b"
Train Data Rows:    96
Train Data Columns: 4
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (5.517465143812751, -13.815510557964274, -5.92147, 7.77483)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6780.72 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.97s of the 59.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.23%)
	-7.2782	 = Validation score   (-root_mean_squared_error)
	0.96s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 55.44s of the 55.44s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.26%)
	-7.3577	 = Validation score   (-root_mean_squared_error)
	0.82s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 50.55s of the 50.54s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.4488	 = Validation score   (-root_mean_squared_error)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 49.92s of the 49.92s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=5.80%)
	-6.8822	 = Validation score   (-root_mean_squared_error)
	1.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 44.91s of the 44.91s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-7.3162	 = Validation score   (-root_mean_squared_error)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 44.36s of the 44.36s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-7.1313	 = Validation score   (-root_mean_squared_error)
	7.7s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 32.86s of the 32.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.09%)
	-7.3016	 = Validation score   (-root_mean_squared_error)
	0.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 27.71s of the 27.71s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-7.7779	 = Validation score   (-root_mean_squared_error)
	7.55s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 16.42s of the 16.42s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.17%)
	-7.1876	 = Validation score   (-root_mean_squared_error)
	0.98s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.97s of the 11.17s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/6.0 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 0.611, 'NeuralNetFastAI_BAG_L1': 0.278, 'ExtraTreesMSE_BAG_L1': 0.111}
	-6.8099	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 48.89s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 363.3 rows/s (20 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__9e081980\model_b")
2026-06-25 12:52:48,918 | INFO | src.modeling.Experiments | Validation (n=36): rmse=0.7936 mae=0.6656
2026-06-25 12:52:48,960 | INFO | src.modeling.Experiments | Done annealing-v1-best-quality__9e081980 in 174.1s

{'rmse': 3.996119956629481,
 'mae': 2.499519852185059,
 'mape': 3.187536363320045,
 'r2': 0.885691000328722}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

Using `df_schema` as `df_val` is illustrative: those rows are inside the
training data, so val metrics are optimistic. Swap in any held-out
DataFrame with the same columns and nothing else changes.

In [6]:
df_val

,id,purity,initial_diameter,iacs,temperature,time,iacs_final
0,C1_250_30m_T1,99.95,1.2,98.47,523,30,101.08
1,C1_250_30m_T3,99.95,1.2,98.47,523,30,101.08
2,C1_250_60m_T1,99.95,1.2,98.47,523,60,100.82
3,C1_250_60m_T2,99.95,1.2,98.47,523,60,100.82
4,C1_250_90m_T1,99.95,1.2,98.47,523,90,101.22
5,C1_250_90m_T2,99.95,1.2,98.47,523,90,101.22
6,C1_250_30m_AQ_T1,99.95,1.2,98.47,523,30,100.95
7,C1_250_30m_AQ_T2,99.95,1.2,98.47,523,30,100.95
8,C1_300_30m_T1,99.95,1.2,98.47,573,30,102.03
9,C1_300_30m_T2,99.95,1.2,98.47,573,30,102.03
10,C1_300_60m_T1,99.95,1.2,98.47,573,60,101.08
11,C1_300_60m_T2,99.95,1.2,98.47,573,60,101.08
12,C1_300_90m_T1,99.95,1.2,98.47,573,90,101.08
13,C1_300_90m_T2,99.95,1.2,98.47,573,90,101.08
14,C1_350_30m_T1,99.95,1.2,98.47,623,30,100.29
15,C1_350_30m_T2,99.95,1.2,98.47,623,30,100.29
16,C1_350_60m_T1,99.95,1.2,98.47,623,60,100.55
17,C1_350_60m_T2,99.95,1.2,98.47,623,60,100.55
18,C2_250_30m_T1,99.90,1.2,97.71,523,30,100.29
19,C2_250_30m_T2,99.90,1.2,97.71,523,30,100.29
20,C2_250_60m_T1,99.90,1.2,97.71,523,60,100.42
21,C2_250_60m_T2,99.90,1.2,97.71,523,60,100.42
22,C2_250_90m_T1,99.90,1.2,97.71,523,90,100.29
23,C2_250_90m_T2,99.90,1.2,97.71,523,90,100.29
24,C2_300_30m_T1,99.90,1.2,97.71,573,30,101.22
25,C2_300_30m_T2,99.90,1.2,97.71,573,30,101.22
26,C2_300_60m_T1,99.90,1.2,97.71,573,60,101.35
27,C2_300_60m_T2,99.90,1.2,97.71,573,60,101.35
28,C2_300_90m_T1,99.90,1.2,97.71,573,90,101.35
29,C2_300_90m_T2,99.90,1.2,97.71,573,90,101.35
30,C2_350_30m_T1,99.90,1.2,97.71,623,30,100.55
31,C2_350_30m_T2,99.90,1.2,97.71,623,30,100.55
32,C2_350_60m_T1,99.90,1.2,97.71,623,60,100.68
33,C2_350_60m_T2,99.90,1.2,97.71,623,60,100.68
34,C2_350_90m_T1,99.90,1.2,97.71,623,90,100.29
35,C2_350_90m_T2,99.90,1.2,97.71,623,90,100.29

In [7]:
result["artifacts"]["validation_metrics"]

{'rmse': 0.7936130294660075,
 'mae': 0.6655881888544484,
 'mape': 0.6596575497019923,
 'r2': -1.847867144716632,
 'coverage': {0.5: 1.0, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}}

In [8]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [9]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [10]:
result

{'cfg': ExperimentConfig(process='annealing_iacs', tag='annealing-v1-best-quality', base_tag=None, target='iacs_final', features=('purity', 'iacs', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=None, fold_seed=42, use_shared_folds=False),
 'run_dir': Path('../../models/annealing_iacs/experiments/annealing-v1-best-quality/annealing-v1-best-quality__9e081980'),
 'artifacts': {'config': {'process': 'annealing_iacs',
   'tag': 'annealing-v1-best-quality',
   'base_tag': None,
   'target': 'iacs_final',
   'features': ['purity', 'iacs', 'temperature', 'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': None,
   'fold_seed': 42,
   'use_shared_folds': False},
  'features': ['purity', 'iacs', 'temperature', 'time'],
  'target': 'iacs_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1',
   'NeuralNetTorch_BAG_L1',
   'LightGBMLarge_BAG_L1',
   'CatBoost_r177_BAG_L1'],
  'weights': array([0.00000000e+00, 0.00000000e+00, 1.77032630e-07, 2.40000207e-01,
         1.99999750e-01, 8.00000322e-02, 0.00000000e+00, 3.19999912e-01,
         1.59999922e-01, 0.00000000e+00]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 4.2170700425003815e-06,
  'variance_floor': 1.4117059220871857,
  'recalibration_c': 1.4248682488330702,
  'ood_ref': {'features': ['purity', 'iacs', 'temperature', 'time'],
   'mean': array([ 99.51208333,  79.40192708, 584.375     ,  69.6875    ]),
   'cov_inv': array([[ 2.48657388e-01,  8.49690036e-04,  8.68909859e-04,
           -1.36427867e-04],
          [ 8.49690036e-04,  3.69548473e-03,  1.56791026e-04,
           -6.86741096e-05],
          [ 8.68909859e-04,  1.56791026e-04,  9.65665002e-05,
            3.06288557e-06],
          [-1.36427867e-04, -6.86741096e-05,  3.06288557e-06,
            1.07676333e-04]]),
   'd_ref': 2.881983654169966,
   'ranges': {'purity': (80.0, 99.98),
    'iacs': (36.0, 100.25),
    'temperature': (373.0, 873.0),
    'time': (30.0, 600.0)}},
  'y_max': None,
  'y_min': None,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.458333 -0.041667
  1   0.80            0.708333 -0.091667
  2   0.90            0.812500 -0.087500
  3   0.95            0.854167 -0.095833,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.635417  0.135417
  1   0.80            0.833333  0.033333
  2   0.90            0.906250  0.006250
  3   0.95            0.947917 -0.002083,
  'aleatoric_diagnostics': {'n_total': 96,
   'n_truncated': 46,
   'pct_truncated': 47.916666666666664,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 249.0030486083374,
   'r_tilde_sq_mean': 12.368657067648073,
   'r_tilde_sq_median': 0.0940765467279284},
  'metrics': {'rmse': 3.996119956629481,
   'mae': 2.499519852185059,
   'mape': 3.187536363320045,
   'r2': 0.885691000328722},
  'validation_metrics': {'rmse': 0.7936130294660075,
   'mae': 0.6655881888544484,
   'mape': 0.6596575497019923,
   'r2': -1.847867144716632,
   'coverage': {0.5: 1.0, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}},
  'dataset_hash': '318f1408'},
 'log_row': {'run_id': 'annealing-v1-best-quality__9e081980',
  'timestamp': '2026-06-25T12:52:48',
  'elapsed_s': 174.1,
  'n_rows': 96,
  'dataset_hash': '318f1408',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_iacs\\experiments\\annealing-v1-best-quality\\annealing-v1-best-quality__9e081980',
  'cfg_process': 'annealing_iacs',
  'cfg_tag': 'annealing-v1-best-quality',
  'cfg_base_tag': None,
  'cfg_target': 'iacs_final',
  'cfg_features': 'purity|iacs|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'medium_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': None,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'rmse': 3.99612,
  'mae': 2.49952,
  'mape': 3.18754,
  'r2': 0.88569,
  'cov_0.5': 0.6354,
  'cov_0.8': 0.8333,
  'cov_0.9': 0.9062,
  'cov_0.95': 0.9479,
  'c_opt': 1.4249,
  'pct_truncated_aleat': 47.92,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 1.67132,
  'mean_sigma_aleat': 1.19368,
  'n_val': 36,
  'val_rmse': 0.79361,
  'val_mae': 0.66559,
  'val_mape': 0.65966,
  'val_r2': -1.84787,
  'val_cov_0.5': 1.0,
  'val_cov_0.8': 1.0,
  'val_cov_0.9': 1.0,
  'val_cov_0.95': 1.0},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x214db1f5050>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x214e3d27850>}

# 6. Grid

Keys are `ExperimentConfig` field names; values are lists of variants.
`features` variants must be tuples. Already-completed runs are skipped
(`force=True` to redo).

In [11]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-06-25 12:52:51,140 | INFO | src.modeling.Experiments | Grid: 8 runs over ['time_limit_a', 'num_bag_folds_a', 'weight_on_essay_rows']
2026-06-25 12:52:51,142 | INFO | src.modeling.Experiments | === Running annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0__b2cc9ca8 ===
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       6.55 GB / 31.57 GB (20.8%)
Disk Space Avail:   749.83 GB / 932.08 GB (80.4%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=10, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0__b2cc9ca8\model_a"
Train Data Rows:    96
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (105.0, 48.0, 88.90533, 11.88152)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6706.14 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 899.96s of the 899.95s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.23%)
	-4.9654	 = Validation score   (-root_mean_squared_error)
	5.21s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 889.32s of the 889.31s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.25%)
	-4.3711	 = Validation score   (-root_mean_squared_error)
	4.71s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 879.18s of the 879.17s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.8611	 = Validation score   (-root_mean_squared_error)
	0.43s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 878.65s of the 878.64s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.02%)
	-3.6894	 = Validation score   (-root_mean_squared_error)
	49.9s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 823.65s of the 823.64s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.394	 = Validation score   (-root_mean_squared_error)
	0.44s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 823.08s of the 823.08s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.8589	 = Validation score   (-root_mean_squared_error)
	18.31s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 799.61s of the 799.60s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.08%)
	-4.2091	 = Validation score   (-root_mean_squared_error)
	3.61s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 790.47s of the 790.47s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-3.9543	 = Validation score   (-root_mean_squared_error)
	21.69s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 763.37s of the 763.36s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=1.13%)
	-3.9481	 = Validation score   (-root_mean_squared_error)
	5.3s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 752.40s of the 752.39s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.14%)
	-3.7609	 = Validation score   (-root_mean_squared_error)
	51.01s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 695.95s of the 695.94s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.5604	 = Validation score   (-root_mean_squared_error)
	19.23s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 671.51s of the 671.50s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.43%)
	-4.8278	 = Validation score   (-root_mean_squared_error)
	4.99s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 661.23s of the 661.22s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.1411	 = Validation score   (-root_mean_squared_error)
	19.92s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 636.16s of the 636.15s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.28%)
	-3.7054	 = Validation score   (-root_mean_squared_error)
	28.37s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 602.43s of the 602.42s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.12%)
	-11.9194	 = Validation score   (-root_mean_squared_error)
	4.36s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 593.01s of the 593.00s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.1498	 = Validation score   (-root_mean_squared_error)
	19.95s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 567.77s of the 567.77s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.32%)
	-4.2285	 = Validation score   (-root_mean_squared_error)
	6.34s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 555.97s of the 555.96s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.3022	 = Validation score   (-root_mean_squared_error)
	0.36s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 555.54s of the 555.53s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=5.63%)
	-3.6872	 = Validation score   (-root_mean_squared_error)
	64.29s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 486.18s of the 486.17s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.7106	 = Validation score   (-root_mean_squared_error)
	18.64s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 462.18s of the 462.17s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.21%)
	-3.9923	 = Validation score   (-root_mean_squared_error)
	67.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 389.35s of the 389.35s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-4.4758	 = Validation score   (-root_mean_squared_error)
	0.59s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 388.68s of the 388.68s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.90%)
	-3.9014	 = Validation score   (-root_mean_squared_error)
	5.1s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 378.55s of the 378.54s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-5.1934	 = Validation score   (-root_mean_squared_error)
	19.19s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 354.12s of the 354.11s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.07%)
	-4.0704	 = Validation score   (-root_mean_squared_error)
	4.28s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 344.51s of the 344.50s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-3.6654	 = Validation score   (-root_mean_squared_error)
	20.22s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 319.11s of the 319.10s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.67%)
	-11.9194	 = Validation score   (-root_mean_squared_error)
	4.32s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 309.72s of the 309.71s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-3.3347	 = Validation score   (-root_mean_squared_error)
	21.49s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 282.90s of the 282.89s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=5.96%)
	-3.5569	 = Validation score   (-root_mean_squared_error)
	63.73s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 213.94s of the 213.93s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-7.417	 = Validation score   (-root_mean_squared_error)
	19.13s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 189.58s of the 189.57s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.12%)
	-4.1224	 = Validation score   (-root_mean_squared_error)
	4.01s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 180.29s of the 180.28s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-6.4779	 = Validation score   (-root_mean_squared_error)
	0.36s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 179.82s of the 179.81s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=5.94%)
	-3.7533	 = Validation score   (-root_mean_squared_error)
	52.32s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 122.13s of the 122.12s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.8577	 = Validation score   (-root_mean_squared_error)
	18.92s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 97.93s of the 97.93s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.9053	 = Validation score   (-root_mean_squared_error)
	19.54s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 72.97s of the 72.97s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=2.09%)
	-4.5807	 = Validation score   (-root_mean_squared_error)
	5.76s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 61.92s of the 61.92s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	-5.1103	 = Validation score   (-root_mean_squared_error)
	19.14s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 37.59s of the 37.58s of remaining time.
	Fitting 10 child models (S1F1 - S1F10) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=6.37%)
	-3.691	 = Validation score   (-root_mean_squared_error)
	15.35s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r156_BAG_L1 ... Training model for up to 16.78s of the 16.78s of remaining time.

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-v1-best-quality__9e081980,2026-06-25T12:52:48,174.1,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__9e081980,annealing_iacs,annealing-v1-best-quality,NaN,iacs_final,...,1.19368,36,0.79361,0.66559,0.65966,-1.84787,1.0000,1.0000,1.0,1.0
1,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0__b2cc9ca8,2026-06-25T13:09:05,974.4,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0__b2cc9ca8,annealing_iacs,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0,annealing-v1-best-quality,iacs_final,...,1.18815,36,1.64868,1.26852,1.25711,-11.29061,0.6111,0.9444,1.0,1.0
2,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=2.0__c6973299,2026-06-25T13:32:20,1394.8,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=2.0__c6973299,annealing_iacs,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=2.0,annealing-v1-best-quality,iacs_final,...,1.19206,36,1.69936,1.32685,1.31487,-12.05786,0.6667,0.9444,1.0,1.0
3,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=1.0__b00d83ba,2026-06-25T13:48:19,959.4,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=1.0__b00d83ba,annealing_iacs,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=1.0,annealing-v1-best-quality,iacs_final,...,1.18815,36,1.45122,1.17272,1.16195,-8.52294,0.7222,1.0000,1.0,1.0
4,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=2.0__c2faef57,2026-06-25T14:04:42,982.3,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=2.0__c2faef57,annealing_iacs,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=2.0,annealing-v1-best-quality,iacs_final,...,1.18815,36,0.68192,0.57464,0.56989,-1.10266,0.9444,1.0000,1.0,1.0
5,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=1.0__58129934,2026-06-25T14:30:47,1564.9,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=1.0__58129934,annealing_iacs,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=1.0,annealing-v1-best-quality,iacs_final,...,1.20936,36,1.10730,0.90545,0.89713,-4.54416,0.7778,1.0000,1.0,1.0
6,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=2.0__a960fe25,2026-06-25T14:56:50,1563.5,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=2.0__a960fe25,annealing_iacs,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=2.0,annealing-v1-best-quality,iacs_final,...,1.20591,36,1.24997,0.97162,0.96267,-6.06481,0.7778,1.0000,1.0,1.0
7,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29,2026-06-25T15:31:06,2055.6,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29,annealing_iacs,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0,annealing-v1-best-quality,iacs_final,...,1.19315,36,1.83345,1.46938,1.45575,-14.19992,0.3333,0.8333,1.0,1.0
8,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=2.0__09e4459d,2026-06-25T16:05:11,2045.3,96,318f1408,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-v1-best-quality\annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=2.0__09e4459d,annealing_iacs,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=2.0,annealing-v1-best-quality,iacs_final,...,1.20141,36,1.82811,1.45586,1.44247,-14.11146,0.5000,0.8333,1.0,1.0

In [12]:
# import pickle
# from pathlib import Path
# import pandas as pd

# exp_dir = Path("../../models/annealing_iacs/experiments")
# rows = []
# for run_path in exp_dir.iterdir():
#     pkl = run_path / "artifacts.pkl"
#     if not pkl.exists():
#         continue
#     with open(pkl, "rb") as f:
#         art = pickle.load(f)
#     row = {"run_id": run_path.name}
#     row.update({f"cfg_{k}": v for k, v in art["config"].items()})
#     m = dict(art["metrics"]); m.pop("coverage", None)
#     row.update({k: v for k, v in m.items()})
#     cov = art["metrics"].get("coverage", {})
#     row.update({f"cov_{a}": c for a, c in cov.items()})
#     row["c_opt"] = art["recalibration_c"]
#     if art.get("validation_metrics"):
#         vm = dict(art["validation_metrics"]); vcov = vm.pop("coverage", {})
#         row.update({f"val_{k}": v for k, v in vm.items()})
#         row.update({f"val_cov_{a}": c for a, c in vcov.items()})
#     row["cfg_features"] = "|".join(art["features"])
#     rows.append(row)

# pd.DataFrame(rows).to_csv(exp_dir / "experiments_log.csv", index=False)
# print(f"Rebuilt log with {len(rows)} runs")

# 7. Inspect results

In [13]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_weight_on_essay_rows", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9", "c_opt", "pct_truncated_aleat",
    "mean_sigma_epist", "mean_sigma_aleat", "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_weight_on_essay_rows,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
7,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29,1500,1.0,purity|iacs|temperature|time,2.46436,1.60750,0.8958,1.83345,1.46938,1.0,1.0902,45.83,1.20462,1.19315,2055.6
8,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=2.0__09e4459d,1500,2.0,purity|iacs|temperature|time,2.48332,1.64380,0.8958,1.82811,1.45586,1.0,1.1735,45.83,1.21766,1.20141,2045.3
4,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=2.0__c2faef57,900,2.0,purity|iacs|temperature|time,2.72366,1.82545,0.8958,0.68192,0.57464,1.0,1.4165,46.88,1.43081,1.18815,982.3
5,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=1.0__58129934,1500,1.0,purity|iacs|temperature|time,2.87629,1.90605,0.8854,1.10730,0.90545,1.0,1.4549,42.71,1.22487,1.20936,1564.9
6,annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=10__weight_on_essay_rows=2.0__a960fe25,1500,2.0,purity|iacs|temperature|time,2.88314,1.93602,0.8958,1.24997,0.97162,1.0,1.6562,40.62,1.17776,1.20591,1563.5
3,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=20__weight_on_essay_rows=1.0__b00d83ba,900,1.0,purity|iacs|temperature|time,2.94994,1.80882,0.9062,1.45122,1.17272,1.0,1.3767,59.38,1.37775,1.18815,959.4
2,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=2.0__c6973299,900,2.0,purity|iacs|temperature|time,3.03089,2.01250,0.8958,1.69936,1.32685,1.0,1.2695,55.21,1.70622,1.19206,1394.8
1,annealing-v1-best-quality__time_limit_a=900__num_bag_folds_a=10__weight_on_essay_rows=1.0__b2cc9ca8,900,1.0,purity|iacs|temperature|time,3.03709,1.99517,0.8854,1.64868,1.26852,1.0,1.2320,46.88,1.55804,1.18815,974.4
0,annealing-v1-best-quality__9e081980,120,1.0,purity|iacs|temperature|time,3.99612,2.49952,0.9062,0.79361,0.66559,1.0,1.4249,47.92,1.67132,1.19368,174.1

In [14]:
# Quick pivot: effect of one knob, marginalised over the others.
# Remember: compare against run-to-run noise (Section 4) before concluding.
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                      rmse                 mae           cov_0.9
                      mean       std      mean       std    mean       std
cfg_time_limit_a
120               3.996120       NaN  2.499520       NaN  0.9062       NaN
900               2.935395  0.146634  1.910485  0.108236  0.8958  0.008492
1500              2.676778  0.234477  1.773343  0.171620  0.8932  0.005200

# 8. Load a winner for deployment / further analysis

Each run folder is self-contained: predictors + artifacts.pkl with weights,
`recalibration_c`, calibration tables.

In [15]:
# log already carries the resolved absolute path, so use it directly
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29

   alpha  empirical_coverage       gap
0   0.50            0.625000  0.125000
1   0.80            0.812500  0.012500
2   0.90            0.895833 -0.004167
3   0.95            0.916667 -0.033333

In [19]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-v1-best-quality/annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29')

In [17]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-v1-best-quality/annealing-v1-best-quality__time_limit_a=1500__num_bag_folds_a=20__weight_on_essay_rows=1.0__d91e7f29')