**Author**: Felipe Matheus  
**Start Date**: 12/06/2026  
**End Date**: 24/06/2026  
**Purpose**: Experiment launcher ("control panel") for the annealing_iacs surrogate.

This notebook does NOT contain pipeline logic. All the logic (Model A -> OOF ->
NNLS -> Model B -> calibration -> metrics -> persistence) lives in
`src/modeling/Experiments.py`, which orchestrates the existing `Modeling` and
`Evaluation` helpers. Here you only:

1. Load and prepare the data (once).
2. Define a base `ExperimentConfig`.
3. Define the grid of variations you want to sweep.
4. Run and inspect the central `experiments_log.csv`.

Results layout on disk:
```
models/annealing_iacs/experiments/
    experiments_log.csv          <- 1 row per run (the "results spreadsheet")
    <tag>__<hash>/               <- 1 folder per run
        config.yaml
        model_a/   model_b/
        artifacts.pkl
        leaderboard_autogluon.csv
```

# 1. Setup

In [2]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
TARGET = "iacs_final"
ALL_FEATURES = ["purity", "iacs", "temperature", "time"]
PROCESS = "annealing_iacs"

SCHEMA_DATE = "110826"
FILE_NAME_SCHEMA_DATA = "schema_annealing_essays_{}.csv".format(SCHEMA_DATE)
FILE_NAME_VALIDATION_DATA = "Experimental Results Annealing V2 - CompiledResults.csv"

TAG = f"annealing-schema{SCHEMA_DATE}"
GRID = {
    "time_limit_a": [900, 600],
    # "num_bag_folds_a": [10, 20],
    # "weight_on_essay_rows": [2.0],
    # "features": [
    #     ("purity", "iacs", "temperature", "time"),
    #     ("iacs", "temperature", "time"),
    # ],
}

# 2. Data (same preparation as annealing_iacs.ipynb, run once)

In [4]:
df, df_val = proc.process_annealing_iacs(
    features=ALL_FEATURES,
    target=TARGET,
    df_schema=pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA)),
    df_val = proc.load_validation_data_chimie_paris(
        path=os.path.join(varv.PATHS.data_processed, FILE_NAME_VALIDATION_DATA)
)
)

In [5]:
# SCHEMA_DATE = "080626"
# FILE_NAME = "dataset_annealing_iacs.csv"
# FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{SCHEMA_DATE}.csv"
# FILE_NAME_VALIDATION_DATA = "Experimental Results Annealing V2 - CompiledResults.csv"

# # ---- Schema (essay) data: explicit is_essay marker ----
# df_raw_schema = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA))
# df_schema = df_raw_schema[ALL_FEATURES + [TARGET]].dropna()
# df_schema["is_essay"] = True

# # ---- Literature data ----
# df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
# df_float = proc.df_to_float(df_raw, drop_cols=["DOI"], ignore_columns=["material"])
# df_labeled = feng.label_element(df_float).drop_duplicates()
# df_with_masks = feng.add_ratio_mask_column(
#     feng.add_ratio_mask_column(df_labeled, "grain_size"), "iacs",
# )
# df_lit = df_with_masks[df_with_masks.has_Cu == True][ALL_FEATURES + [TARGET]]
# df_lit["is_essay"] = False

# # ---- Validation data ----
# df_val = proc.load_validation_data_chimie_paris(
#     path=os.path.join(varv.PATHS.data_processed, FILE_NAME_VALIDATION_DATA)
# )

# assert df_lit[ALL_FEATURES + [TARGET]].isna().sum().sum() == 0, "NaNs in inputs"

# # ---- Concat. weight_col is built INSIDE the runr from is_essay + config ----
# df = pd.concat([df_schema, df_lit], ignore_index=True)
# print(f"Dataset: {df.shape} | essays: {df.is_essay.sum()} | lit: {(~df.is_essay).sum()}")
# df.head()

# 3. Base config

In [6]:
df = df[df.iacs > 90]

In [7]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a = "best_quality",
    #     presets_a = "medium_quality"
    #     presets_b = "medium_quality"
    # everything else uses the defaults; override here if needed, e.g.:
    # time_limit_a=120, weight_on_essay_rows=1.0, use_shared_folds=False,
)
print(base.run_id)

annealing-schema110826__bd1b73d5

# 4. Single run (sanity check before any grid)

Always run the base config alone first. Then run it 2-3 more times with
`tag="annealing-v1-rep2"` etc. to measure run-to-run noise: AutoGluon under a
time budget is NOT deterministic, and at n~90 this noise is the floor below
which grid differences mean nothing.

In [8]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-08-12 11:39:17,047 | INFO | src.modeling.Experiments | === Running annealing-schema110826__bd1b73d5 ===
2026-08-12 11:39:17,047 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.49 GB / 31.57 GB (11.1%)
Disk Space Avail:   699.22 GB / 932.08 GB (75.0%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__bd1b73d5\model_a"
Train Data Rows:    39
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (104.865, 98.355, 101.56697, 1.92333)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3575.29 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.94s of the 119.92s of remaining time.
2026-08-12 11:39:27,150	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.43%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-1.9246	 = Validation score   (-root_mean_squared_error)
	1.31s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 96.97s of the 96.95s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.77%)
	-1.9246	 = Validation score   (-root_mean_squared_error)
	6.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 87.32s of the 87.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0237	 = Validation score   (-root_mean_squared_error)
	1.49s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 85.69s of the 85.66s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=12.64%)
	-0.9908	 = Validation score   (-root_mean_squared_error)
	6.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 74.39s of the 74.37s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0145	 = Validation score   (-root_mean_squared_error)
	0.6s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 73.65s of the 73.63s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.8431	 = Validation score   (-root_mean_squared_error)
	20.15s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 49.62s of the 49.60s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.20%)
	-1.0998	 = Validation score   (-root_mean_squared_error)
	4.17s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 42.40s of the 42.38s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.4255	 = Validation score   (-root_mean_squared_error)
	20.83s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 16.93s of the 16.91s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=2.43%)
	-1.0748	 = Validation score   (-root_mean_squared_error)
	4.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 9.90s of the 9.88s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=13.83%)
	-1.0002	 = Validation score   (-root_mean_squared_error)
	6.75s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.94s of the -1.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/2.7 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 0.636, 'RandomForestMSE_BAG_L1': 0.364}
	-0.9742	 = Validation score   (-root_mean_squared_error)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 121.37s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 270.7 rows/s (8 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__bd1b73d5\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       2.89 GB / 31.57 GB (9.2%)
Disk Space Avail:   699.24 GB / 932.08 GB (75.0%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__bd1b73d5\model_b"
Train Data Rows:    39
Train Data Columns: 4
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1.7707554100785554, -13.815510557964274, -2.44719, 4.58243)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2969.79 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.93s of the 59.93s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.52%)
	-4.6788	 = Validation score   (-root_mean_squared_error)
	5.73s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 51.50s of the 51.49s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.63%)
	-4.6788	 = Validation score   (-root_mean_squared_error)
	4.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 42.99s of the 42.99s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-5.5359	 = Validation score   (-root_mean_squared_error)
	0.63s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 42.23s of the 42.22s of remaining time.
	Memory not enough to fit 5 folds in parallel. Will train 4 folds in parallel instead (Estimated 16.03% memory usage per fold, 64.12%/80.00% total).
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=2, gpus=0, memory=16.03%)
	-4.6221	 = Validation score   (-root_mean_squared_error)
	6.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 33.39s of the 33.38s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-5.3713	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 32.58s of the 32.58s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-4.5878	 = Validation score   (-root_mean_squared_error)
	15.67s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 12.36s of the 12.35s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.56%)
	-4.7028	 = Validation score   (-root_mean_squared_error)
	5.79s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 2.25s of the 2.25s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.93s of the -432.99s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/6.9 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.625, 'CatBoost_BAG_L1': 0.375}
	-4.5689	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 493.07s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 68.8 rows/s (8 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__bd1b73d5\model_b")
2026-08-12 11:49:45,159 | INFO | src.modeling.Experiments | Validation (n=36): rmse=0.4815 mae=0.3745
2026-08-12 11:49:45,211 | INFO | src.modeling.Experiments | Done annealing-schema110826__bd1b73d5 in 628.1s

{'rmse': 0.9742241447184035,
 'mae': 0.7752511640299472,
 'mape': 0.7646024881594429,
 'r2': 0.7366766023765559}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

Using `df_schema` as `df_val` is illustrative: those rows are inside the
training data, so val metrics are optimistic. Swap in any held-out
DataFrame with the same columns and nothing else changes.

In [9]:
df_val

,id,purity,initial_diameter,iacs,temperature,time,iacs_final
0,C1_250_30m_T1,99.95,1.2,98.47,523,30,101.08
1,C1_250_30m_T3,99.95,1.2,98.47,523,30,101.08
2,C1_250_60m_T1,99.95,1.2,98.47,523,60,100.82
3,C1_250_60m_T2,99.95,1.2,98.47,523,60,100.82
4,C1_250_90m_T1,99.95,1.2,98.47,523,90,101.22
5,C1_250_90m_T2,99.95,1.2,98.47,523,90,101.22
6,C1_250_30m_AQ_T1,99.95,1.2,98.47,523,30,100.95
7,C1_250_30m_AQ_T2,99.95,1.2,98.47,523,30,100.95
8,C1_300_30m_T1,99.95,1.2,98.47,573,30,102.03
9,C1_300_30m_T2,99.95,1.2,98.47,573,30,102.03
10,C1_300_60m_T1,99.95,1.2,98.47,573,60,101.08
11,C1_300_60m_T2,99.95,1.2,98.47,573,60,101.08
12,C1_300_90m_T1,99.95,1.2,98.47,573,90,101.08
13,C1_300_90m_T2,99.95,1.2,98.47,573,90,101.08
14,C1_350_30m_T1,99.95,1.2,98.47,623,30,100.29
15,C1_350_30m_T2,99.95,1.2,98.47,623,30,100.29
16,C1_350_60m_T1,99.95,1.2,98.47,623,60,100.55
17,C1_350_60m_T2,99.95,1.2,98.47,623,60,100.55
18,C2_250_30m_T1,99.90,1.2,97.71,523,30,100.29
19,C2_250_30m_T2,99.90,1.2,97.71,523,30,100.29
20,C2_250_60m_T1,99.90,1.2,97.71,523,60,100.42
21,C2_250_60m_T2,99.90,1.2,97.71,523,60,100.42
22,C2_250_90m_T1,99.90,1.2,97.71,523,90,100.29
23,C2_250_90m_T2,99.90,1.2,97.71,523,90,100.29
24,C2_300_30m_T1,99.90,1.2,97.71,573,30,101.22
25,C2_300_30m_T2,99.90,1.2,97.71,573,30,101.22
26,C2_300_60m_T1,99.90,1.2,97.71,573,60,101.35
27,C2_300_60m_T2,99.90,1.2,97.71,573,60,101.35
28,C2_300_90m_T1,99.90,1.2,97.71,573,90,101.35
29,C2_300_90m_T2,99.90,1.2,97.71,573,90,101.35
30,C2_350_30m_T1,99.90,1.2,97.71,623,30,100.55
31,C2_350_30m_T2,99.90,1.2,97.71,623,30,100.55
32,C2_350_60m_T1,99.90,1.2,97.71,623,60,100.68
33,C2_350_60m_T2,99.90,1.2,97.71,623,60,100.68
34,C2_350_90m_T1,99.90,1.2,97.71,623,90,100.29
35,C2_350_90m_T2,99.90,1.2,97.71,623,90,100.29

In [10]:
result["artifacts"]["validation_metrics"]

{'rmse': 0.48151312308318656,
 'mae': 0.37447404691282,
 'mape': 0.37041232389831374,
 'r2': -0.048379214887428024,
 'coverage': {0.5: 0.8888888888888888,
  0.8: 0.9444444444444444,
  0.9: 0.9444444444444444,
  0.95: 0.9444444444444444}}

In [11]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [12]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [13]:
result

{'cfg': ExperimentConfig(process='annealing_iacs', tag='annealing-schema110826', base_tag=None, target='iacs_final', features=('purity', 'iacs', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=None, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': Path('../../models/annealing_iacs/experiments/annealing-schema110826/annealing-schema110826__bd1b73d5'),
 'artifacts': {'config': {'process': 'annealing_iacs',
   'tag': 'annealing-schema110826',
   'base_tag': None,
   'target': 'iacs_final',
   'features': ['purity', 'iacs', 'temperature', 'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': None,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['purity', 'iacs', 'temperature', 'time'],
  'target': 'iacs_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1',
   'NeuralNetTorch_BAG_L1',
   'LightGBMLarge_BAG_L1',
   'CatBoost_r177_BAG_L1'],
  'weights': array([0.00000000e+00, 0.00000000e+00, 3.63636123e-01, 6.36361403e-01,
         0.00000000e+00, 0.00000000e+00, 1.07284473e-06, 0.00000000e+00,
         0.00000000e+00, 1.40067700e-06]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 3.650784080377889e-06,
  'variance_floor': 0.03699212992565972,
  'recalibration_c': 2.0450890592840136,
  'ood_ref': {'features': ['purity', 'iacs', 'temperature', 'time'],
   'mean': array([ 99.92875128,  99.26974359, 608.        ,  48.21794872]),
   'cov_inv': array([[ 2.48322031e+02, -2.54602810e+00, -4.93833765e-02,
            5.09155411e-02],
          [-2.54602810e+00,  3.54651239e-01,  3.89626701e-03,
           -1.46078693e-03],
          [-4.93833765e-02,  3.89626701e-03,  1.74013178e-04,
            1.51956563e-04],
          [ 5.09155411e-02, -1.46078693e-03,  1.51956563e-04,
            1.88459426e-03]]),
   'd_ref': 2.899551459309719,
   'ranges': {'purity': (99.7637, 99.98),
    'iacs': (96.835, 102.7),
    'temperature': (523.0, 873.0),
    'time': (0.5, 90.0)}},
  'y_max': None,
  'y_min': None,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.153846 -0.346154
  1   0.80            0.410256 -0.389744
  2   0.90            0.564103 -0.335897
  3   0.95            0.717949 -0.232051,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.435897 -0.064103
  1   0.80            0.846154  0.046154
  2   0.90            0.871795 -0.028205
  3   0.95            0.871795 -0.078205,
  'aleatoric_diagnostics': {'n_total': 39,
   'n_truncated': 5,
   'pct_truncated': 12.820512820512821,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 5.87528893868814,
   'r_tilde_sq_mean': 0.8945878984690301,
   'r_tilde_sq_median': 0.3467814176913541},
  'metrics': {'rmse': 0.9742241447184035,
   'mae': 0.7752511640299472,
   'mape': 0.7646024881594429,
   'r2': 0.7366766023765559},
  'validation_metrics': {'rmse': 0.48151312308318656,
   'mae': 0.37447404691282,
   'mape': 0.37041232389831374,
   'r2': -0.048379214887428024,
   'coverage': {0.5: 0.8888888888888888,
    0.8: 0.9444444444444444,
    0.9: 0.9444444444444444,
    0.95: 0.9444444444444444}},
  'dataset_hash': 'd90e3228'},
 'log_row': {'run_id': 'annealing-schema110826__bd1b73d5',
  'timestamp': '2026-08-12T11:49:45',
  'elapsed_s': 628.1,
  'n_rows': 39,
  'dataset_hash': 'd90e3228',
  'model_dir': 'C:\\Users\\fmfoa\\Projects\\uncertainty-aware-predictors\\models\\annealing_iacs\\experiments\\annealing-schema110826\\annealing-schema110826__bd1b73d5',
  'cfg_process': 'annealing_iacs',
  'cfg_tag': 'annealing-schema110826',
  'cfg_base_tag': None,
  'cfg_target': 'iacs_final',
  'cfg_features': 'purity|iacs|temperature|time',
  'cfg_weight_on_essay_rows': 1.0,
  'cfg_presets_a': 'best_quality',
  'cfg_num_bag_folds_a': 5,
  'cfg_num_bag_sets_a': 1,
  'cfg_num_stack_levels_a': 0,
  'cfg_time_limit_a': 120,
  'cfg_presets_b': 'medium_quality',
  'cfg_num_bag_folds_b': 5,
  'cfg_num_stack_levels_b': 0,
  'cfg_time_limit_b': 60,
  'cfg_use_weighted_variance': True,
  'cfg_variance_floor_frac': 0.01,
  'cfg_recalibration_target_alpha': 0.9,
  'cfg_calibration_alphas': [0.5, 0.8, 0.9, 0.95],
  'cfg_y_max': None,
  'cfg_y_min': None,
  'cfg_fold_seed': 42,
  'cfg_use_shared_folds': False,
  'cfg_group_col': None,
  'rmse': 0.97422,
  'mae': 0.77525,
  'mape': 0.7646,
  'r2': 0.73668,
  'cov_0.5': 0.4359,
  'cov_0.8': 0.8462,
  'cov_0.9': 0.8718,
  'cov_0.95': 0.8718,
  'c_opt': 2.0451,
  'pct_truncated_aleat': 12.82,
  'nnls_recovery_ok': True,
  'mean_sigma_epist': 0.19849,
  'mean_sigma_aleat': 0.32888,
  'n_val': 36,
  'val_rmse': 0.48151,
  'val_mae': 0.37447,
  'val_mape': 0.37041,
  'val_r2': -0.04838,
  'val_cov_0.5': 0.8889,
  'val_cov_0.8': 0.9444,
  'val_cov_0.9': 0.9444,
  'val_cov_0.95': 0.9444},
 'predictor_a': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x27f084c4850>,
 'predictor_b': <autogluon.tabular.predictor.predictor.TabularPredictor at 0x27f0f973490>}

# 6. Grid

Keys are `ExperimentConfig` field names; values are lists of variants.
`features` variants must be tuples. Already-completed runs are skipped
(`force=True` to redo).

In [14]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-08-12 11:49:47,486 | INFO | src.modeling.Experiments | Grid: 2 runs over ['time_limit_a']
2026-08-12 11:49:47,488 | INFO | src.modeling.Experiments | === Running annealing-schema110826__time_limit_a=900__e98488a7 ===
2026-08-12 11:49:47,489 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       5.65 GB / 31.57 GB (17.9%)
Disk Space Avail:   681.48 GB / 932.08 GB (73.1%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=900__e98488a7\model_a"
Train Data Rows:    39
Train Data Columns: 5
Label Column:       iacs_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (104.865, 98.355, 101.56697, 1.92333)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5703.64 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['purity', 'iacs', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 899.95s of the 899.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.25%)
	-1.9246	 = Validation score   (-root_mean_squared_error)
	2.09s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 894.04s of the 894.03s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.30%)
	-1.9246	 = Validation score   (-root_mean_squared_error)
	2.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 887.71s of the 887.70s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0237	 = Validation score   (-root_mean_squared_error)
	0.56s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 886.99s of the 886.98s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.83%)
	-0.9908	 = Validation score   (-root_mean_squared_error)
	2.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 878.23s of the 878.22s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0145	 = Validation score   (-root_mean_squared_error)
	0.5s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 877.61s of the 877.60s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.8431	 = Validation score   (-root_mean_squared_error)
	17.65s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 857.34s of the 857.33s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.08%)
	-1.0998	 = Validation score   (-root_mean_squared_error)
	2.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 852.45s of the 852.44s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.4255	 = Validation score   (-root_mean_squared_error)
	14.38s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 835.39s of the 835.38s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.11%)
	-1.0748	 = Validation score   (-root_mean_squared_error)
	2.7s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 830.35s of the 830.33s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.42%)
	-1.0002	 = Validation score   (-root_mean_squared_error)
	4.94s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 822.63s of the 822.62s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.9834	 = Validation score   (-root_mean_squared_error)
	13.79s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 806.27s of the 806.26s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.47%)
	-1.1154	 = Validation score   (-root_mean_squared_error)
	4.03s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 799.83s of the 799.83s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.0367	 = Validation score   (-root_mean_squared_error)
	16.16s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 781.03s of the 781.02s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.16%)
	-0.9939	 = Validation score   (-root_mean_squared_error)
	9.69s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 768.99s of the 768.98s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-1.9246	 = Validation score   (-root_mean_squared_error)
	2.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 764.18s of the 764.17s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0457	 = Validation score   (-root_mean_squared_error)
	14.23s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 747.04s of the 747.03s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.36%)
	-1.0984	 = Validation score   (-root_mean_squared_error)
	2.18s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 742.39s of the 742.38s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0024	 = Validation score   (-root_mean_squared_error)
	0.56s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 741.71s of the 741.70s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=6.75%)
	-0.9545	 = Validation score   (-root_mean_squared_error)
	5.22s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 733.72s of the 733.71s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.8551	 = Validation score   (-root_mean_squared_error)
	15.02s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 716.00s of the 715.99s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=8.39%)
	-1.0033	 = Validation score   (-root_mean_squared_error)
	5.42s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 708.06s of the 708.04s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0069	 = Validation score   (-root_mean_squared_error)
	0.77s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 707.14s of the 707.13s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=1.03%)
	-1.0227	 = Validation score   (-root_mean_squared_error)
	3.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 701.08s of the 701.07s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.9363	 = Validation score   (-root_mean_squared_error)
	16.3s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 681.94s of the 681.93s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.07%)
	-1.1228	 = Validation score   (-root_mean_squared_error)
	3.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 674.63s of the 674.62s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0913	 = Validation score   (-root_mean_squared_error)
	17.04s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 654.79s of the 654.78s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.82%)
	-1.9246	 = Validation score   (-root_mean_squared_error)
	3.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 646.95s of the 646.94s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.3366	 = Validation score   (-root_mean_squared_error)
	16.04s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 628.00s of the 628.00s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=7.68%)
	-0.9665	 = Validation score   (-root_mean_squared_error)
	6.3s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 617.41s of the 617.40s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-2.0517	 = Validation score   (-root_mean_squared_error)
	18.83s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 595.58s of the 595.57s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.28%)
	-1.226	 = Validation score   (-root_mean_squared_error)
	1.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 582.52s of the 582.51s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-1.0239	 = Validation score   (-root_mean_squared_error)
	0.49s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 581.87s of the 581.86s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=9.94%)
	-0.9737	 = Validation score   (-root_mean_squared_error)
	5.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 572.34s of the 572.34s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.8937	 = Validation score   (-root_mean_squared_error)
	13.7s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 548.55s of the 548.54s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.0055	 = Validation score   (-root_mean_squared_error)
	16.65s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 525.73s of the 525.72s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=4.38%)
	-0.9487	 = Validation score   (-root_mean_squared_error)
	4.53s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 517.21s of the 517.21s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-1.8881	 = Validation score   (-root_mean_squared_error)
	18.36s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 492.70s of the 492.69s of remaining time.
	Memory not enough to fit 5 folds in parallel. Will train 4 folds in parallel instead (Estimated 16.97% memory usage per fold, 67.87%/80.00% total).
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=2, gpus=0, memory=16.97%)
	-0.952	 = Validation score   (-root_mean_squared_error)
	8.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r156_BAG_L1 ... Training model for up to 480.14s of the 480.13s of remaining time.

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema110826__bd1b73d5,2026-08-12T11:49:45,628.1,39,d90e3228,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__bd1b73d5,annealing_iacs,annealing-schema110826,NaN,iacs_final,...,0.32888,36,0.48151,0.37447,0.37041,-0.04838,0.8889,0.9444,0.9444,0.9444
1,annealing-schema110826__time_limit_a=900__e98488a7,2026-08-12T12:06:08,981.3,39,d90e3228,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=900__e98488a7,annealing_iacs,annealing-schema110826__time_limit_a=900,annealing-schema110826,iacs_final,...,0.19738,36,0.48837,0.39885,0.39496,-0.07846,0.3889,0.8333,0.9444,1.0000
2,annealing-schema110826__time_limit_a=600__f5a8ba0a,2026-08-12T12:17:57,708.3,39,d90e3228,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_iacs\experiments\annealing-schema110826\annealing-schema110826__time_limit_a=600__f5a8ba0a,annealing_iacs,annealing-schema110826__time_limit_a=600,annealing-schema110826,iacs_final,...,0.19893,36,0.54447,0.40813,0.40386,-0.34043,0.6667,0.9444,0.9444,0.9444

In [15]:
# import pickle
# from pathlib import Path
# import pandas as pd

# exp_dir = Path("../../models/annealing_iacs/experiments")
# rows = []
# for run_path in exp_dir.iterdir():
#     pkl = run_path / "artifacts.pkl"
#     if not pkl.exists():
#         continue
#     with open(pkl, "rb") as f:
#         art = pickle.load(f)
#     row = {"run_id": run_path.name}
#     row.update({f"cfg_{k}": v for k, v in art["config"].items()})
#     m = dict(art["metrics"]); m.pop("coverage", None)
#     row.update({k: v for k, v in m.items()})
#     cov = art["metrics"].get("coverage", {})
#     row.update({f"cov_{a}": c for a, c in cov.items()})
#     row["c_opt"] = art["recalibration_c"]
#     if art.get("validation_metrics"):
#         vm = dict(art["validation_metrics"]); vcov = vm.pop("coverage", {})
#         row.update({f"val_{k}": v for k, v in vm.items()})
#         row.update({f"val_cov_{a}": c for a, c in vcov.items()})
#     row["cfg_features"] = "|".join(art["features"])
#     rows.append(row)

# pd.DataFrame(rows).to_csv(exp_dir / "experiments_log.csv", index=False)
# print(f"Rebuilt log with {len(rows)} runs")

# 7. Inspect results

In [16]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_weight_on_essay_rows", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9", "c_opt", "pct_truncated_aleat",
    "mean_sigma_epist", "mean_sigma_aleat", "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_weight_on_essay_rows,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
1,annealing-schema110826__time_limit_a=900__e98488a7,900,1.0,purity|iacs|temperature|time,0.82342,0.63838,0.8974,0.48837,0.39885,0.9444,2.0451,20.51,0.29102,0.19738,981.3
2,annealing-schema110826__time_limit_a=600__f5a8ba0a,600,1.0,purity|iacs|temperature|time,0.88705,0.70504,0.8718,0.54447,0.40813,0.9444,2.4098,23.08,0.27761,0.19893,708.3
0,annealing-schema110826__bd1b73d5,120,1.0,purity|iacs|temperature|time,0.97422,0.77525,0.8718,0.48151,0.37447,0.9444,2.0451,12.82,0.19849,0.32888,628.1

In [17]:
# Quick pivot: effect of one knob, marginalised over the others.
# Remember: compare against run-to-run noise (Section 4) before concluding.
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                     rmse          mae     cov_0.9
                     mean std     mean std    mean std
cfg_time_limit_a
120               0.97422 NaN  0.77525 NaN  0.8718 NaN
600               0.88705 NaN  0.70504 NaN  0.8718 NaN
900               0.82342 NaN  0.63838 NaN  0.8974 NaN

# 8. Load a winner for deployment / further analysis

Each run folder is self-contained: predictors + artifacts.pkl with weights,
`recalibration_c`, calibration tables.

In [18]:
# log already carries the resolved absolute path, so use it directly
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema110826__time_limit_a=900__e98488a7

   alpha  empirical_coverage       gap
0   0.50            0.410256 -0.089744
1   0.80            0.717949 -0.082051
2   0.90            0.897436 -0.002564
3   0.95            0.897436 -0.052564

In [22]:
1

1

In [20]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-schema110826/annealing-schema110826__time_limit_a=900__e98488a7')

In [21]:
run_dir

Path('C:/Users/fmfoa/Projects/uncertainty-aware-predictors/models/annealing_iacs/experiments/annealing-schema110826/annealing-schema110826__time_limit_a=900__e98488a7')