**Author**: Felipe Matheus
**Purpose**: Experiment launcher for the annealing **tensile strength (UTS)** surrogate.

Same architecture as the IACS launcher: data preparation lives in
`src/pipelines/AnnealingPipeline.py` (composition resolution + IRI/GBEI via
`ChemicalFeatureEngineering`), and the modelling pipeline lives in
`src/modeling/Experiments.py`, which is process-agnostic — the SAME
`ExperimentRunner` is reused; only the `ExperimentConfig` changes (target,
features, physical bounds). No new class needed.

Kept in step with `notebooks/modeling/annealing_uts.ipynb`: same schema date,
same feature list (GBEI included).

Results layout: `models/annealing_uts/experiments/`
(`experiments_log.csv` + one folder per run).

# 1. Setup

In [1]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.modeling.Modeling import Modeling
from src.metrics.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner
from src.pipelines.AnnealingPipeline import AnnealingDataPipeline

from config.Variables import Variables
from config.bags_compositions import ALL_SAMPLES
from config.elements_coefficients import RESISTIVITY_FACTORS, ENRICHMENT_FACTORS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# ---- Surrogate identity ----
TARGET = "tensile_strength_final"
# GBEI is composition-derived (ChemicalFeatureEngineering), not a raw column.
ALL_FEATURES = ["IRI" "initial_diameter", "GBEI", "purity", "tensile_strength",
                "temperature", "time"]
PROCESS = "annealing_uts"

# ---- Schemas (kept in step with notebooks/modeling/annealing_uts.ipynb) ----
# Bump both to "070926" when that notebook moves to the newer schema.
ANNEALING_SCHEMA_DATE = "070926"
SN_SCHEMA_DATE = "070926"
FILE_NAME_SCHEMA_DATA = f"schema_annealing_essays_{ANNEALING_SCHEMA_DATE}.csv"
FILE_NAME_SN_COMPOSITION = f"serial-number-encoding_{SN_SCHEMA_DATE}.csv"

ID = "IRI-GBEI-comparison"
TAG = f"annealing-schema{ANNEALING_SCHEMA_DATE}_{ID}"

# ---- Physical constraints (inference-time truncation) ----
Y_MAX = None
Y_MIN = 0.0     # tensile strength cannot be negative

GRID = {
    "time_limit_a": [1200, 3600],
    # "num_bag_folds_a": [10, 15, 20],
    "features": [
        ("IRI", "initial_diameter", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("IRI", "purity", "initial_diameter", "tensile_strength", "temperature", "time"),  # pre-GBEI baseline
        ("IRI", "initial_diameter", "GBEI", "tensile_strength", "temperature", "time"), # no purity
        ("IRI", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("initial_diameter", "GBEI", "purity", "tensile_strength", "temperature", "time"),
        ("purity", "initial_diameter", "tensile_strength", "temperature", "time"),  # pre-GBEI baseline
        ("initial_diameter", "GBEI", "tensile_strength", "temperature", "time"), # no purity
        ("GBEI", "purity", "tensile_strength", "temperature", "time"),
    ],
    # NOTE: "weight_on_essay_rows" is no longer sweepable — the pipeline output
    # carries no `is_essay` column, so anything but 1.0 makes the runner raise.
}

# Raw columns the pipeline keeps before feature engineering. `material_reference`
# is never a model feature, but ChemicalFeatureEngineering resolves it into the
# composition that IRI and GBEI are computed from, so it must survive here.
ANNEALING_FEATURES = [
    "experiment_id",
    "material_reference",
    "purity",
    "initial_diameter",
    "temperature",
    "time",
    "iacs",
    "tensile_strength",
    "elongation",
    "iacs_final",
    "tensile_strength_final",
    "elongation_final",
]

# 2. Data

`AnnealingDataPipeline` replaces the old `proc.process_annealing_uts` call
(that method was moved out of `Processing`). It performs the same preparation
as `notebooks/modeling/annealing_uts.ipynb`, run once here.

In [3]:
# One pipeline object owns the whole preparation: drop all-NaN rows, select
# ANNEALING_FEATURES, resolve every material_reference to a composition, and
# attach IRI + GBEI. `pipe.df_iri_gbei` is the enriched frame the getters slice.
pipe = AnnealingDataPipeline(
    df_annealing_schema_raw=pd.read_csv(
        os.path.join(varv.PATHS.data_raw, FILE_NAME_SCHEMA_DATA)
    ),
    annealing_features=ANNEALING_FEATURES,
    df_sn=pd.read_csv(
        os.path.join(varv.PATHS.data_structured, FILE_NAME_SN_COMPOSITION)
    ),
    all_samples=ALL_SAMPLES,
    resistivity_factors=RESISTIVITY_FACTORS,
    enrichment_factors=ENRICHMENT_FACTORS,
)

df, df_val = pipe.get_uts_df_df_val(
    features_uts=ALL_FEATURES,
    target_uts=TARGET,
)

print(f"train: {df.shape} | val: {df_val.shape}")
df.head()

train: (53, 7) | val: (10, 7)

,initial_diameter,GBEI,purity,tensile_strength,temperature,time,tensile_strength_final
0,2.160000,0.001038,99.9,391.690000,573,30.0,249.78
1,2.182333,0.001038,99.9,387.595254,573,30.0,255.01
2,1.200000,0.002674,99.9,431.580000,523,30.0,247.08
3,1.200000,0.002674,99.9,431.580000,523,60.0,242.21
4,1.200000,0.002674,99.9,431.580000,523,90.0,239.64

In [4]:
# Sanity check BEFORE training: an unresolved material_reference yields NaN
# IRI/GBEI, and the getter's .dropna() then removes those rows silently. This
# report is the fastest way to see a typo'd reference or a blend whose bag
# weights did not sum to 1.
report = pipe.chfe.resolution_report(pipe.df_feat)
print(f"unresolved references: {(~report['resolved']).sum()}")
report

unresolved references: 0

,n_rows,source,resolved,raw weight sum,recipe,problem
material_reference,,,,,,
Cu-ETP,12,direct sample,True,NaN,,
Cu-T2,9,direct sample,True,NaN,,
SN015,9,blend,True,1.0,"1B_sac2=0.4047, 1B_sac3=0.4047, 1B_sac5=0.1906",
SN014,6,blend,True,1.0,1B_sac2=1,
SN021,6,blend,True,1.0,"1A_sac1=0.02, 1A_sac2=0.02, 1B_sac2=0.02, 1B_s...",
SN019,5,blend,True,1.0,"1A_sac1=0.3, 2N_sac2=0.6952, echantillon_2N=0....",
C14500,3,direct sample,True,NaN,,
SN027,3,blend,True,1.0,"1B_sac3=0.05, 1B_sac4=0.05, 1B_sac5=0.05, 1B_s...",
SN025,2,blend,True,1.0,"1B_sac2=0.1, 1B_sac3=0.1, 1B_sac5=0.1, echanti...",
SN016,2,blend,True,1.0,"1B_sac2=0.2305, 1B_sac3=0.2305, 1B_sac5=0.2305...",
SN024,1,blend,True,1.0,"1B_sac6=0.1, echantillon_1=0.225, echantillon_...",
SN029,1,blend,True,1.0,"1A_sac1=0.10273, 1A_sac2=0.10273, 1B_sac1=0.10...",

# 3. Base config

In [ ]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    presets_a="best_quality",
    presets_b="best_quality",
    y_max=Y_MAX,
    y_min=Y_MIN,
    # `weight_on_essay_rows` stays at its 1.0 default: the pipeline output has
    # no `is_essay` column, and any other value would make the runner raise.
    # Same reason `use_shared_folds` stays False (fold stratification needs it).
)
print(base.run_id)

annealing-schema070926_LT-20-with-IRI__a0fcf479

# 4. Single run (sanity check before any grid)

Run the base config alone first; then repeat 2-3x with `tag="uts-v1-rep2"`
etc. to measure run-to-run noise (the floor below which grid differences
mean nothing).

In [6]:
result = runr.run_experiment(df, cfg=base, df_val=df_val)
result["artifacts"]["metrics"]

2026-09-08 23:30:46,094 | INFO | src.modeling.Experiments | Skipping annealing-schema070926_LT-20-with-IRI__a0fcf479 (already run). force=True to redo.

{'rmse': 14.527437003016272,
 'mae': 7.8242308764187785,
 'mape': 2.8680984433404184,
 'r2': 0.6261796439736713,
 'coverage': {0.5: 0.5471698113207547,
  0.8: 0.8490566037735849,
  0.9: 0.9056603773584906,
  0.95: 0.9433962264150944}}

# 5. Validation set

`df_val` rides along inside the runner: after training + calibration, the
calibrated predictive distribution is evaluated on it and `val_rmse`,
`val_mae`, `val_r2`, `val_cov_*` are appended to the SAME log row — so every
grid run carries fold (OOF) metrics AND validation metrics side by side.

**Caveat — where this `df_val` comes from.** The pipeline getter builds it as a
random 20 % sample *of `df` itself* when no `df_val` is passed, so those rows
are inside the training data and the val metrics are IN-SAMPLE and optimistic.
Pass a genuinely held-out frame to the getter to make them honest — it must
carry the same engineered columns (`IRI` / `GBEI` included), which in practice
means running it through `pipe` too.

In [7]:
df_val

,initial_diameter,GBEI,purity,tensile_strength,temperature,time,tensile_strength_final
19,1.2,0.006830,99.9800,335.21,573,60.0,245.00
41,2.2,0.264027,99.7036,362.31,673,60.0,235.61
47,2.2,0.207493,99.7637,367.04,673,60.0,231.44
12,1.2,0.001038,99.9000,397.09,573,30.0,261.32
43,2.2,0.264027,99.7036,362.31,773,60.0,232.15
5,1.2,0.002674,99.9000,431.58,573,30.0,232.03
17,1.2,0.001038,99.9000,397.09,523,90.0,259.14
50,1.0,0.268018,99.6985,367.73,723,60.0,239.69
3,1.2,0.002674,99.9000,431.58,523,60.0,242.21
32,0.8,0.011525,99.9740,347.70,673,30.0,247.19

In [8]:
result["artifacts"]["validation_metrics"]

{'rmse': 1.9449426316693028,
 'mae': 1.311897488395698,
 'mape': 0.5481360242622215,
 'r2': 0.9641027701047477,
 'coverage': {0.5: 0.9, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}}

In [9]:
result["artifacts"].keys()

dict_keys(['config', 'features', 'target', 'base_model_names', 'weights', 'nnls_recovery_ok', 'nnls_max_diff', 'variance_floor', 'recalibration_c', 'ood_ref', 'y_max', 'y_min', 'calibration_before', 'calibration_after', 'aleatoric_diagnostics', 'metrics', 'validation_metrics', 'dataset_hash'])

In [10]:
result.keys()

dict_keys(['cfg', 'run_dir', 'artifacts', 'log_row', 'predictor_a', 'predictor_b'])

In [11]:
result

{'cfg': ExperimentConfig(process='annealing_uts', tag='annealing-schema070926_LT-20-with-IRI', base_tag=None, target='tensile_strength_final', features=('initial_diameter', 'GBEI', 'purity', 'tensile_strength', 'temperature', 'time'), weight_on_essay_rows=1.0, presets_a='best_quality', num_bag_folds_a=5, num_bag_sets_a=1, num_stack_levels_a=0, time_limit_a=120, presets_b='medium_quality', num_bag_folds_b=5, num_stack_levels_b=0, time_limit_b=60, use_weighted_variance=True, variance_floor_frac=0.01, recalibration_target_alpha=0.9, calibration_alphas=(0.5, 0.8, 0.9, 0.95), y_max=None, y_min=0.0, fold_seed=42, use_shared_folds=False, group_col=None),
 'run_dir': WindowsPath('../../models/annealing_uts/experiments/annealing-schema070926_LT-20-with-IRI/annealing-schema070926_LT-20-with-IRI__a0fcf479'),
 'artifacts': {'config': {'process': 'annealing_uts',
   'tag': 'annealing-schema070926_LT-20-with-IRI',
   'base_tag': None,
   'target': 'tensile_strength_final',
   'features': ['initial_diameter',
    'GBEI',
    'purity',
    'tensile_strength',
    'temperature',
    'time'],
   'weight_on_essay_rows': 1.0,
   'presets_a': 'best_quality',
   'num_bag_folds_a': 5,
   'num_bag_sets_a': 1,
   'num_stack_levels_a': 0,
   'time_limit_a': 120,
   'presets_b': 'medium_quality',
   'num_bag_folds_b': 5,
   'num_stack_levels_b': 0,
   'time_limit_b': 60,
   'use_weighted_variance': True,
   'variance_floor_frac': 0.01,
   'recalibration_target_alpha': 0.9,
   'calibration_alphas': [0.5, 0.8, 0.9, 0.95],
   'y_max': None,
   'y_min': 0.0,
   'fold_seed': 42,
   'use_shared_folds': False,
   'group_col': None},
  'features': ['initial_diameter',
   'GBEI',
   'purity',
   'tensile_strength',
   'temperature',
   'time'],
  'target': 'tensile_strength_final',
  'base_model_names': ['LightGBMXT_BAG_L1',
   'LightGBM_BAG_L1',
   'RandomForestMSE_BAG_L1',
   'CatBoost_BAG_L1',
   'ExtraTreesMSE_BAG_L1',
   'NeuralNetFastAI_BAG_L1',
   'XGBoost_BAG_L1',
   'NeuralNetTorch_BAG_L1'],
  'weights': array([0.00000000e+00, 0.00000000e+00, 2.50000087e-01, 7.49999838e-01,
         7.45986471e-08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
  'nnls_recovery_ok': True,
  'nnls_max_diff': 1.6081695946468244e-05,
  'variance_floor': 5.754234822206097,
  'recalibration_c': 2.045088649228769,
  'ood_ref': {'features': ['initial_diameter',
    'GBEI',
    'purity',
    'tensile_strength',
    'temperature',
    'time'],
   'mean': array([1.47815723e+00, 8.57125997e-02, 9.98662019e+01, 3.76785005e+02,
          6.44509434e+02, 5.07075472e+01]),
   'cov_inv': array([[ 5.33637957e+00, -6.85080232e+00,  7.06025089e+00,
            7.62909394e-04, -1.26016695e-03, -6.45721550e-03],
          [-6.85080232e+00,  2.46508926e+02,  1.83495176e+02,
            1.87360269e-01, -3.87971577e-02, -5.84192850e-02],
          [ 7.06025089e+00,  1.83495176e+02,  2.55213261e+02,
            2.18175434e-01,  1.01889829e-02,  1.88517449e-02],
          [ 7.62909394e-04,  1.87360269e-01,  2.18175434e-01,
            1.31223738e-03,  1.08731556e-04, -1.32136507e-04],
          [-1.26016695e-03, -3.87971577e-02,  1.01889829e-02,
            1.08731556e-04,  1.37155248e-04,  1.62853357e-04],
          [-6.45721550e-03, -5.84192850e-02,  1.88517449e-02,
           -1.32136507e-04,  1.62853357e-04,  1.86015549e-03]]),
   'd_ref': 3.037842236781612,
   'ranges': {'initial_diameter': (0.8, 2.2),
    'GBEI': (0.0010379999999999999, 0.2966417158930622),
    'purity': (99.6675, 99.98),
    'tensile_strength': (335.21, 431.58),
    'temperature': (523.0, 923.0),
    'time': (0.5, 105.0)}},
  'y_max': None,
  'y_min': 0.0,
  'calibration_before':    alpha  empirical_coverage       gap
  0   0.50            0.320755 -0.179245
  1   0.80            0.509434 -0.290566
  2   0.90            0.641509 -0.258491
  3   0.95            0.698113 -0.251887,
  'calibration_after':    alpha  empirical_coverage       gap
  0   0.50            0.547170  0.047170
  1   0.80            0.849057  0.049057
  2   0.90            0.905660  0.005660
  3   0.95            0.943396 -0.006604,
  'aleatoric_diagnostics': {'n_total': 53,
   'n_truncated': 8,
   'pct_truncated': 15.09433962264151,
   'r_tilde_sq_min': 0.0,
   'r_tilde_sq_max': 4188.900883222961,
   'r_tilde_sq_mean': 205.60168035372348,
   'r_tilde_sq_median': 11.915919190564269},
  'metrics': {'rmse': 14.527437003016272,
   'mae': 7.8242308764187785,
   'mape': 2.8680984433404184,
   'r2': 0.6261796439736713,
   'coverage': {0.5: 0.5471698113207547,
    0.8: 0.8490566037735849,
    0.9: 0.9056603773584906,
    0.95: 0.9433962264150944}},
  'validation_metrics': {'rmse': 1.9449426316693028,
   'mae': 1.311897488395698,
   'mape': 0.5481360242622215,
   'r2': 0.9641027701047477,
   'coverage': {0.5: 0.9, 0.8: 1.0, 0.9: 1.0, 0.95: 1.0}},
  'dataset_hash': '4f17a278'},
 'log_row': None,
 'predictor_a': None,
 'predictor_b': None}

# 6. Grid

In [12]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-09-08 23:30:46,925 | INFO | src.modeling.Experiments | Grid: 8 runs over ['time_limit_a', 'features']
2026-09-08 23:30:46,926 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__624b2b5c ===
2026-09-08 23:30:46,927 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,929 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__624b2b5c failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,934 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__4f4323cf ===
2026-09-08 23:30:46,935 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,936 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__4f4323cf failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,938 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__40cbd736 ===
2026-09-08 23:30:46,939 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,940 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__40cbd736 failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,942 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time__7b3009dc ===
2026-09-08 23:30:46,943 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,944 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=1200__features=IRI-GBEI-purity-tensile_strength-temperature-time__7b3009dc failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,945 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__e96f3d16 ===
2026-09-08 23:30:46,946 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,948 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-initial_diameter-GBEI-purity-tensile_strength-temperature-time__e96f3d16 failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,950 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__4e3e3d88 ===
2026-09-08 23:30:46,951 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,951 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-purity-initial_diameter-tensile_strength-temperature-time__4e3e3d88 failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,954 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__1b9e1e6f ===
2026-09-08 23:30:46,954 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,956 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-initial_diameter-GBEI-tensile_strength-temperature-time__1b9e1e6f failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"
2026-09-08 23:30:46,958 | INFO | src.modeling.Experiments | === Running annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-GBEI-purity-tensile_strength-temperature-time__9eb7e533 ===
2026-09-08 23:30:46,958 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
2026-09-08 23:30:46,960 | ERROR | src.modeling.Experiments | Run annealing-schema070926_LT-20-with-IRI__time_limit_a=600__features=IRI-GBEI-purity-tensile_strength-temperature-time__9eb7e533 failed; continuing grid.
Traceback (most recent call last):
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 631, in run_grid
    self.run_experiment(df, cfg, df_val=df_val, force=force)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Experiments.py", line 408, in run_experiment
    predictor_a = self.modl.fit_model_a(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\modeling\Modeling.py", line 132, in fit_model_a
    train_df = df[keep_cols].copy()
               ~~^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\frame.py", line 4119, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IRI'] not in index"

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,mean_sigma_aleat,n_val,val_rmse,val_mae,val_mape,val_r2,val_cov_0.5,val_cov_0.8,val_cov_0.9,val_cov_0.95
0,annealing-schema070926_LT-20-with-IRI__a0fcf479,2026-09-08T23:27:18,192.0,53,4f17a278,C:\Users\fmfoa\Projects\uncertainty-aware-pred...,annealing_uts,annealing-schema070926_LT-20-with-IRI,NaN,tensile_strength_final,...,3.22361,10,1.94494,1.3119,0.54814,0.9641,0.9,1.0,1.0,1.0

# 7. Inspect results

In [13]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_num_bag_folds_a", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9",
    "c_opt", "pct_truncated_aleat", "mean_sigma_epist", "mean_sigma_aleat",
    "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_num_bag_folds_a,cfg_features,rmse,mae,cov_0.9,val_rmse,val_mae,val_cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
0,annealing-schema070926_LT-20-with-IRI__a0fcf479,120,5,initial_diameter|GBEI|purity|tensile_strength|...,14.52744,7.82423,0.9057,1.94494,1.3119,1.0,2.0451,15.09,1.52639,3.22361,192.0

In [14]:
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                      rmse          mae     cov_0.9
                      mean std     mean std    mean std
cfg_time_limit_a
120               14.52744 NaN  7.82423 NaN  0.9057 NaN

# 8. Load a winner

In [15]:
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-schema070926_LT-20-with-IRI__a0fcf479

   alpha  empirical_coverage       gap
0   0.50            0.547170  0.047170
1   0.80            0.849057  0.049057
2   0.90            0.905660  0.005660
3   0.95            0.943396 -0.006604

In [16]:
1

1