**Author**: Felipe Matheus
**Purpose**: Experiment launcher for the annealing **tensile strength (UTS)** surrogate.

Same architecture as `run_experiments.ipynb` (IACS): all pipeline logic lives
in `src/modeling/Experiments.py`, which is process-agnostic — the SAME
`ExperimentRunner` is reused; only the `ExperimentConfig` changes (target,
features, physical bounds). No new class needed.

Results layout: `models/annealing_tensile_strength/experiments/`
(`experiments_log.csv` + one folder per run).

# 1. Setup

In [ ]:
import logging
import os
import sys

import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from autogluon.tabular import TabularPredictor

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.processing.Processing import Processing
from src.feature_engineering.FeatureEngineering import FeatureEngineering
from src.modeling.Modeling import Modeling
from src.modeling.Evaluation import Evaluation
from src.modeling.Experiments import ExperimentConfig, ExperimentRunner

from config.Variables import Variables

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

%load_ext autoreload
%autoreload 2

varv = Variables()
proc = Processing()
feng = FeatureEngineering()
modl = Modeling()
evla = Evaluation()
runr = ExperimentRunner(modl, evla, models_root=varv.PATHS.models)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
TARGET = "tensile_strength_final"
ALL_FEATURES = ["purity", "initial_diameter", "tensile_strength", "temperature", "time"]
PROCESS = "annealing_uts"

TAG = "annealing-uts-v1-best_quality"
GRID = {
    "time_limit_a": [120, 900],
    "num_bag_folds_a": [5, 10],
    # "features": [
    #     ("purity", "initial_diameter", "tensile_strength", "temperature", "time"),
    #     # ("initial_diameter", "tensile_strength", "temperature", "time"),
    # ],
}

# 2. Data (same preparation as annealing_uts.ipynb, run once)

In [7]:
FILE_NAME = "dataset_annealing_tensile-strength.csv"

df_raw = pd.read_csv(os.path.join(varv.PATHS.data_raw, FILE_NAME))
df_float = proc.df_to_float(
    df_raw, drop_cols=["DOI", "is_Cu"], ignore_columns=["material"]
)
df_labeled = feng.label_element(df_float).drop_duplicates()
df_with_masks = feng.add_ratio_mask_column(
    feng.add_ratio_mask_column(df_labeled, "grain_size"), "tensile_strength",
)
df = (
    df_with_masks[ALL_FEATURES + [TARGET]]
    .dropna(subset=[TARGET])
    .reset_index(drop=True)
)

# No essay rows yet for UTS -> no is_essay column. The runr detects this
# and applies uniform weights (weight_on_essay_rows must stay 1.0).
print(f"Dataset: {df.shape}")

# Validation set: none held-out yet. When UTS essays arrive, build df_val
# from them (with the same columns) and pass df_val=df_val below.
df_val = None
df.head()

Dataset: (92, 6)

c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\src\processing\Processing.py:37: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_float = df_float.applymap(

,purity,initial_diameter,tensile_strength,temperature,time,tensile_strength_final
0,99.99,23.0,1200.0,373.0,60.0,1180.0
1,99.99,23.0,1200.0,473.0,60.0,1150.0
2,99.99,23.0,1200.0,573.0,60.0,850.0
3,99.99,23.0,1200.0,673.0,60.0,600.0
4,99.99,23.0,1200.0,773.0,60.0,330.0

# 3. Base config

In [ ]:
base = ExperimentConfig(
    process=PROCESS,
    tag=TAG,
    target=TARGET,
    features=tuple(ALL_FEATURES),
    y_max=None,
    y_min=0.0,
    presets_a = "best_quality",
)
print(base.run_id)

annealing-uts-v1-test__e3d4945f

# 4. Single run (sanity check before any grid)

Run the base config alone first; then repeat 2-3x with `tag="uts-v1-rep2"`
etc. to measure run-to-run noise (the floor below which grid differences
mean nothing).

In [ ]:
# result = runr.run_experiment(df, cfg=base, df_val=df_val)
# result["artifacts"]["metrics"]

2026-06-24 15:59:13,789 | INFO | src.modeling.Experiments | === Running annealing-uts-v1-test__e3d4945f ===
2026-06-24 15:59:13,790 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       12.44 GB / 31.57 GB (39.4%)
Disk Space Avail:   752.97 GB / 932.08 GB (80.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__e3d4945f\model_a"
Train Data Rows:    92
Train Data Columns: 6
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1180.0, 124.0, 329.76, 190.87151)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12728.39 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.98s of the 119.97s of remaining time.
2026-06-24 15:59:18,868	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
c:\Users\fmfoa\Projects\uncertainty-aware-predictors\.venv\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-84.0452	 = Validation score   (-root_mean_squared_error)
	1.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 107.08s of the 107.08s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-73.8674	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 102.89s of the 102.89s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-59.4094	 = Validation score   (-root_mean_squared_error)
	0.6s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 102.22s of the 102.22s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.30%)
	-55.5184	 = Validation score   (-root_mean_squared_error)
	43.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 54.73s of the 54.73s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-53.6421	 = Validation score   (-root_mean_squared_error)
	0.37s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 54.27s of the 54.27s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-45.5324	 = Validation score   (-root_mean_squared_error)
	8.64s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 42.17s of the 42.16s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.05%)
	-54.2798	 = Validation score   (-root_mean_squared_error)
	1.18s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 36.56s of the 36.55s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-56.4282	 = Validation score   (-root_mean_squared_error)
	15.01s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 17.85s of the 17.85s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.58%)
	-60.7487	 = Validation score   (-root_mean_squared_error)
	3.39s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.98s of the 9.96s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/11.4 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.5, 'NeuralNetTorch_BAG_L1': 0.25, 'RandomForestMSE_BAG_L1': 0.125, 'XGBoost_BAG_L1': 0.125}
	-40.7811	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 110.09s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 168.3 rows/s (19 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__e3d4945f\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.54 GB / 31.57 GB (36.6%)
Disk Space Avail:   752.90 GB / 932.08 GB (80.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__e3d4945f\model_b"
Train Data Rows:    92
Train Data Columns: 5
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (10.57468107593003, -13.815510557964274, -4.29723, 10.09629)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11879.01 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.98s of the 59.98s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-9.7541	 = Validation score   (-root_mean_squared_error)
	1.63s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 55.25s of the 55.25s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-9.5599	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 49.95s of the 49.95s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.695	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 49.35s of the 49.35s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.24%)
	-9.995	 = Validation score   (-root_mean_squared_error)
	2.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 43.77s of the 43.77s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.6531	 = Validation score   (-root_mean_squared_error)
	0.5s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 43.14s of the 43.14s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-9.9119	 = Validation score   (-root_mean_squared_error)
	8.63s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 31.11s of the 31.10s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.05%)
	-10.21	 = Validation score   (-root_mean_squared_error)
	1.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 25.88s of the 25.88s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-10.3135	 = Validation score   (-root_mean_squared_error)
	7.63s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 14.45s of the 14.45s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.62%)
	-10.2344	 = Validation score   (-root_mean_squared_error)
	1.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 8.73s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/11.0 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 0.7, 'NeuralNetFastAI_BAG_L1': 0.3}
	-9.4787	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 51.32s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 382.9 rows/s (19 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__e3d4945f\model_b")
2026-06-24 16:02:00,051 | INFO | src.modeling.Experiments | Done annealing-uts-v1-test__e3d4945f in 166.2s

{'rmse': 40.78105998345382,
 'mae': 25.740681563667632,
 'mape': 8.221208254720606,
 'r2': 0.953848987214664}

# 5 Validation set

TBD

# 6. Grid

In [10]:
log = runr.run_grid(df, base_cfg=base, grid=GRID, df_val=df_val)
log

2026-06-24 16:02:00,853 | INFO | src.modeling.Experiments | Grid: 8 runs over ['time_limit_a', 'num_bag_folds_a', 'features']
2026-06-24 16:02:00,856 | INFO | src.modeling.Experiments | === Running annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1 ===
2026-06-24 16:02:00,856 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.63 GB / 31.57 GB (36.8%)
Disk Space Avail:   752.89 GB / 932.08 GB (80.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1\model_a"
Train Data Rows:    92
Train Data Columns: 6
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1180.0, 124.0, 329.76, 190.87151)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11907.76 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.97s of the 59.97s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-84.0452	 = Validation score   (-root_mean_squared_error)
	2.08s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 54.41s of the 54.41s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-73.8674	 = Validation score   (-root_mean_squared_error)
	2.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 48.30s of the 48.29s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-59.4094	 = Validation score   (-root_mean_squared_error)
	0.37s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 47.84s of the 47.83s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.29%)
	-55.5184	 = Validation score   (-root_mean_squared_error)
	39.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 5.16s of the 5.16s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-53.6421	 = Validation score   (-root_mean_squared_error)
	0.35s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 4.72s of the 4.72s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-45.5324	 = Validation score   (-root_mean_squared_error)
	8.65s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.97s of the -7.17s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/10.4 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.65, 'CatBoost_BAG_L1': 0.2, 'RandomForestMSE_BAG_L1': 0.15}
	-43.0623	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 67.23s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 296.2 rows/s (19 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1\model_a")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       10.40 GB / 31.57 GB (33.0%)
Disk Space Avail:   752.85 GB / 932.08 GB (80.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1\model_b"
Train Data Rows:    92
Train Data Columns: 5
Label Column:       log_r_tilde_sq
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (10.58653025443765, -13.815510557964274, -0.84743, 9.63829)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11405.99 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 5 | ['purity', 'initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 59.96s of the 59.96s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.13%)
	-9.6805	 = Validation score   (-root_mean_squared_error)
	1.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 54.68s of the 54.68s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.14%)
	-9.6138	 = Validation score   (-root_mean_squared_error)
	1.57s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 49.37s of the 49.37s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.0604	 = Validation score   (-root_mean_squared_error)
	0.57s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 48.69s of the 48.69s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=3.32%)
	-9.6213	 = Validation score   (-root_mean_squared_error)
	1.84s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 43.13s of the 43.13s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=8, gpus=0
	-10.1398	 = Validation score   (-root_mean_squared_error)
	0.47s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 42.55s of the 42.55s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-9.081	 = Validation score   (-root_mean_squared_error)
	8.73s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 30.28s of the 30.28s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.05%)
	-9.4907	 = Validation score   (-root_mean_squared_error)
	0.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 25.21s of the 25.21s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.00%)
	-9.5591	 = Validation score   (-root_mean_squared_error)
	7.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 14.18s of the 14.18s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=1, gpus=0, memory=0.61%)
	-9.4304	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.96s of the 8.36s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/11.0 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.81, 'RandomForestMSE_BAG_L1': 0.095, 'LightGBMLarge_BAG_L1': 0.095}
	-9.0555	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 51.7s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 327.6 rows/s (19 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1\model_b")
2026-06-24 16:04:01,755 | INFO | src.modeling.Experiments | Done annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1 in 120.9s
2026-06-24 16:04:01,757 | INFO | src.modeling.Experiments | === Running annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__eced9448 ===
2026-06-24 16:04:01,758 | INFO | src.modeling.Experiments | No 'is_essay' column: dataset has no essay rows; uniform weights applied.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.9
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       11.68 GB / 31.57 GB (37.0%)
Disk Space Avail:   752.84 GB / 932.08 GB (80.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Values in column 'weight_col' used as sample weights instead of predictive features. Evaluation metrics will ignore sample weights, specify weight_evaluation=True to instead report weighted metrics.
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__eced9448\model_a"
Train Data Rows:    92
Train Data Columns: 5
Label Column:       tensile_strength_final
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1180.0, 124.0, 329.76, 190.87151)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11962.46 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4 | ['initial_diameter', 'tensile_strength', 'temperature', 'time']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4 | ['initial_diameter', 'tensile_strength', 'temperature', 'time']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],

,run_id,timestamp,elapsed_s,n_rows,dataset_hash,model_dir,cfg_process,cfg_tag,cfg_base_tag,cfg_target,...,r2,cov_0.5,cov_0.8,cov_0.9,cov_0.95,c_opt,pct_truncated_aleat,nnls_recovery_ok,mean_sigma_epist,mean_sigma_aleat
0,annealing-uts-v1-test__e3d4945f,2026-06-24T16:02:00,166.2,92,d26194f9,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__e3d4945f,annealing_uts,annealing-uts-v1-test,NaN,tensile_strength_final,...,0.95385,0.6413,0.8261,0.9239,0.9348,1.0902,52.17,True,23.18034,19.08715
1,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1,2026-06-24T16:04:01,120.9,92,d26194f9,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1,annealing_uts,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.94854,0.4891,0.8152,0.8913,0.9348,1.0902,34.78,True,18.10781,19.08715
2,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__eced9448,2026-06-24T16:06:05,123.4,92,689947c5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__eced9448,annealing_uts,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.96020,0.5000,0.7935,0.9022,0.9348,1.1431,30.43,True,18.42146,19.08715
3,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__9c4b8022,2026-06-24T16:08:09,124.7,92,d26194f9,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__9c4b8022,annealing_uts,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.96463,0.5109,0.8370,0.9239,0.9565,1.0708,28.26,True,15.78590,19.08715
4,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__2bdb3be2,2026-06-24T16:10:33,144.0,92,689947c5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__2bdb3be2,annealing_uts,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.96855,0.5000,0.8152,0.9022,0.9348,1.0502,32.61,True,15.89410,19.08715
5,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__e3d4945f,2026-06-24T16:13:06,152.9,92,d26194f9,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__e3d4945f,annealing_uts,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.95385,0.6413,0.8261,0.9239,0.9348,1.0902,52.17,True,23.18034,19.08715
6,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__7c7745e2,2026-06-24T16:15:37,150.3,92,689947c5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__7c7745e2,annealing_uts,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.96046,0.5109,0.8152,0.9022,0.9239,1.0902,42.39,True,21.39663,19.08715
7,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__2c0d86a2,2026-06-24T16:18:32,175.7,92,d26194f9,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__2c0d86a2,annealing_uts,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.96878,0.5326,0.7935,0.9022,0.9565,0.9296,46.74,True,21.92120,19.08715
8,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__9b0ba1d3,2026-06-24T16:21:25,172.9,92,689947c5,C:\Users\fmfoa\Projects\uncertainty-aware-predictors\models\annealing_uts\experiments\annealing-uts-v1-test\annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__9b0ba1d3,annealing_uts,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time,annealing-uts-v1-test,tensile_strength_final,...,0.97107,0.5870,0.8587,0.9348,0.9457,1.0902,54.35,True,21.55632,19.08715

# 7. Inspect results

In [11]:
log = runr.load_log(base)

view_cols = [
    "run_id", "cfg_time_limit_a", "cfg_num_bag_folds_a", "cfg_features",
    "rmse", "mae", "cov_0.9", "val_rmse", "val_mae", "val_cov_0.9",
    "c_opt", "pct_truncated_aleat", "mean_sigma_epist", "mean_sigma_aleat",
    "elapsed_s",
]
log[[c for c in view_cols if c in log.columns]].sort_values("rmse")

,run_id,cfg_time_limit_a,cfg_num_bag_folds_a,cfg_features,rmse,mae,cov_0.9,c_opt,pct_truncated_aleat,mean_sigma_epist,mean_sigma_aleat,elapsed_s
8,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__9b0ba1d3,120,10,initial_diameter|tensile_strength|temperature|time,32.28832,22.75341,0.9348,1.0902,54.35,21.55632,19.08715,172.9
7,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__2c0d86a2,120,10,purity|initial_diameter|tensile_strength|temperature|time,33.54071,23.56783,0.9022,0.9296,46.74,21.92120,19.08715,175.7
4,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__2bdb3be2,60,10,initial_diameter|tensile_strength|temperature|time,33.66411,24.19113,0.9022,1.0502,32.61,15.89410,19.08715,144.0
3,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=10__features=purity-initial_diameter-tensile_strength-temperature-time__9c4b8022,60,10,purity|initial_diameter|tensile_strength|temperature|time,35.70117,24.57673,0.9239,1.0708,28.26,15.78590,19.08715,124.7
6,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__7c7745e2,120,5,initial_diameter|tensile_strength|temperature|time,37.74624,26.83952,0.9022,1.0902,42.39,21.39663,19.08715,150.3
2,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=initial_diameter-tensile_strength-temperature-time__eced9448,60,5,initial_diameter|tensile_strength|temperature|time,37.87000,27.36114,0.9022,1.1431,30.43,18.42146,19.08715,123.4
5,annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__e3d4945f,120,5,purity|initial_diameter|tensile_strength|temperature|time,40.78106,25.74068,0.9239,1.0902,52.17,23.18034,19.08715,152.9
0,annealing-uts-v1-test__e3d4945f,120,5,purity|initial_diameter|tensile_strength|temperature|time,40.78106,25.74068,0.9239,1.0902,52.17,23.18034,19.08715,166.2
1,annealing-uts-v1-test__time_limit_a=60__num_bag_folds_a=5__features=purity-initial_diameter-tensile_strength-temperature-time__bbce27b1,60,5,purity|initial_diameter|tensile_strength|temperature|time,43.06229,27.29911,0.8913,1.0902,34.78,18.10781,19.08715,120.9

In [13]:
log.groupby("cfg_time_limit_a")[["rmse", "mae", "cov_0.9"]].agg(["mean", "std"])

                       rmse                  mae           cov_0.9
                       mean       std       mean       std    mean       std
cfg_time_limit_a
60                37.574393  4.041603  25.857028  1.708443  0.9049  0.013669
120               37.027478  3.978459  24.928424  1.699537  0.9174  0.014572

# 8. Load a winner

In [ ]:
best_row = log.sort_values("rmse").iloc[0]
RUN_ID = best_row["run_id"]
run_dir = Path(best_row["model_dir"])   # <-- absolute path, base_tag included

with open(run_dir / "artifacts.pkl", "rb") as f:
    art = pickle.load(f)
predictor_a = TabularPredictor.load(str(run_dir / "model_a"))
predictor_b = TabularPredictor.load(str(run_dir / "model_b"))

print(RUN_ID)
art["calibration_after"]

annealing-uts-v1-test__time_limit_a=120__num_bag_folds_a=10__features=initial_diameter-tensile_strength-temperature-time__9b0ba1d3

   alpha  empirical_coverage       gap
0   0.50            0.586957  0.086957
1   0.80            0.858696  0.058696
2   0.90            0.934783  0.034783
3   0.95            0.945652 -0.004348